### ISSUE TITLE
NPqq toolbar icons are invisible with system dark themes

### ISSUE THREAD

**Issue by ineuw** [notepadqq/notepadqq#1002]
**Describe the bug**
NPqq toolbar icons are invisible with system dark themes

**To Reproduce**
Try any dark theme in Linux Mint Cinnamon 20.1 

**Expected behavior**
Most toolbar icons are invisible

**Screenshots**
![210630npqq-toolbar-icons](https://user-images.githubusercontent.com/10367016/124050515-b0654900-d9e8-11eb-8f9f-9403ea1559cf.png)

**Environment (please complete the following information):**
Linux Mint Cinnamon 20.1 

 Notepadqq version
v2.0.0.beta-git

**Comment by robertapengelly** [comment]
@ineuw Check the icon theme within QT5 Configuration Settings as changing the theme within there fixed the issue for me.

**Comment by danieleds** [comment]
Thanks - @robertapengelly @ineuw can this issue be closed?
