### ISSUE TITLE
Adjustable Font Size

### ISSUE THREAD

**Issue by jgedri** [notepadqq/notepadqq#1012]
**Is your feature request related to a problem? Please describe.*
I'm running Xubuntu 20.04 on a laptop with 1366x768 resolution. The text in notepadqq is just shy of being too small to read.
**Describe the solution you'd like**
Add the ability to adjust the font size.

**Describe alternatives you've considered**

**Additional context**
![Screenshot_2021-09-09_09-35-11](https://user-images.githubusercontent.com/24856045/132695892-38c38ca5-7c8c-47b5-b21e-2425f90443be.png)

**Comment by robertapengelly** [comment]
@jgedri If your talking about the editor text within each tab then the go to Settings > Preferences > Appearance, check the Override Font Size box and change it to a size that you like.
