### ISSUE TITLE
Shortcut to duplicate line

### ISSUE THREAD

**Issue by flavio20002** [notepadqq/notepadqq#102]
In notepad++ the shortcut CTRL-D duplicate the current line, while CTRL-L delete it. 
Look at: 

http://www.keyxl.com/aaacd5a/43/Notepad-Plus-text-editor-software-keyboard-shortcuts.htm

If you agree, i can modify it with a pull request.

**Comment by danieleds** [comment]
Sure, thanks!

**Comment by danieleds** [comment]
Closed with 8715532c1ec47ac537525191f568ba101c252b02
