### ISSUE TITLE
Good afternoon! Help me get the menu back

### ISSUE THREAD

**Issue by nlime** [notepadqq/notepadqq#1025]
![qq](https://user-images.githubusercontent.com/59861893/146367488-236ce43c-ccfe-4d65-a07b-dff274a7cecf.png)
![qq_2](https://user-images.githubusercontent.com/59861893/146378851-c5d502fd-381f-475e-8c45-2395dd3900e4.png)

**Comment by onemannoplan** [comment]
I'm not sure which OS you're on, but the hotkey I use to get it back is Ctrl+M

**Comment by nlime** [comment]
thanks
