### ISSUE TITLE
Selecting files uses single-clicks instead of double-clicks, violating conventional UI design

### ISSUE THREAD

**Issue by AreaDenial** [notepadqq/notepadqq#1029]
Today, I lost weeks of work because of a simple UI issue. It all happened because I double-clicked a folder to choose where I wanted to save a new file.

What happened was the first click opened the folder, and the second click selected a file to save over. A window popped up saying "Are you sure you want to overwrite this file" or something, and I barely noticed what had happened and tried to click "No". I misread, and clicked "Yes" instead.

Now, accidentally clicking "Yes" when I meant to click "No" is perfectly understandable, it could have happened to anybody in any program. But it never would have happened in the first place if the UI was consistent with every other UI I've ever used in my life, across multiple operating systems and applications. Any time I'm navigating in a file explorer, a double-click is required to enter a folder or choose a file. But for some reason, Notepadqq decides to use single clicks instead. This will cause users used to double-clicking to make the same mistake I did, opening the wrong folder in the best case or in the worst case, overwriting something they didn't mean to.

**To Reproduce**
1. Create a new text file and save it.
2. Within the file navigation window, double click on a folder with files in it.
3. You will be prompted to overwrite whatever file your mouse was over upon the second click.

**Expected behavior**
I expected a double click to open the folder, instead of open the folder on the first click and choose a file to overwrite on the second click.

**Environment (please complete the following information):**
 - OS: Garuda Linux
 - Installation type: from official community repositories (idk, just installed it from pamac)
 - Qt version: 5.15.2
 - Notepadqq version: v1.4.8

**Comment by robertapengelly** [comment]
@AreaDenial I think the problem is related to the QT configuration with regards to your desktop environment as I have the GNOME version of Garuda Linux installed and I need to double click to enter a directory when I'm saving a new document.  It may also be worth noting that I have QT version 5.15.5 not 5.15.2.  Are you using KDE or GNOME as your desktop environment?  Is your version of QT the latest version?  Also have you tried other distros with the same desktop environment to see if it's isolated to Garuda Linux or not?

**Comment by AreaDenial** [comment]
@robertapengelly Thank you for the detailed reply. I'm using QT 5.15.5, and my desktop environment is XFCE. Thanks to your info, I was able to easily solve the issue by opening "Qt5 Configuration Tool", and found a checkbox under the interface tab: "Activate item on single-click", which was checked. Unchecking this box fixes the issue.

**Comment by robertapengelly** [comment]
Awesome, glad it helped.
