### ISSUE TITLE
Installed Notepadqq 2.0.0-beta+git no way to uninstall/purge

### ISSUE THREAD

**Issue by ACR-Jeff** [notepadqq/notepadqq#1045]
**Describe the bug**
I installed Notepadqq 2.0.0-beta+git from source and it has had nothing but glitches and crashing so I just want to uninstall/purge it off of my system. Yet there are no instructions on how to uninstall/purge it. I even tried to uninstall from the source. Yet there are no instructions there as well. Thanks for any help.

**To Reproduce**
$ notepadqq -v
Notepadqq 2.0.0-beta+git
$ sudo apt purge notepadqq
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package notepadqq
$ sudo apt-get purge notepadqq
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package notepadqq

**Environment (please complete the following information):**
 - OS: Debian 11 Bullseye
 - Installation type [git per instructions on the readme]
 - Qt version [Version 5.15.2]
 - Notepadqq version [Notepadqq 2.0.0-beta+git]

**Comment by robertapengelly** [comment]
When you say installed do you mean through the package manager or from the repo?  The apt purge will only work if a package is installed through apt, if you installed it through the repo then you will need to manually remove the files (at least until there's an uninstall option within the makefile).

**Comment by ACR-Jeff** [comment]
@robertapengelly Thank you for your reply, I installed it from the repo per the instructions on this github, Well that sounds a lot like Malware without having any way to uninstall it from the repo. What a way to clutter up the file system and Etc.

**Comment by robertapengelly** [comment]
@ACR-Jeff it's not malware it's just the way systems work it would be the same if you extracted something from a zip or tar file as very often there's no uninstall file which again would require manual deletion
