### ISSUE TITLE
Build fails on QT5 check

### ISSUE THREAD

**Issue by sri-arjuna** [notepadqq/notepadqq#118]
Since the changes in ./configure i can no longer build.
I did install the new requirement qtchooser, but the build still fails:

And even when i disable the QT5 check on line 104, a regular build fails later on on what i assume to be related with the codemirror empty dir check:
https://github.com/notepadqq/notepadqq/commit/90e1ccc37fa6985bcb16957731da4d3e3fc329bc

Anyway, here is my output:

	✔ notepadqq $ sudo yum install -y qt5-qtsvg-devel qt5-qtwebkit-devel qt-creator qtchooser qt5-qtwebkit qt5-qtsvg 
	Loaded plugins: langpacks
	Package qt5-qtsvg-devel-5.4.0-1.fc21.x86_64 already installed and latest version
	Package qt5-qtwebkit-devel-5.4.0-1.fc21.x86_64 already installed and latest version
	Package qt-creator-3.3.1-1.fc21.x86_64 already installed and latest version
	Package qtchooser-39-5.fc21.x86_64 already installed and latest version
	Package qt5-qtwebkit-5.4.0-1.fc21.x86_64 already installed and latest version
	Package qt5-qtsvg-5.4.0-1.fc21.x86_64 already installed and latest version
	Nothing to do
	## QT5 is installed! ##

	:) notepadqq $ ./configure --prefix=/usr
	checking for QT5 qmake... not found!

	:( notepadqq $ ./configure --prefix=/usr
	## Disabled check on line 104... ##
	checking for QT5 qmake... checking for c++... /bin/c++
	checking whether c++ compiler builds test program... ok
	checking whether c++ compiler supports -std=c++0x... ok
	checking whether compiled test program works... ok
	checking for make... /bin/make
	checking for git... /bin/git
	checking for pkg-config... /bin/pkg-config
	checking for Qt5Core library... -lQt5Core 
	checking for Qt5Gui library... -lQt5Gui -lQt5Core 
	checking for Qt5Network library... -lQt5Network -lQt5Core 
	checking for Qt5WebKit library... -lQt5WebKit -lQt5Gui -lQt5Network -lQt5Core 
	checking for Qt5Widgets library... -lQt5Widgets -lQt5Gui -lQt5Core 
	checking for Qt5WebKitWidgets library... -lQt5WebKitWidgets -lQt5Widgets -lQt5WebKit -lQt5Gui -lQt5Network -lQt5Core 
	checking for Qt5PrintSupport library... -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core 
	checking for Qt5Svg library... -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Core 
	./configure: line 157: test: too many arguments
	error: CodeMirror submodule not available at `src/editor/libs/codemirror'!

	✘ notepadqq $ 

From this point of view, i'd like to have the old ./configure back ;)
Any ideas?

**Comment by darealshinji** [comment]
Try to change `test $(ls -A $cmdir)` to `test "$(ls -A $cmdir)"`.
As for the configure script, well, that's only a little helper script to make configuring and checking dependencies easier. You could always fallback to running qmake directly.
qtchooser isn't a requirement either, it's just the default qmake command that's used to check if qt5-qmake is available. You can run something like `./configure --qmake=/usr/bin/qmake-qt5` instead.

**Comment by sri-arjuna** [comment]
The quotes and suggested argument solved it.
Thanks
