### ISSUE TITLE
"undo all" option

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#124]
Let's say I do something like replacing all instances of "e" with "a" in a document; to undo that I'll have to hold down ctrl+z and wait until the editor is done, which takes quite a lot of time.
I'd like it there was either an "undo all" function which reverts everything until the point where I have loaded or saved the document, or - even better - a single "undo" will redo everything that was done with the replace function.

**Comment by danieleds** [comment]
What about File -> Reload from Disk?

**Comment by darealshinji** [comment]
That would however delete all the changes I've made between my last save and the last replacement.

**Comment by danieleds** [comment]
Hmm, wasn't you asking exactly that?
> reverts everything until the point where I have loaded or saved the document

It makes sense to treat the "Replace All" button as a single undo event, though.

**Comment by danieleds** [comment]
Working on it... I'm waiting for https://github.com/codemirror/CodeMirror/pull/3153 to be merged.

**Comment by danieleds** [comment]
Fixed in 7c4243cb4df866d5f4f44c8f063695e142aa0a7a!
