### ISSUE TITLE
error: CodeMirror submodule not available at `src/editor/libs/codemirror'!

### ISSUE THREAD

**Issue by jackfido** [notepadqq/notepadqq#125]
Im not familiar with linux compilation, im receive this error:

jackfido@JAcKFiDo:~/Downloads/notepadqq-master$ ./configure --prefix /usr
checking for QT5 qmake... qtchooser -run-tool=qmake -qt=5
checking for c++... /usr/bin/c++
checking whether c++ compiler builds test program... ok
checking whether c++ compiler supports -std=c++0x... ok
checking whether compiled test program works... ok
checking for make... /usr/bin/make
checking for git... not found!
checking for pkg-config... /usr/bin/pkg-config
checking for Qt5Core library... -lQt5Core 
checking for Qt5Gui library... -lQt5Gui -lQt5Core 
checking for Qt5Network library... -lQt5Network -lQt5Core 
checking for Qt5WebKit library... -lQt5WebKit -lQt5Gui -lQt5Network -lQt5Core 
checking for Qt5Widgets library... -lQt5Widgets -lQt5Gui -lQt5Core 
checking for Qt5WebKitWidgets library... -lQt5WebKitWidgets -lQt5Quick -lQt5Qml -lQt5PrintSupport -lQt5OpenGL -lQt5Widgets -lQt5WebKit -lQt5Gui -lQt5Network -lQt5Core 
checking for Qt5PrintSupport library... -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core 
checking for Qt5Svg library... -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Core 
error: CodeMirror submodule not available at `src/editor/libs/codemirror'!
jackfido@JAcKFiDo:~/Downloads/notepadqq-master$

**Comment by danieleds** [comment]
Looks like you're missing git. Try installing it first!

**Comment by darealshinji** [comment]
To clarify it, install git, download the repository with git and then run configure again. Then it will automatically download the CodeMirror submodule.

**Comment by danieleds** [comment]
@darealshinji thanks, I wrongly assumed it already was a git repo.

**Comment by jackfido** [comment]
Yea, thnx, now it is installed!
