### ISSUE TITLE
Is there a way to turn off the indent warning?

### ISSUE THREAD

**Issue by LavaSlayer** [notepadqq/notepadqq#126]
Whenever I open a file, I see a blue bar at the top stating "This file is indented with spaces, but your current settings specify to use tabs," with the option to "Use Spaces" or "Ignore".

I use Notepadqq primarily for Minecraft mod config files (written by a variety of authors), and these come in several flavors of indent styles/sizes.  I would like to disable the indent warning so that I don't have to click Ignore every time I open a file.  Is there a way to turn this off?

Thank you.

**Comment by danieleds** [comment]
Currently no, there's not a way. I'll add a setting asap.
