### ISSUE TITLE
Memory Usage & rnd Freeze

### ISSUE THREAD

**Issue by sri-arjuna** [notepadqq/notepadqq#129]
With 3 files open, 2500 lines, 700 lines, 5 lines, it uses more memory than my Firefox with 12 tabs, ffplay, xorg and irc together.
It even freezes at times for aprox 1-2 min, i can still switch desktops/windows and all work but notepad not :(
Freeze seems to happen randomly, but most of the times when scrolling up/down alot, combined with mouse entering and leaving the notepad window.

Just guessing (not pun intended, exp from my own projects) use less loops, and dont make functions call themself.
Also, at times, eg just while writing. my cpu temp increase up to 80°C, closed notepadqq as it hung up itself and its down to 60°C again.

Please let me know what info you need.

Thank you.

**Comment by danieleds** [comment]
Hi, I tried with 3 files: 4000 lines, 800 lines, and 10 lines, without any problem on my machine.
Can you tell me how much memory notepadqq uses on your pc?
Also, could be useful to know the file types you used (what syntax highlighter was active).

Thanks!

**Comment by sri-arjuna** [comment]
0.45.2, all 3 were bash scripts with active hightlighting.
It used roughly about 2.6 gb (~2598xxxyyy) virtual memory.

But i guess its not really related to the file size, currently having more files open (and the same as then) and had less freezes.

There were some QT packages listed during the update this morning...
I'm just rebuilding NQ and will install the current gitbuild in a few.

**Comment by danieleds** [comment]
The latest commits in 0.46.1, especially 02746f4, highly improve the memory usage... Let me know if the situation gets better

**Comment by sri-arjuna** [comment]
Something different, but quite similar.
I'm currently writing a script to build ffmpeg with several features (deps/libs), due to the nature of this complexity, for each failed build it opens a logfile - or notepadqq asks to reload the file if already opened.
Simplified example:

     make && sudo make install || notepadd logfile

Anyway, so i had multiple files open and was clicking on "Reload file" (twice, within 2 secs :smile: ) and notepadqq closed itself, while having an unsaved doc 'open'.

Also didnt happen for the first time, but with the new 0.46.1 it did.

Other than that, memory usage IS better so far!
Thank you

**Comment by danieleds** [comment]
Hmm ok!
I tried to reproduce the "Reload file" crash without any success... Are you able to reproduce it?

Thanks!

**Comment by danieleds** [comment]
Closing for now
