### ISSUE TITLE
Start with maximized window 

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#132]
The window doesn't start maximized if I use the system's Qt version. I previously used the Qt libraries from http://www.qt.io/ but now I need an account to install or update these and I don't want that.
I'm using Ubuntu 14.04.

**Comment by danieleds** [comment]
What's your system version?
What do you mean with "the window doesn't start maximized"? It *never* starts maximized even if you close Notepadqq while it is maximized?

**Comment by darealshinji** [comment]
I'm using Qt 5.2.1.
>It never starts maximized even if you close Notepadqq while it is maximized?

This. And it didn't happen with the newer Qt libraries.

**Comment by sri-arjuna** [comment]
Me having a 'maximized' notepadqq started up, due to the WM filling all the desktop space -- so far expected and as used to be, i have to switch it floating and back fitting to arange itself with other open windows (thats new/bad).
Its overlapping everything else, even if other things are started later, they disapear behind nqq.

Using AwesomeWM on Fedora 22 with a 1920x1080 and qt5-qttools: 5.4.1

**Comment by darealshinji** [comment]
Okay, I either didn't realize it back then or they changed something, but to install the "Community Open Source" version from http://www.qt.io/download-open-source/ you appearently don't need an account. And with the library version 5.4.1 the windows are now opening fullscreen.

**Comment by sri-arjuna** [comment]
Not quite sure what changed. but its d/gone (for me).
qt5-tools: 5.4.1-2

**Comment by danieleds** [comment]
Ok!
Closing for now ;)

**Comment by darealshinji** [comment]
This problem somehow reappeared for me. I'm now using Kubuntu 15.04.
I have this problem with the system Qt libraries and the Qt installer libraries (version 5.4.2 and 5.4.1).

**Comment by danieleds** [comment]
Can you try to remove `~/.config/notepadqq/Notepadqq.conf` and see what happens?

**Comment by darealshinji** [comment]
That did it. Great.
