### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#134]
I thought I should try to create a better looking icon for nqq.

Here's what I got:
![notepadqq](https://cloud.githubusercontent.com/assets/5700937/7728740/479c0eb2-ff11-11e4-890b-90667627a9ae.png)
([svg version](https://gist.github.com/darealshinji/f9c4bf55ba6fd63288a9))

It's a modified combination of two Mint-X icons: [accessories-text-editor.svg](https://github.com/linuxmint/mint-x-icons/blob/master/usr/share/icons/Mint-X/apps/96/accessories-text-editor.svg) and [text-richtext.svg](https://github.com/linuxmint/mint-x-icons/blob/master/usr/share/icons/Mint-X/mimetypes/96/text-richtext.svg).

What do you think?

**Comment by sri-arjuna** [comment]
Sure looks better than the current :)

**Comment by danieleds** [comment]
Nice!
I believe it will need some minor modifications, but it's ok.
I'll leave this issue open until I have some time to think about it! I'd like to seek advice from some graphic designer too.

**Comment by darealshinji** [comment]
I didn't see that you were working on a new logo.
![logo](https://cloud.githubusercontent.com/assets/5700937/11316516/9f8f22dc-900a-11e5-8017-377ac7e51981.png)
I think it looks very good so far. When are you going to use it?

**Comment by danieleds** [comment]
@darealshinji I'm glad you like it!
I'd like to use it as soon as possible, hopefully in the next release... I'm extremely busy right now, and I would like to ask to a few more people about it, but it's definitely going to make it for a close release.

**Comment by danieleds** [comment]
The new icon has been published :)
Thank you!

**Comment by flamusdiu** [comment]
yeah like this last one. =) Makes it stand out from similar apps.
