### ISSUE TITLE
Message line in preferences window too long

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#136]
Needs to be adjusted a little.

![preferences](https://cloud.githubusercontent.com/assets/5700937/7827284/bafdfe4c-0425-11e5-97ac-640600bbbb71.png)

**Comment by danieleds** [comment]
Version?
I think it might be already fixed in the Extensions branch

**Comment by darealshinji** [comment]
Current build from master branch.

**Comment by danieleds** [comment]
Closed with the merge at 736e837258454e87d0c1a01c1183468ed2531e08

**Comment by darealshinji** [comment]
That did it. Thanks.
