### ISSUE TITLE
Moving mouse while using mouse wheel resets scroll position

### ISSUE THREAD

**Issue by Toverbal** [notepadqq/notepadqq#138]
When scrolling through a document using the mouse wheel, the scroll position will reset after you change the mouse pointer position and use the wheel to scroll again.

To reproduce:

1. Open/create a document which contains a vertical scrollbar
2. Use the mouse wheel to scroll down a few lines
3. Move the mouse pointer position
4. Use the mouse sheel again to scroll down again and the scroll position is reset to the position it had on step 2.

This is particularly annoying when you by accident move the cursor a bit when scrolling through a document.
 
Using Ubuntu 15.04 in VirtualBox on a Windows 8 host.

**Comment by darealshinji** [comment]
I'm using a native installation of Ubuntu 15.04 (KDE) and I don't have such problems. Maybe it's related to VirtualBox or the desktop environment you're using (Unity I assume)?

**Comment by danieleds** [comment]
Tried on Ubuntu 15.04 with Unity, Qt 5.4.1, without finding any any problem.

As @darealshinji says, it could be related to a VirtualBox issue.
What version of Qt are you using? `Menu ? -> About Qt...`

**Comment by Toverbal** [comment]
I have version 5.4.1 of Qt. I've also tried full screen, but it doesn't make a difference. When I, however, disable Mouse Intergration in VBox, it works (but then I don't see a mouse cursor in my VM). So it seems to be a VBox issue, but other editors don't show this behaviour (e.g. GEdit, Sublime or LibreOffice). Any ideas?

**Comment by raburton** [comment]
I'm getting the same in virtualbox, but for me it does affect other things (even the basic terminal), so I suspect it isn't something notepadqq is going to be able to fix.

**Comment by danieleds** [comment]
Ok, closing as it looks it's a VirtualBox issue. If you have news, feel free to reopen :)

**Comment by 0pm** [comment]
i have same problem,
currently working on ubuntu 16.04 with latest version of notepadqq and when i scroll up, it suddenly scrolls down the page. it's sometimes annoying , you should drag the scroller bar and slide to top or bottom.
please fix it.
thanks.
