### ISSUE TITLE
python long lists issue

### ISSUE THREAD

**Issue by drdhaval2785** [notepadqq/notepadqq#139]
![screenshot from 2015-07-15 09 18 55](https://cloud.githubusercontent.com/assets/5755132/8690488/a8948428-2ad2-11e5-8d9c-2bdaf067e516.png)

There are long lists in my python code.
After some time the syntax highlighting breaks without any wrong syntax in the code.

The other offshoot of this issue is that every time I press Enter to go on next line after this syntax highlight break, the indentation is 16 spaces / 4 tabs / 3 tabs and 4 spaces.

**Comment by drdhaval2785** [comment]
To note, there is no problem in execution of code because of syntax highlighting issue.

But everytime i add a line, I have to press backspace 16 times to go to the first line and indent 4 spaces again.

Very annoying to code in such a scenario.

**Comment by darealshinji** [comment]
I'm having issues with very long lines too.
A good example is this 5 MB one-liner text file: https://github.com/nagadomi/waifu2x/blob/master/models/anime_style_art/noise2_model.json
Without line wrap I can't even scroll horizontally and when line wrapping is activated I have the same syntax highlight breaking issue.

**Comment by danieleds** [comment]
You should report this bug to CodeMirror! https://github.com/codemirror/codemirror
Thanks
