### ISSUE TITLE
Customize keyboard shortcuts?

### ISSUE THREAD

**Issue by saintsfan342000** [notepadqq/notepadqq#143]
Happy to have found notepadqq.  Just wondering if there's a way to specify a keyboard shortcut for an existing menu item.  Specifically, I'd like to set one for "Copy Full File Path to Clipboard".

 I found this in the API but don't know where to implement it:
http://notepadqq.altervista.org/docs/0.50/Objects/MenuItem/#itemsetshortcutshortcut

Thanks for any and all help.

**Comment by danieleds** [comment]
Hi! Sorry for the late reply.
No, currently there's not the possibility to customize keyboard shortcuts, even with the APIs for extensions.

But if you have a suggestion for the shortcut to use for "Copy Full File Path to Clipboard", I can add it directly.

**Comment by saintsfan342000** [comment]
No worries.  The two I seem to use most often are Ctrl+Shift+C for "Copy Full File Path to Clipboard", and Ctrl+Shift+A for "Show All Characters".  I'm just one user among many, though, so who knows if others would find these useful.  Thank you!

**Comment by mannol** [comment]
Is this feature planned in a near future?

**Comment by danieleds** [comment]
@mannol not "near", sorry :/
I'll happily accept pull requests, if someone has time to work on this.

**Comment by kouul** [comment]
Is there any keyboard shortcut to Launch in Chrome?

**Comment by Teklad** [comment]
Go ahead and assign this to me.  I'm working on an implementation of it now.  Just figuring out the fine details in places. :)

**Comment by mannol** [comment]
Wonderful news! Thank you @Teklad and @danieleds!
