### ISSUE TITLE
Set tab size ?

### ISSUE THREAD

**Issue by sri-arjuna** [notepadqq/notepadqq#144]
Installed using prefix /usr.
When changing the tab size, it accepted 'once' to go down to 4.
Eversince, only within the preferences dialog it applies the tab size = 8, but does not apply it to the text.

I was looking to change settings manualy, but could not find anything in **~/.config/***.

**Comment by danieleds** [comment]
That's strage. Can you check that Notepadqq has write permissions for ~/config/Notepadqq?

**Comment by sri-arjuna** [comment]
I wasnt finding anything, because i was just looking for small letters, and yes Notepadqq has write access, at least, my user account has. ;)

I'm on a GNU/Linux only system, as in : no WINE, but i do have a a Notepadqq.ini and a Notepadqq.conf file in there.

Observed executing (with already started):

    notepadqq ~/.config/Notepadqq/*

It seems, it does write the settings - as it contains the 'current value 8', to the *conf file, but constantly read/writes to the *ini file - which still contains the 'old value 4'.

**Comment by danieleds** [comment]
The .conf file is related to past versions, you can delete it.
Maybe this was causing the problem?

**Comment by sri-arjuna** [comment]
Removed the \*conf file.
*Opened the ini file, seems its constantly writing to it, as it keeps asking to reload the just opened file since it content had changed?*
Once i manualy saved the current file 'as opened', it stoped asking for reload.

Anyway, tab stops seem to work again.
Guess that really was causing the issue.

Thank you and keep it up! :)
