### ISSUE TITLE
Weird issue in WM

### ISSUE THREAD

**Issue by sri-arjuna** [notepadqq/notepadqq#151]
Not sure if it is solvable within NQQ (54.1), QT, the WM (awesome 3.5.6, lua 5.3.0) or Xorg.
But reporting here is easiest to me, and the last two are the 'oldest'.

Everytime i suspend my laptop and start again later, the menu and bar of the WM are no longer usable, until i restart notepadqq.
I could open the menu via hotkey, but the mouse-click on it was not recognized - 'enter' was.

Priority: _very low_, if i'm alone with this - doesnt really bother me since i use hotkeys most of the time.
More of a related issue, is anyone else here using NQQ on AwesomeWM? - would help to elaborate the source of this.

Thank you

**Comment by sri-arjuna** [comment]
Ok, been using pluma since last post, there were several (~7) suspenses of the laptop, without issue.
But then again, thats GTK3 - not QT5.

**Comment by Teklad** [comment]
This was a WM suspend issue.  Should be able to close this... I use awesome and it doesn't appear to have this problem anymore. :)
