### ISSUE TITLE
Change default editor font

### ISSUE THREAD

**Issue by Swyter** [notepadqq/notepadqq#152]
This is basic functionality. I still haven't found an easy way to change it.

It's a bit funny that a complex, fully-fledged CSS-based code highlight framework like _Codemirror_ does not expose something that even _Notepad_ has.

I think it should be high on the to-do list. Anyway, keep it up.

**Comment by xnko** [comment]
While there is no settings for that, you can change font-family in the file `/usr/share/notepadqq/editor/libs/codemirror/lib/codemirro.css`

**Comment by akien-mga** [comment]
I'd be interested in this feature too, the default font is not monospace so it's the first thing I wanted to change when starting notepadqq for the first time.

**Comment by danieleds** [comment]
@akien-mga It should be. What distro are you using?

**Comment by akien-mga** [comment]
Mageia 6; I just packaged notepadqq for its official repositories: http://svnweb.mageia.org/packages/cauldron/notepadqq/current/SPECS/notepadqq.spec?view=markup&pathrev=987360

Building against CodeMirror 5.3.0. Here's how the font looks like (with custom colours that I chose while testing, but it does not impact the font):

![spectacle m24589](https://cloud.githubusercontent.com/assets/4701338/13616217/38381228-e579-11e5-80b3-369d8b92e5cf.png)

**Comment by akien-mga** [comment]
I'll test a clean build from source without the packaging step, it might be related to something in my packaging I guess.

**Comment by akien-mga** [comment]
Same thing with a build from HEAD using updated git submodules.

**Comment by danieleds** [comment]
Are you able to see monospace fonts in e.g. Google Chrome / Chromium?

**Comment by OhDaeto** [comment]
Updated Arch to qt 5.6 and now I do not know how to return the previous font.

**Comment by Teklad** [comment]
This issue was resolved in: #245 .... can now be closed.
