### ISSUE TITLE
there is for opensuse to binary?

### ISSUE THREAD

**Issue by manuelsongokuh** [notepadqq/notepadqq#153]
i wish to use it in m y opensuse, maybe best binary without rpm packed?

**Comment by sri-arjuna** [comment]
From source:

    git clone https://github.com/notepadqq/notepadqq.git
    cd notepadqq
    ./configure --prefix=/usr
    make && sudo make install

Uninstall then works like:

    cd <to where the files were git cloned to...>
    sudo make uninstall

hth

**Comment by manuelsongokuh** [comment]
there are errors:
gokuh@linux-h4bi:~/notepadqq> ./configure --prefix=/usr --qmake /usr/bin/qmake
checking for QT5 qmake... /usr/bin/qmake
checking for c++... /usr/bin/c++
checking whether c++ compiler builds test program... ok
checking whether c++ compiler supports -std=c++0x... ok
checking whether compiled test program works... ok
checking for make... /usr/bin/make
checking for git... /usr/bin/git
checking for pkg-config... /usr/bin/pkg-config
checking for Qt5Core library... not found!
checking for Qt5Gui library... not found!
checking for Qt5Network library... not found!
checking for Qt5WebKit library... not found!
checking for Qt5Widgets library... not found!
checking for Qt5WebKitWidgets library... not found!
checking for Qt5PrintSupport library... not found!
checking for Qt5Svg library... not found!
Submodule 'src/editor/libs/codemirror' (https://github.com/notepadqq/CodeMirror.git) registered for path 'src/editor/libs/codemirror'
Cloning into 'src/editor/libs/codemirror'...
remote: Counting objects: 28178, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 28178 (delta 4), reused 2 (delta 2), pack-reused 28170
Ricezione degli oggetti: 100% (28178/28178), 14.35 MiB | 1.25 MiB/s, done.
Risoluzione dei delta: 100% (16500/16500), done.
Checking connectivity... fatto.
Submodule path 'src/editor/libs/codemirror': checked out '07ed65833bd7b5c92ecfc0adea5f82e5cc2ecc78'
generate Makefile... done
gokuh@linux-h4bi:~/notepadqq> make && sudo make install
cd src/ui/ && /usr/bin/qmake /home/gokuh/notepadqq/src/ui/ui.pro PREFIX=/usr QMAKE_CXX=c++ QMAKE_CXXFLAGS=\  QMAKE_LFLAGS= -o Makefile
WARNING: /home/gokuh/notepadqq/src/ui/ui.pro:22: Variable QMAKE_RPATH is deprecated; use QMAKE_LFLAGS_RPATH instead.
Project MESSAGE: Release build
cd src/ui/ && make -f Makefile 
make[1]: ingresso nella directory "/home/gokuh/notepadqq/src/ui"
(cd "/home/gokuh/notepadqq/src/ui" && rm -rf "../../out/release/lib/../appdata/editor" && cd "../editor" && make DESTDIR="../../out/release/lib/../appdata/editor")
make[2]: ingresso nella directory "/home/gokuh/notepadqq/src/editor"
mkdir -p "../../out/release/lib/../appdata/editor"
cp -r classes styles images app.js index.html init.js "../../out/release/lib/../appdata/editor"/
mkdir -p "../../out/release/lib/../appdata/editor"/libs
cp -r libs/jquery "../../out/release/lib/../appdata/editor"/libs/jquery/
# Call CodeMirror makefile passing DESTDIR as absolute path, so we have no problems with cd-ing to libs
make -C libs -f Makefile-codemirror DESTDIR="/home/gokuh/notepadqq/out/release/appdata/editor"/libs/codemirror
make[3]: ingresso nella directory "/home/gokuh/notepadqq/src/editor/libs"
mkdir -p "/home/gokuh/notepadqq/out/release/appdata/editor/libs/codemirror"
cd codemirror && cp -r addon keymap lib mode theme LICENSE "/home/gokuh/notepadqq/out/release/appdata/editor/libs/codemirror"/
# Clean unnecessary files within "mode"
find "/home/gokuh/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/ -type f -name '*.html' -exec rm -f {} +
find "/home/gokuh/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/ -type f -name 'test.js' -exec rm -f {} +
cd "/home/gokuh/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/m4/ && rm -f *.txt *.sh *.in
make[3]: uscita dalla directory "/home/gokuh/notepadqq/src/editor/libs"
make[2]: uscita dalla directory "/home/gokuh/notepadqq/src/editor"
(cd "/home/gokuh/notepadqq/src/ui" && rm -rf "../../out/release/lib/../appdata/extension_tools" && cd "../extension_tools" && make DESTDIR="../../out/release/lib/../appdata/extension_tools")
make[2]: ingresso nella directory "/home/gokuh/notepadqq/src/extension_tools"
mkdir -p "../../out/release/lib/../appdata/extension_tools"
cp -r node_modules install.js pack.js package.json readmanifest.js "../../out/release/lib/../appdata/extension_tools"/
make[2]: uscita dalla directory "/home/gokuh/notepadqq/src/extension_tools"
(cd "/home/gokuh/notepadqq/src/ui" && mkdir -p "../../out/release/lib/../bin/" && cp -f "../../support_files/launch/notepadqq" "../../out/release/lib/../bin/" && chmod 755 "../../out/release/lib/../bin/notepadqq")
/usr/bin/uic mainwindow.ui -o ../../out/build_data/ui_mainwindow.h
/usr/bin/uic frmabout.ui -o ../../out/build_data/ui_frmabout.h
/usr/bin/uic frmpreferences.ui -o ../../out/build_data/ui_frmpreferences.h
/usr/bin/uic frmencodingchooser.ui -o ../../out/build_data/ui_frmencodingchooser.h
/usr/bin/uic frmindentationmode.ui -o ../../out/build_data/ui_frmindentationmode.h
/usr/bin/uic Search/dlgsearching.ui -o ../../out/build_data/ui_dlgsearching.h
/usr/bin/uic Search/frmsearchreplace.ui -o ../../out/build_data/ui_frmsearchreplace.h
/usr/bin/uic frmlinenumberchooser.ui -o ../../out/build_data/ui_frmlinenumberchooser.h
/usr/bin/uic Extensions/installextension.ui -o ../../out/build_data/ui_installextension.h
c++ -c -O2 -Wall -W -Wold-style-cast -D_REENTRANT -DQT_WEBKIT -DQT_NO_URL_CAST_FROM_STRING -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtSvg -I/usr/include -I../../out/build_data -I../../out/build_data -o ../../out/build_data/main.o main.cpp
In file included from ./include/EditorNS/editor.h:4:0,
                 from ./include/editortabwidget.h:6,
                 from ./include/topeditorcontainer.h:6,
                 from include/mainwindow.h:5,
                 from main.cpp:2:
./include/EditorNS/customqwebview.h:4:20: fatal error: QWebView: File o directory non esistente
 #include <QWebView>
                    ^
compilation terminated.
Makefile:643: set di istruzioni per l'obiettivo "../../out/build_data/main.o" non riuscito
make[1]: *** [../../out/build_data/main.o] Errore 1
make[1]: uscita dalla directory "/home/gokuh/notepadqq/src/ui"
Makefile:39: set di istruzioni per l'obiettivo "sub-src-ui-make_default" non riuscito
make: *** [sub-src-ui-make_default] Errore 2
gokuh@linux-h4bi:~/notepadqq>

**Comment by manuelsongokuh** [comment]
this is not resolved or is resolved..?

**Comment by danieleds** [comment]
I believe you are missing some dependencies.
Follow the instructions in the readme: https://github.com/notepadqq/notepadqq/blob/master/README.md
