### ISSUE TITLE
Add "Replace all in open files" option

### ISSUE THREAD

**Issue by CJCombrink** [notepadqq/notepadqq#154]
Would be nice to have a "Replace all in open files" option on the Search widget. 
##

**Comment by grenzor** [comment]
+1

**Comment by dpolivaev** [comment]
+1

**Comment by xproofx** [comment]
+1

**Comment by dpolivaev** [comment]
I use geany now because it can what notepadqq can't.

**Comment by danieleds** [comment]
That's the spirit!

**Comment by xproofx** [comment]
LOL, danieleds.

**Comment by versavius** [comment]
Was this feature ever implimented as I can't find it in the search widget which I access from the menu "Search > Replace"?
