### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by intialonso** [notepadqq/notepadqq#156]
Hi, how can I help to translate NotepadQQ to my language (Spanish)?

**Comment by lumon13** [comment]
I want to know this too... I want to translate it to PT-BR

**Comment by darealshinji** [comment]
You can use Qt Linguist to create translations. I've created a German localization: https://github.com/notepadqq/notepadqq/pull/157

**Comment by mlopezcoria** [comment]
Initialonso, I want to help with spanish translation too. We can work together. Let me know what are you on, now. Regards

**Comment by intialonso** [comment]
@mlopezcoria aún no he comenzado, no he tenido el tiempo necesario.

**Comment by xDShot** [comment]
Hi. Me and my friend are interested in adding Russian translation. We have Qt Liguist 5.5.1 already installed, but we still don't get it how to add new localization and what we should change in source code to make it appeared.

@darealshinji @danieleds could you please write a guide on translating please?

Thanks in advance and thank you for such great project :)

**Comment by vpop** [comment]
[This](http://stackoverflow.com/a/34385559/1454261) answer from Stackoverflow provides a nice overview of the process. Hopefully it will give you some pointers to get you started.

Now if you want to see the translation in action for an existing .qm file, change _main.cpp_ by replacing the default constructor `QLocale()` at [line 42](https://github.com/notepadqq/notepadqq/blob/master/src/ui/main.cpp#L42) (in my case based on paths) to an overloaded constructor to which you provide the language as argument, or with a language and country combination, etc. Check the [`QLocale`](http://doc.qt.io/qt-5.5/qlocale.html) documentation for all the constructor options. More details on that `load(...)` function [here](http://doc.qt.io/qt-5.5/qtranslator.html#load-1). 

For example if you change line 42 to `if (translator.load(QLocale("de"),` and build and run the application, it will be translated in German.

If you create a new file _notepadqq_ru.ts_ and need to know where do you reference it within the code/config files, you can always search for _notepadqq_de.ts_ text in all files of the project and that will show you where to add yours.

**Comment by darealshinji** [comment]
@xDShot Creating the German localization wasn't that difficult. I've installed Qt Linguist and just got started. It's very easy to use.

**Comment by xDShot** [comment]
We've already figured out how to add translations. Thank you for explanation :)
