### ISSUE TITLE
Official version? What about the Launchpad site?

### ISSUE THREAD

**Issue by rugk** [notepadqq/notepadqq#159]
Is this an official version/repo of Notepadqq. Because on the homepage there is no link to this repo.

But what about the Launchpad site? Currently it seems you have now two repos (and issue tracker, pull requests and so on) - one here and one at Launchpad.
So are you going to move to GitHub or what is the reason behind this repo?

**Comment by flamusdiu** [comment]
@rugk It's the official repo ... not sure why he has both; but that is his choice.

**Comment by danieleds** [comment]
Sorry for the late reply, these days I'm really busy!
Everything has moved to GitHub: launchpad is still active just for the PPA.

I thought I had disabled the issue tracker on launchpad... It should be read-only. The other things too.

**Comment by rugk** [comment]
Okay, nice to hear.
However I think you should promote this repo on your website more, so that everyone knows it is hear. Currently I could not find any link from your website to this repo at all.

**Comment by danieleds** [comment]
There should be a "fork me on GitHub" banner in the top left corner of the website, however I will make it clearer in other places too.
Thank you!
