### ISSUE TITLE
Arch Linux moves to new ABI

### ISSUE THREAD

**Issue by flamusdiu** [notepadqq/notepadqq#160]
For Arch: 

This needs to be rebuilt for the new ABI as per
https://lists.archlinux.org/pipermail/arch-dev-public/2015-December/027597.html

The git package is fine but the binaries need to be rebuilt to support the new ABI. Unless it already is..

**Comment by darealshinji** [comment]
I think the bin packages are based on the Launchpad builds. GCC 5 is used on Ubuntu 15.10 and newer. So using the binaries from these versions might work.

**Comment by flamusdiu** [comment]
Okay. I'll have to look at it tonight.

**Comment by danieleds** [comment]
News on this?

**Comment by flamusdiu** [comment]
Oops ... let me double check. I think it was fine. I forgot at the moment. #starwars things :P

**Comment by Teklad** [comment]
This works fine as intended I think.  I used to maintain the notepadqq Arch Linux package many moons ago.  This can be closed. :)
