### ISSUE TITLE
The dropdowns in the Search dialog do not honor exact casing

### ISSUE THREAD

**Issue by dagostinelli** [notepadqq/notepadqq#161]
Consider the following use case:
- Open Search Box
- Choose Replace
- Type in hello in Find box
- Type in pickles in Replace with box
- Check Show Advanced Options 
- Choose Search plain Text and Choose Match Case
- Replace All
- Close Dialog
- Open Search Box
- Choose Replace
- Type in HELLO in Find box

problem, it changes HELLO to hello

- Type in PICKLES into Replace with box

problem, it changes PICKLES to pickles>

Cannot move on from here...

The drop down boxes function as a most-recently-used list.  But the rules controlling it are not permitting case variations.

**Comment by danieleds** [comment]
Thank you for reporting!
