### ISSUE TITLE
makefile ignore DESTDIR

### ISSUE THREAD

**Issue by schmidicom** [notepadqq/notepadqq#163]
The makefile ignores the DESTDIR Variable which prevents the installation with Portage.
Forumthread @ Gentoo: https://forums.gentoo.org/viewtopic-t-1035726.html
Buildlog: https://drive.google.com/file/d/0B3pmY9R_R3jqcWlEeEFpTTZLY2c/view?usp=sharing

**Comment by Scimmia22** [comment]
DESTDIR is an autotools thing. qmake uses INSTALL_ROOT.

**Comment by darealshinji** [comment]
Maybe DESTDIR could be used if INSTALL_ROOT wasn't set.
Kinda like this:
``` sh
if [ "x$DESTDIR" != "x" ] && [ "x$INSTALL_ROOT" = "x" ]; then
  INSTALL_ROOT="$DESTDIR"
fi
```

**Comment by Scimmia22** [comment]
Or you could just use INSTALL_ROOT and move on.

**Comment by schmidicom** [comment]
With INSTALL_ROOT in the "src_install()" Section can Portage install the Software.
```
src_install() { 
        INSTALL_ROOT="$D" make install || die 
}
```
Thank you.
