### ISSUE TITLE
How to turn off auto indent in notepadqq?

### ISSUE THREAD

**Issue by EastAPOLO** [notepadqq/notepadqq#170]
Whenever I go to a new line it automatically indents for me and I was wondering if there is any way to turn this off, because I can't find it anywhere in the settings.

Thank you,

- EastAPOLO

**Comment by danieleds** [comment]
No, right now there is not any setting for this.

**Comment by xproofx** [comment]
This would be a very welcome feature.  Thanks!

**Comment by danieleds** [comment]
Fixed by @JuBan1 at 8210b15a1dd73e0c05e9e552e24fa92b3d86e6eb
