### ISSUE TITLE
How I can upgrade from Qt 5.2.1 to 5.5 under Linux Mint Xfce 17.3

### ISSUE THREAD

**Issue by BogusCurry** [notepadqq/notepadqq#182]
Hello ;D
I know maybe is not the right place here my problem, but I not found a tutorial for the upgrade Qt 5.2.1 to 5.5 under Linux Mint Xfce 17.3. So sorry for my question.
How I can do it ?

Greetings 
Bogus | Have a nice Day ;D

**Comment by darealshinji** [comment]
It's recommended to use the Qt online installer and install the files into `$HOME/Qt`: https://github.com/notepadqq/notepadqq#qt

**Comment by BogusCurry** [comment]
thanks ;D
