### ISSUE TITLE
notepaddq installation succeeds, but it fails to start

### ISSUE THREAD

**Issue by rohshall** [notepadqq/notepadqq#189]
`
 ~/notepadqq (git)-[master]- % notepadqq
/usr/local/bin/../lib/notepadqq/notepadqq-bin: /opt/Qt/5.5/gcc_64/lib/libQt5PrintSupport.so.5: no version information available (required by /usr/local/bin/../lib/notepadqq/notepadqq-bin)
/usr/local/bin/../lib/notepadqq/notepadqq-bin: /opt/Qt/5.5/gcc_64/lib/libQt5Network.so.5: no version information available (required by /usr/local/bin/../lib/notepadqq/notepadqq-bin)
/usr/local/bin/../lib/notepadqq/notepadqq-bin: /opt/Qt/5.5/gcc_64/lib/libQt5WebKitWidgets.so.5: no version information available (required by /usr/local/bin/../lib/notepadqq/notepadqq-bin)
/usr/local/bin/../lib/notepadqq/notepadqq-bin: /opt/Qt/5.5/gcc_64/lib/libQt5Gui.so.5: no version information available (required by /usr/local/bin/../lib/notepadqq/notepadqq-bin)
/usr/local/bin/../lib/notepadqq/notepadqq-bin: /opt/Qt/5.5/gcc_64/lib/libQt5Core.so.5: no version information available (required by /usr/local/bin/../lib/notepadqq/notepadqq-bin)
/usr/local/bin/../lib/notepadqq/notepadqq-bin: /opt/Qt/5.5/gcc_64/lib/libQt5Core.so.5: no version information available (required by /usr/local/bin/../lib/notepadqq/notepadqq-bin)
/usr/local/bin/../lib/notepadqq/notepadqq-bin: /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5: no version information available (required by /usr/local/bin/../lib/notepadqq/notepadqq-bin)
/usr/local/bin/../lib/notepadqq/notepadqq-bin: relocation error: /usr/local/bin/../lib/notepadqq/notepadqq-bin: symbol qt_version_tag, version Qt_5.6 not defined in file libQt5Core.so.5 with link time reference

 ~/notepadqq (git)-[master]- % qtchooser --print-env
QT_SELECT="default"
QTTOOLDIR="/usr/lib64/qt5/bin"
QTLIBDIR="/usr/lib64/qt5"

 ~/notepadqq (git)-[master]- % uname -a
Linux acer 4.5.0-0.rc7.git0.2.fc24.x86_64 #1 SMP Tue Mar 8 02:20:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 ~/notepadqq (git)-[master]- % cat /etc/fedora-release 
Fedora release 24 (Twenty Four)

`

**Comment by darealshinji** [comment]
Does it start if you run `/usr/local/lib/notepadqq/notepadqq-bin` directly?

**Comment by rohshall** [comment]
Yes, it does start if I run /usr/local/lib/notepadqq/notepadqq-bin directly

**Comment by rohshall** [comment]
I fixed the script (/usr/local/bin/notepadqq) manually. I had two installations of Qt5 on my machine and the script took the one qtchooser does now show (qtchooser --print-env). Anyway, when I configured the LD_LIBRARY_PATH in the script according to my qt installation, it worked. Thanks :)
