### ISSUE TITLE
Allow to change font

### ISSUE THREAD

**Issue by M0xkLurk3r** [notepadqq/notepadqq#192]
I need a separate font when writes code, but the notepadqq seems insist on the system default monospace font (i did not like the default font for sure, but any changes on the desktop settings may take effect on all desktop apps and make their UI messes). The same place to configure the style (Settings -> Style Configuator) in notepad++ was nothing in notepadqq, maybe you did not achieve this feature =_=
Hope you to bring this feature out in next version o(*￣▽￣*)o

**Comment by danieleds** [comment]
Duplicate: #152
