### ISSUE TITLE
Can't compile on Fedora 23

### ISSUE THREAD

**Issue by devhen** [notepadqq/notepadqq#198]
Trying to compile the github sources on F23 I eventually get this error:

`g++ -Wl,-O1 -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-rpath-link,/usr/lib64 -o ../../out/release/lib/notepadqq-bin ../../out/build_data/main.o ../../out/build_data/mainwindow.o ../../out/build_data/topeditorcontainer.o ../../out/build_data/editortabwidget.o ../../out/build_data/docengine.o ../../out/build_data/frmabout.o ../../out/build_data/notepadqq.o ../../out/build_data/frmpreferences.o ../../out/build_data/iconprovider.o ../../out/build_data/editor.o ../../out/build_data/bannerfilechanged.o ../../out/build_data/bannerbasicmessage.o ../../out/build_data/bannerfileremoved.o ../../out/build_data/customqwebview.o ../../out/build_data/clickablelabel.o ../../out/build_data/frmencodingchooser.o ../../out/build_data/bannerindentationdetected.o ../../out/build_data/frmindentationmode.o ../../out/build_data/singleapplication.o ../../out/build_data/localcommunication.o ../../out/build_data/filesearchresultswidget.o ../../out/build_data/frmsearchreplace.o ../../out/build_data/searchinfilesworker.o ../../out/build_data/replaceinfilesworker.o ../../out/build_data/dlgsearching.o ../../out/build_data/searchresultsitemdelegate.o ../../out/build_data/extension.o ../../out/build_data/frmlinenumberchooser.o ../../out/build_data/extensionsserver.o ../../out/build_data/stub.o ../../out/build_data/runtimesupport.o ../../out/build_data/windowstub.o ../../out/build_data/notepadqqstub.o ../../out/build_data/editorstub.o ../../out/build_data/extensionsloader.o ../../out/build_data/globals.o ../../out/build_data/menuitemstub.o ../../out/build_data/installextension.o ../../out/build_data/qrc_resources.o ../../out/build_data/moc_mainwindow.o ../../out/build_data/moc_topeditorcontainer.o ../../out/build_data/moc_editortabwidget.o ../../out/build_data/moc_docengine.o ../../out/build_data/moc_frmabout.o ../../out/build_data/moc_notepadqq.o ../../out/build_data/moc_frmpreferences.o ../../out/build_data/moc_editor.o ../../out/build_data/moc_bannerfilechanged.o ../../out/build_data/moc_bannerbasicmessage.o ../../out/build_data/moc_bannerfileremoved.o ../../out/build_data/moc_customqwebview.o ../../out/build_data/moc_clickablelabel.o ../../out/build_data/moc_frmencodingchooser.o ../../out/build_data/moc_bannerindentationdetected.o ../../out/build_data/moc_frmindentationmode.o ../../out/build_data/moc_singleapplication.o ../../out/build_data/moc_filesearchresultswidget.o ../../out/build_data/moc_frmsearchreplace.o ../../out/build_data/moc_searchinfilesworker.o ../../out/build_data/moc_replaceinfilesworker.o ../../out/build_data/moc_dlgsearching.o ../../out/build_data/moc_extension.o ../../out/build_data/moc_frmlinenumberchooser.o ../../out/build_data/moc_extensionsserver.o ../../out/build_data/moc_stub.o ../../out/build_data/moc_runtimesupport.o ../../out/build_data/moc_windowstub.o ../../out/build_data/moc_notepadqqstub.o ../../out/build_data/moc_extensionsloader.o ../../out/build_data/moc_menuitemstub.o ../../out/build_data/moc_installextension.o   -lQt5Svg -lQt5WebKitWidgets -lQt5PrintSupport -lQt5Widgets -lQt5WebKit -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/5.3.1/../../../libGL.so when searching for -lGL
/usr/bin/ld: skipping incompatible /lib/libGL.so when searching for -lGL
/usr/bin/ld: skipping incompatible /usr/lib/libGL.so when searching for -lGL
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:369: recipe for target '../../out/release/lib/notepadqq-bin' failed
make[1]: *** [../../out/release/lib/notepadqq-bin] Error 1
make[1]: Leaving directory '/home/devhen/src/notepadqq/src/ui'
Makefile:42: recipe for target 'sub-src-ui-make_first' failed
make: *** [sub-src-ui-make_first] Error 2`

I'm thinking maybe this has something to do with the fact that I'm using the proprietary nvidia drivers from geforce.com?

Any ideas? I'd love to give notepadqq a try.

Thanks

**Comment by darealshinji** [comment]
Maybe it works if you replace `-lGL` with `/usr/lib64/mesa/libGL.so` or wherever the original MESA GL library is placed.

**Comment by devhen** [comment]
Thanks! So it turns out my /usr/lib64/libGL.so link was just broken, probably from the nvidia install. I had to link it to the nv version:

`sudo ln -sf /usr/lib64/libGL.so.361.28 /usr/lib64/libGL.so`

notepadqq compiled and works great now.

Cheers
