### ISSUE TITLE
Zenburn theme doesn't properly style new tabs

### ISSUE THREAD

**Issue by Vhin** [notepadqq/notepadqq#199]
Changing the theme to zenburn will correctly update all existing tabs, but new ones aren't styled correctly. They have a white background, with black text and the current line is highlighted in black, exactly the same color as the text, making it essentially unusable.

If you go back into the settings, the theme switcher still says zenburn, but if you just hit okay (without changing anything) it will fix the problem, at least until more tabs are opened.

**Comment by danieleds** [comment]
Thank you for the bug report. Does this happen only with the Zenburn theme?

**Comment by Vhin** [comment]
As far as I can tell. I tried about a half-dozen other styles, and none of them had this problem, only Zenburn.

**Comment by Algomorph** [comment]
+1 for this problem.
