### ISSUE TITLE
Notepadqq is not using Monospace font

### ISSUE THREAD

**Issue by ram-on** [notepadqq/notepadqq#201]
The file `/usr/share/notepadqq/editor/libs/codemirror/lib/codemirror.css` indicates that notepadqq should be using Monospace font:
```
/* BASICS */

.CodeMirror {
  /* Set height, width, borders, and global font properties here */
  font-family: monospace;
  height: 300px;
  color: black;
}
```

However, the font used is neither Monospace nor fixed-width.  Pls refer to the screenshot below:

[<img src="http://i.imgur.com/wehglCb.png">](http://i.imgur.com/wehglCb.png)

Notepadqq version:  v0.51.0

**Comment by danieleds** [comment]
Does it work if you put there the name of a monospace font in your system?

**Comment by ram-on** [comment]
@danieleds I changed the font from 'monospace' to 'Liberation Mono'.  It worked, however the font was way too large.

Therefore, I had to add and manually set `font-size` as demonstrated below:

```
/* BASICS */

.CodeMirror {
  /* Set height, width, borders, and global font properties here */
  font-family: Liberation Mono;
  font-size:   13px;
  height: 300px;
  color: black;
}
```

I've used notepadqq for months now and never had this issue.  Hence, I'm presuming this is a bug?

**Comment by darealshinji** [comment]
It might be useful if there was an option in the settings to customize the font.

**Comment by danieleds** [comment]
Blocked by #96

**Comment by alik-co** [comment]
Adding quotes around font family name fixed the problem
(OS Mint 17.3; notepadqq v0.51.0; Qt 5.6.0)
.CodeMirror {
  font-family: "monospace";
  ...
}

**Comment by danieleds** [comment]
Interesting! Can someone else confirm?
In the meantime, I'm adding the quotes to the master branch.
Thank you.

**Comment by danieleds** [comment]
I'm not able to reproduce the issue, so I'm leaving this open until someone confirm that the last commit fixed the problem.

**Comment by xDShot** [comment]
Looks like it uses Monospace again. At least it's much better than before.
![_2016-04-13_23-28-20](https://cloud.githubusercontent.com/assets/4261659/14508274/60cc11c2-01cf-11e6-80aa-b540fda58e63.png)

**Comment by danieleds** [comment]
Great! Nice find, @alik-co.
The next priority, after the switch to QtWebEngine, will be the ability to control font settings.

**Comment by alik-co** [comment]
@danieleds: Thanks! Font settings exposed to the UI is one useful feature, indeed.

**Comment by tuxedo-ath** [comment]
Same issue here. Adding quotes to the css fixed it, but had to set the font size too, like ram-on wrote already.
