### ISSUE TITLE
Indentation message crash

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#203]
Starting NQQ for the first timer after a boot often takes a few seconds. When I double-click a file to open two times or more often, and the file's indentation doesn't match up, the indentation message will appear more than once (see screenshot). Clicking either "Use spaces" or "Ignore" then will make the app hang-up.
![indent-crash](https://cloud.githubusercontent.com/assets/5700937/14316661/9578b388-fc04-11e5-8ac7-4f0433be2fcc.png)
##

**Comment by danieleds** [comment]
Okay, I've been able to reproduce it.
Thanks for the report!

**Comment by danieleds** [comment]
Easily reproducible with this shell command:

    (notepadqq <filename> &); (notepadqq <filename> &)

Where `<filename>` is the path of a file which triggers the banner.

If it doesn't work on the first run, close notepadqq and try it again a few times

**Comment by danieleds** [comment]
Apparently the bug has been inadvertitely fixed
