### ISSUE TITLE
notepadqq not showing in open with menu

### ISSUE THREAD

**Issue by pradel1992** [notepadqq/notepadqq#218]
Since I updated ubuntu to 16.04 (clean install), notepadqq is not showing in the 'Open with' applications.
I also tried to add %F to the notepadqq.desktop file, nothing changes

**Comment by danieleds** [comment]
I upgraded to Ubuntu 16.04 on Sunday with a clean install too, but I correctly have the option in the 'Open with' menu.

I know it sound stupid, but can you try to reinstall notepadqq / reboot?
Also, do you see it in the Dash?

**Comment by pradel1992** [comment]
already tried both, in the dash i see it (with the name "new 1 - Notepadqq").

**Comment by danieleds** [comment]
That is strange too: the name should be just "Notepadqq".
I have observed strange behaviors with other applications too here on Xenial, so I suspect (and I'm pretty sure) it might be a problem with Unity.

I'll leave this open until we can find a workaround, an explanation, or a solution. Thanks for the report.

**Comment by pradel1992** [comment]
Hi, today I renamed the notepadqq.desktop file into Notepadqq.desktop.
Now it is shown correctly both in dash and open with menu.

**Comment by danieleds** [comment]
Nice to hear!
Just for reference: my "notepadqq.desktop" is lowercase.

**Comment by danieleds** [comment]
I suspect that renaming that file triggered a refresh: if I'm right, things should be ok if you rename it back to lowercase.

**Comment by pradel1992** [comment]
Yes, I was just going to write that. Odd stuff happening in 16.04 :)
