### ISSUE TITLE
How to build using Ubuntu SDK?

### ISSUE THREAD

**Issue by mevsme** [notepadqq/notepadqq#219]
I'm in China, so I can not enter G+ group. I have Ubuntu SDK and Qt, but it's not in /opt and /home/{usrname}.

How to build? I am very newbie, but I'd like to study desktop development at the example of Nqq.

**Comment by jack980517** [comment]
Ubuntu SDK should not be needed. Just install the development packages specified in "build dependencies" in README.md and follow the instructions,
