### ISSUE TITLE
Previously unsaved files are not recovering on restart

### ISSUE THREAD

**Issue by lokesh1729** [notepadqq/notepadqq#220]
Hi guys,

I have observed in notepad++ that if there is an unsaved file, if i attempt restart and open notepad++ previous files are same as it is. But in notepadqq it's not like that. I am not able to get those.

**Comment by guekho64** [comment]
That would be a great idea for some people who forget to save their files.

+1

PD: What about "Autosave"? Could it be possible someday, alongside recoverable "unsaved files"?

**Comment by danieleds** [comment]
I agree that it would be great to have both (unsaved file recovery and autosave).
The first one is a special case of Sessions.

They surely need to be implemented.

**Comment by Teklad** [comment]
Implemented completely in PR #249

**Comment by cpagravel** [comment]
Is this feature working? I just lost some important info because it crashed and looks to not have recovered the files.

**Comment by JuBan1** [comment]
No, recovery from crashes isn't working yet. 

This requires autosaving to work. I've written the code for it but the underlying editor doesn't expose a feature I need to make it work nicely so I shelved it for the time being.

Sorry that you've lost data. Keeping users' files save should be all the way up the priority list. Hopefully it won't be much longer until this works.

**Comment by Sariyn** [comment]
Hello, is this still a bug in the latest version?  Just lost some important work.  Nice heads up btw.

**Comment by JuBan1** [comment]
What exactly happened? Nqq doesn't do anything to protect your unsaved documents in case of crashes. 

If you restart your computer Nqq should be closed properly and save your documents.

**Comment by Sariyn** [comment]
Hi, yes it is how you said-- system crashed that resulted in loss of unsaved notepadqq work.
To be fair however, it is probably easy to be mistaken for relying on this feature as it not atypical in other editors, and even the Windows notepad++ counterpart supports some level of disaster recovery on crash with unsaved work.  It feels like too an important feature to be missing.  Other than that, great app.

**Comment by JuBan1** [comment]
@mrandreastoth I'm afraid you've got the wrong project :) This is Notepad**qq**, a Linux and macOS alternative to Notepad++. If you want to report an issue with N++ you can probably do that [there](https://github.com/notepad-plus-plus/notepad-plus-plus/issues)

**Comment by mrandreastoth** [comment]
Lol! How embarrassing. But thank you for the link. :)

**Comment by TimHandy** [comment]
This just happened to me. PopOS didn't suspend properly and crashed. On restarting I lost all my text in an unsaved file in Notepadqq. :-(

**Comment by squatmaestro** [comment]
It's happened to me several times that Notepadqq loses my unsaved data, even when closing the window via the X button then shutting down the computer (using Ubuntu 20.04). I never had this issue with Notepad++ on Windows. Losing unsaved data is too dangerous so I'll have to use another software until this is fixed.
