### ISSUE TITLE
Search and replace: special character are used as literal in replace

### ISSUE THREAD

**Issue by rlaloux** [notepadqq/notepadqq#223]
In the search and replace (any mode), if I try to replace the matched text with a special character (\r, \n, \t, ... basically every character that need escaping) the replaced value will be replaced by literals ("\t" and not a tabulation for instance).

This issue might be associated with #191.
##

**Comment by Algomorph** [comment]
Bump.
I don't think it's associated with #191. This is a matter of converting the replace string to a special character, which #191 doesn't mess with at all (the group reuse regex is /\\([1-9])/g, which requires a number). The current behavior replicates Notepad++ behavior for Normal mode, but in Extended and Regular Expression modes, the literals in the replace string should be substituted with the actual special characters.

**Comment by danieleds** [comment]
Yep, not related. It's just a matter of unescaping the replace string before sending it to the editor.

**Comment by Teklad** [comment]
If we moved SearchInFilesWorker::unescapeString to a better location and made it static I think this could be fixed in just a few minutes... the question is... where should it be moved too? 

Its a general purpose function so it doesn't make sense for it to stay in SearchInFilesWorker.
