### ISSUE TITLE
Double-click highlights entire line

### ISSUE THREAD

**Issue by Vhin** [notepadqq/notepadqq#226]
This is a feature request.

Imagine you have a file consisting of one line:

Hello world.

And, you double click on "Hello".

Expected behavior: The "Hello" gets highlighted.
Actual behavior: The entire line "Hello world." gets highlighted.

Because single word highlighting is found essentially everywhere, from other text editors to browsers, the current behavior is very hard to get used to.

**Comment by guekho64** [comment]
This is a wierd bug that happens when you use an old QT version. Try updating Qt using the Online Installer provided by the official web page.

In fact, Notepadqq respects that universal haviour of Double-Clicking  = Select Single Word

**Comment by Vhin** [comment]
I'm pretty sure I already have it set up to use the newest QT version, but I'll check when I get the chance (currently away from my laptop). If not, I'll try the newest version, and if that works, this can be closed.

Thank you.

**Comment by danieleds** [comment]
Yep, see #222

**Comment by Vhin** [comment]
Okay, so apparently I had a newer version installed, but it wasn't actually set up to use that. I got that sorted out, and, yeah, it fixes the issue.

Sorry. I didn't think about checking closed issues.

**Comment by danieleds** [comment]
No problem! Thanks for reporting.
Closing.
