### ISSUE TITLE
Compiled notepadqq for fedora 22

### ISSUE THREAD

**Issue by ptoki** [notepadqq/notepadqq#228]
Hello.
I was curious how this editor works so I compiled it for fedora.

I have two questions:
How can I make a package from it to provide it to you for other fedora users?

Is there a way to compile it statically and provide the executable with path to its files? I would like to have it compiled statically like portable app. And be able to run it with the config files directory parameter.

PS.
Very nice editor :)
If it gets a couple of features which notepad++ has it will be KILLER NOTEPAD :)

-- 
Lukasz

**Comment by danieleds** [comment]
Hi, sorry for the delay.

For the Fedora package, take a look here: https://github.com/notepadqq/notepadqq-packaging/tree/master/Fedora. It's old but might be a starting point. You can send a pull request to that repository if you want to maintain the package.

I don't think you can build it statically without going into a lot of physical pain for endless days. But if you do it, let me know.
