### ISSUE TITLE
C-Like: comments in pre-processer lines not working

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#229]
In nqq comments in pre-processer lines aren't working, but in latest CodeMirror they do. Maybe nqq's copy of CodeMirror needs an update?

![shot](https://cloud.githubusercontent.com/assets/5700937/17404713/039e7968-5a5d-11e6-8b6f-bafc0e9c6ad9.png)

**Comment by Teklad** [comment]
You would be correct in that assumption.  I'll go ahead and try to merge the latest upstream changes shortly to see if we can't get that feature integrated. :)

**Comment by danieleds** [comment]
Yes, definitely correct.

**Comment by Teklad** [comment]
The recent CodeMirror update resolves this issue.  It can be closed now. :+1:

**Comment by danieleds** [comment]
Thanks, I forgot about it :)
