### ISSUE TITLE
Fast handling of files with long lines

### ISSUE THREAD

**Issue by ericjs** [notepadqq/notepadqq#231]
This is a going to be a strange "issue type"...sort of a "feature request", but really a "please make sure this remains a feature request" :^)  Basically what I'm going to describe is something that works remarkably well in notepadqq, and could said to already be a "feature", but I don't know whether it was by intentional design or just happy circumstance. So what I'm requesting is really that it be intentionally kept as a feature.

That feature is, that it is able to handle files with very long lines, with word wrap turned on, without becoming unusable. Other editors I've tried on linux, (mainly I've tried QT-based ones, including Kate and Juffed) slow to a crawl if you load a file with extremely long lines with word wrap turned on...they become unusable, to the point of one either needing to wait many minutes to be able to even just close the file and be able to use the editor again or kill the process. Notepadqq has no such problem. (I run into such files routinely in the form large XML documents which have been generated or processed by systems that do not care about formatting.)

**Comment by danieleds** [comment]
Thanks for the "report"!

The goal for Notepadqq is to be a swiss army knife for us developers. And a swiss army knife, while it packs a lot of features, must be simple, light and _agile_.

So no, we're not going to slow it down. No matter what :-)
