### ISSUE TITLE
With Word Wrap enabled, the first space keypress in a sequence is not displayed

### ISSUE THREAD

**Issue by SarenT** [notepadqq/notepadqq#237]
Hi,

I have realized this behaviour recently while working on a python script. When I hit space once, a wide space is inserted. If I immediately hit backspace, entire space is deleted. This is confusing, because it looks like, as if I hit space twice. But it is deleted as a single character with single backspace.
So the funny thing is, when I ignore it and continue on writing, it actually becomes a double space. Meaning, I can go back to that position and delete one of the 2 space characters, which I could not before. This is a bit annoying and frustrating.
I am using Ubuntu 14.04 LTS, Qt 5.2.1, Notepadqq v0.52.1

Is it maybe the Qt version, which is outdated? Ubuntu is a bit slow with package versions...

Best,
Saren

**Comment by Teklad** [comment]
This is the first time I've heard of this behavior.  Are you using the 
latest notepadqq from github or the release version?

If you're using the release version I recommend compiling the latest 
development version to see if it fixes this behavior so we can narrow 
the issue down.  Possibly an upstream issue with CodeMirror perhaps.

**Comment by SarenT** [comment]
Thanks! I will try it with the recent version, when I have time and write here!

**Comment by danieleds** [comment]
It could be a regression with the latest CodeMirror.

Can you provide an example file and step-by-step instructions on how to reproduce? Also, your settings about tabs/spaces.

**Comment by SarenT** [comment]
I see now, what actually the problem was. At the end of the line if I insert a space character, the cursor does not move. Then I hit again thinking that I did not press properly. Then with the next character, space becomes double. Sorry for the wrong report. I will try with the latest release too, to just see if the behavior is different.

**Comment by SarenT** [comment]
I see now, what actually the problem was. At the end of the line if I insert a space character, the cursor does not move. Then I hit again thinking that I did not press properly. Then with the next character, space becomes double. Sorry for the wrong report. I will try with the latest release too, to just see if the behavior is different.

**Comment by danieleds** [comment]
Don't worry, I can reproduce it. It only happens with word wrap enabled, right?

**Comment by SarenT** [comment]
Yes it only happens with word wrap.

**Comment by danieleds** [comment]
Possible reference: https://github.com/codemirror/CodeMirror/issues/4161

**Comment by danieleds** [comment]
I checked Notepadqq v0.51.0 and it worked back then. It must a problem with CodeMirror. Tracking the issue will not be easy because I wasn't able to reproduce it on the online CodeMirror demo, and between v0.51.0 and v0.52.1 there are something like 16 different CodeMirror versions.

I suspect it has to do with the fact that QWebKit uses an old WebKit version, and CodeMirror has started to use some unsupported features.

This should be considered an high-priority issue.

**Comment by danieleds** [comment]
Okay, CodeMirror 5.17.0 introduced the problem. CM 5.16.0 works fine.

**Comment by Teklad** [comment]
Once the issue is pinpointed we should probably maintain our own patch for
future codemirror updates just to be on the safe side.

QT isn't too quick about updating its webkit engine.  QWebEngine I believe
is based on Blink(chromium). Are we currently using that?

If not it'd be worth a shot to see if it resolves the issue without having
to beat CodeMirror into shape.

**Comment by Teklad** [comment]
Missed your last reply, sorry. You can disregard that. :p

**Comment by danieleds** [comment]
This is the commit that introduced the issue: https://github.com/codemirror/CodeMirror/commit/e60f4b7dd88b71e227f79200932c028ca047d78e

It should be simple to fix, and I *might* get some help from the project manager if needed.

And no, we're not using QWebEngine and this is a major issue too. Doing the switch is not easy, and I'm not sure how many distributions will ship QWebEngine so we're going to think about it a lot.

And if this wasn't enough, they just decided to deprecate QWebKit :)

**Comment by danieleds** [comment]
PR here: https://github.com/codemirror/CodeMirror/pull/4197

**Comment by Teklad** [comment]
Well one sure-fire way to implement it would be to allow the option to use either/or until QWebKit his deprecated completely.  That would allow the freedom to work on the new implementation while still keeping the old intact for the moment until we're sure it won't break everything.

**Comment by danieleds** [comment]
The upstream maintainer has not replied to my pull request yet, so I'm patching this in our own fork.

https://github.com/notepadqq/CodeMirror/commit/d790fc39c1a5f06aa66415110b8ebe3026df665a
