### ISSUE TITLE
Ability to customize toolbar buttons.

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#238]
This is more or less just going to be a placeholder for a feature that needs implementation.  Currently Notepadqq's toolbar is hard-coded, so the icons/actions aren't able to be moved around or changed in any way.

Being able to customize the toolbar to one's liking gives more power to the user allowing them to have what they need without all the extras.

This would resolve #120 as well as any future requests regarding the toolbar that might arise.
##

**Comment by Cybermaxrus** [comment]
Can we hope that this feature will be implemented in the future? If a few people ask about it, then it's really useful.

**Comment by JuBan1** [comment]
I'm taking a look at it now. Shouldn't be that hard; it just fell through the cracks. Little dev time, lots of requests :)
