### ISSUE TITLE
Program crash when trying to close a tab.

### ISSUE THREAD

**Issue by JuBan1** [notepadqq/notepadqq#240]
Steps to reproduce:

* Open a fresh window.
* Open a second tab.
* Right click on second tab and select "Move to Other View"
* Middle click(!) on the tab you just moved to close it.
* Segmentation Fault

Using the 'x' button to close the tab works normally. Doesn't occur every time, but most of the time. Just repeat steps 3+4 if it doesn't work immediately.

PS: I have a fix for that lined up, but I'm fighting more with git than with the code. It'll come eventually.
PPS: Fix is here.

**Comment by danieleds** [comment]
Confirmed.
