### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by JuBan1** [notepadqq/notepadqq#247]
I hope this is a fine way of asking a few questions about the code.

While working on a feature I came across a few bits of code that were a bit odd to me:

* TopEditorContainer and TabWidgets: As far as I see we only ever use at most two TabWidgets (=views), never more. Some of the code would allow for more TabWidgets, but other pieces assume that there are at most two (e.g. "Move to Other View" makes little sense with more than two). My question: would it be alright to refactor the code to only ever allow at most two TabWidgets in a TopEditorContainer? It'd reduce code complexity.

* Editors and the editor buffer. Right now there's a `QQueue<Editor*>` inside editor.cpp to buffer unused Editors. However, the buffer isn't ever really used much. I don't think it would ever do much good all-in-all. I did some benchmarking and you can get the same performance without the queue. Again, it would reduce complexity, but I don't think there would be any losses.

Both changes are aimed at making the code easier to read and to handle. Whaddaya think?

**Comment by danieleds** [comment]
> I hope this is a fine way of asking a few questions about the code.

Sure it's fine!

> would it be alright to refactor the code to only ever allow at most two TabWidgets in a TopEditorContainer? It'd reduce code complexity.

I prefer it to stay generic. "Move to Other View" is just a special case because, for now, we only support two views. Nothing prevent us from supporting three vertical views at the same time.

> I did some benchmarking and you can get the same performance without the queue.

The buffer was introduced to avoid showing to the user a blank page for the small time needed to render a full HTML page. This is especially evident on slow systems, so we always keep a pre-rendered editor ready to be shown when needed.

**Comment by JuBan1** [comment]
> Nothing prevent us from supporting three vertical views at the same time.

Alright.

> The buffer was introduced to avoid showing to the user a blank page for the small time needed to render a full HTML page. This is especially evident on slow systems, so we always keep a pre-rendered editor ready to be shown when needed.

It's not necessary to have a queue though. I used a single Editor as a buffer which works just as well. I timed the results and they're practically the same on my terrible Intel Celeron. The change would pretty much be from this

```
static QQueue<Editor*> m_editorBuffer;
Editor *Editor::getNewEditorUnmanagedPtr(QWidget *parent)
    {
        Editor *out;

        if (m_editorBuffer.length() == 0) {
            m_editorBuffer.enqueue(new Editor());
            out = new Editor();
        } else if (m_editorBuffer.length() == 1) {
            m_editorBuffer.enqueue(new Editor()); //<- this is the code path that runs virtually every time
            out = m_editorBuffer.dequeue();
        } else {
            out = m_editorBuffer.dequeue(); //<- there's never more than 1 buffer in the queue at the moment. So this never runs.
        }

        out->setParent(parent);
        return out;
    }
```
to this:

```
static Editor* m_bufferEditor;
Editor *Editor::getNewEditorUnmanagedPtr(QWidget *parent)
    {
        Editor *out = m_bufferEditor;
        m_bufferEditor = new Editor();
      
        out->setParent(parent);
        return out;
    }
```
In both cases the same work is being done - one editor is created, another one returned. They're equally fast.

Basically you'd do away with the queue as well as the `addEditorToBuffer` stuff.

**Comment by danieleds** [comment]
Oh ok, I though that you wanted to remove the buffer altogether, but you were referring just to the queue.

Yep, the queue is not used at all. But let's keep that how it is right now. It isn't broken, it allows to pre-render an arbitrary number of editors in case we need to display more than one at the same time (see your first point), and it works :)

**Comment by JuBan1** [comment]
True, it's not broken :)

**Comment by JuBan1** [comment]
Two more questions, so I reopened this.

First, I was looking into implementing a document map [such as this](https://images.duckduckgo.com/iu/?u=http%3A%2F%2F3.bp.blogspot.com%2F-TAGE9DKqFAA%2FUFuZznWddBI%2FAAAAAAAAOxc%2Ff_y6w6rgiRg%2Fs1600%2Fnotepaddocumentmap.png&f=1). But actually getting a "screenshot" of the whole text file is a bit of a problem.

Right now I found a way to do that: get the Editor's QWebView and render it into a QImage. There are a bunch of issues which do not make this simple, though. I don't know if there's a better way. Maybe CodeMirror can help with that natively?

Second, is about our use of QSettings. By now we're storing quite a bit of stuff in QSettings and the bits of code are all over the place. It's relatively inconvenient to change the string or the default value of a setting because they're usually found in several places. I thought it might be useful to refactor all of that stuff so we've got it in one place.

Here's some incomplete code to give an idea what I mean.

```
//List of all settings
enum NqqValueKey{
	SEACH_HISTORY,
	SEARCH_REPLACE_HISTORY,
	WORD_WRAP,
	...
};

//Store all information about settings in one place.
//Changing/Retrieving a setting's default value or changing its key is simple since this is 
//the only place it's kept.
struct[] allSettings = {
	//Enum					Save string					default value
	SEARCH_HISTORY, 		"Search/searchHistory", 	QString()
	SEARCH_REPLACE_HISTORY, "Search/replaceHistory", 	QString(),
	WORD_WRAP, 				"wordWrap", 				false,
	....
};

//New settings class, just to wrap some of the logic that is currently spinkled throughout the code.
class NqqSettings {

	QVariant value(NqqValueKey key) {
		return m_settings.value(allSettings[key].saveString, allSettings[key].defaultValue);
	}
	void setValue(NqqValueKey key, QVariant value){
		m_settings.setValue(allSettings[key].saveString, value);
	}
	void resetAllSettings(){
		for(auto&& item : allSettings){
			m_settings.setValue(item.saveString, item.defaultValue);
		}
	}
	
	//A few kinds of settings might need special treatment
	void setLanguageValue(QString whichLanguage, QVariant value){
		m_settings("Languages/" + whichLanguage, value);
	}

private:
	QSettings m_settings;
}

//Usage is very similar to now, but with enums instead of strings as keys and
//without having to deal with defaults.

//Save some value.
m_nqqSettings->setValue(WORD_WRAP, true);

//Load some value.
m_nqqSettings->value(WORD_WRAP);

```

Wanted to ask if you consider this worth pursuing.

**Comment by danieleds** [comment]
Document map should be implemented javascript-side only as a CodeMirror plugin. See here: https://github.com/alex-seville/minimap
To be fair, I would like features like this to be implemented as plugins (will be possible only after I will finalize the API in some future). I don't want to clutter the core with too many big features.

I like the refactoring for the settings. When you'll create a pull request we'll discuss the details.
