### ISSUE TITLE
Opening a recent document does not check for the file's existence

### ISSUE THREAD

**Issue by JuBan1** [notepadqq/notepadqq#248]
You can open a recent file that does not exist anymore.

Steps to reproduce:
- Create any new file and open it in Notepadqq.
- Close Notepadqq and delete the file.
- Open it again and select the deleted file from the list of recent documents.
- The file is opened as if it still exists, no indication is given that it's gone.
- Even worse, when pressing 'Save' the file will be stealthily recreated on disk.
##

**Comment by danieleds** [comment]
True, we should at least give a warning.
I mean, I see nothing wrong with this behavior*, but we should inform the user that the file is actually gone, e.g. with a dialog that pops out right after he clicks on the recent filename from the list.


*it mimics the command line behavior so opening a unexisting file it's fine per se

**Comment by JuBan1** [comment]
It makes sense for command line, but opening a *recent document* when it doesn't exist could be deceiving. I think most programs remove non-existing files from the recent list. That could be an option too.

**Comment by danieleds** [comment]
Agreed

**Comment by Teklad** [comment]
Another method would be to gray it out as a visual indicator.  Its a bit
cleaner than a pop out box. Or just removing works too. I'm fine with
either.

**Comment by danieleds** [comment]
@JuBan1 @Teklad *how* and *when* would you detect that the file is not there anymore, so that it can be removed from the list? 
(I like this approach more than the dialog, btw)

**Comment by JuBan1** [comment]
When thinking about it, the only surefire way would be to check it every time the Menu is opened (And even then a file could be deleted in the time between opening the menu and clicking an entry- but that's an obscure case.) or to create file monitors for all files on the recent list in order to be notified if they are deleted. That's probably unreasonably much effort for a feature like this.

N++ actually just shows you a dialog and removes it from the recent list if No is chosen.

![](http://pix.toile-libre.org/upload/original/1472504121.png)

Maybe a compromise: 

* Check all recent files for existence on program start-up and remove nonexistent files from the list. 

* Then, when the user actually selects an entry from the recent list, do another check for existence in case the file was deleted between start-up and this point in time. If it was, show a dialog like N++ does.

**Comment by danieleds** [comment]
> When thinking about it, the only surefire way would be to check it every time the Menu is opened (And even then a file could be deleted in the time between opening the menu and clicking an entry- but that's an obscure case.) or to create file monitors for all files on the recent list in order to be notified if they are deleted. That's probably unreasonably much effort for a feature like this.

Yeah, I'd avoid the file monitors. And I'd avoid to check them when the user opens the menu.

Maybe the dialog is actually the best solution. In that case, for the sake of consistency we should *not* clear the missing files on startup.
