### ISSUE TITLE
Smart Indent

### ISSUE THREAD

**Issue by slypiggies** [notepadqq/notepadqq#253]
Hello!
Is there a way to turn off _Smart Indent_? For example, when I am editing a C++ file, I type `{` and hit `Enter`, an extra indentation will be added. Also, when I missed the `;` on the previous line and hit `Enter`, an extra indentation will be added, too. I just want to keep the indentation on the previous line (_Basic Auto Indent_). Where can I find a toggle to turn this (_Smart Indent_) off?

### Suggestion (if there isn't a way)
Add a way to allow users to turn off _Smart Indent_, but keeping _Basic Auto Indent_ at the same time.

Thanks!

**Comment by JuBan1** [comment]
Hey, 
right now there's no option for this as far as I know. It's been requested in #170 as well. It seems to be a very easy addition so I'll throw a patch together.

**Comment by slypiggies** [comment]
Thanks a lot!

**Comment by danieleds** [comment]
Fixed by @JuBan1 at 8210b15a1dd73e0c05e9e552e24fa92b3d86e6eb
