### ISSUE TITLE
Brainstorming about a Workspace feature

### ISSUE THREAD

**Issue by JuBan1** [notepadqq/notepadqq#259]
So next I wanted to tackle Workspaces.

I wanted to keep roughly to how VS Code implements it. Here's a screenshot:

![image](http://pix.toile-libre.org/upload/original/1473105788.png)

* You can add folders to your Workspace, which is a docklet like the search widget.
* You can navigate subfolders, open files, etc using the files tree.
* Right-clicking on any file/folder gives you a few options. New File, Delete, etc.
* Also, you can select a filter for any folder that is added to the Workspace if you want to only see files with certain extensions.

What would you like to see in Workspaces? Any certain actions on right-click? Anything from other editors with similar features? A different approach of it entirely?

**Comment by Teklad** [comment]
I would really like to see this implemented as an on/off plugin.  Its one of those features that are great for some but not very useful for others.  Unfortunately, outside of the extensions API we seriously lack features to build such features as plugins.

I mainly don't want to bloat the core to the point it feels like... kate?  If you do go for this, try to keep the code as separated as possible from the main bits, or write a pseudo plugin API which can load things in the right places.  

The latter would be more useful when more features like this come up.  I'm not sure how well developed our extension system is, since I wasn't around very much when it first got implemented.

@danieleds would probably have better insight for a feature like this I think.  I'm a little tied up bug hunting for the moment or I'd write a small plugin system to get us started, lol.

**Comment by JuBan1** [comment]
I share your concern and I think I can do a pretty decent job encapsulating this feature. In general I've been trying to reduce the amount of interconnectivity between systems when I was working on them. 

I could try to make an effort to create a system to incorporate "plugins" - first thing that comes to mind is practically a Plugin base-class that can be sub-classed and that interacts with other components through a set of signals. But that would be a significant rewrite of a lot of code.

**Comment by danieleds** [comment]
I agree with @Teklad, I would like something like this to come as an external implementation.

There is a preliminary support for plugins but I've not had the time to finalize the API yet, so we can only build pretty basic stuff with it. Example: https://github.com/notepadqq/example-extensions

Right now, the things we need the most are:
 * Stability and performance fixes (as in the search-in-files PR)
 * Implementing missing features (as in the sessions PR)... see the "Run" menu too

After these two points we can finally release Notepadqq v1.0.

Then, the focus will switch to
 * the plugin system and its uses (e.g. workspaces)
 * QtWebEngine.

----

Anyway, for the record, I like how VS Code implements workspaces.

**Comment by JuBan1** [comment]
Well, I can't say I'm particularly stoked about the prospect of writing this stuff in javascript.

**Comment by Teklad** [comment]
Couldn't we offer a C++ backend for plugins as well for ones that are shipped with notepadqq?  Javascript isn't very appealing for people that prefer to get their hands dirty with low end code, so extensions adhere more to the users than to back-end developers.

While I understand that this method is more prone to bugs, the extra processing power can be useful for plugins that do a lot of data crunching, but don't necessarily qualify as a directly implemented feature.  Plus we can disable plugins that lack polish upon release if necessary.

A good idea to compliment this would be to offer up a repository which has extensions users have submitted. That would allow users to share their own creations with everyone else for functionality that doesn't qualify as either a directly implemented feature or a C++ plugin.

Mainly it would allow for more flexibility inside the extensions for things that require it.  I think QT has an API for plugin-like systems anyways, so it shouldn't be hard to implement these side-by-side without too much hassle... once we get done with bug fixes and core features anyways. :)

**Comment by JuBan1** [comment]
Yep, that sounds like something to be done once all the internal systems have stabilized, at the very earliest. But it's an idea.
