### ISSUE TITLE
GUI Preferences Restore

### ISSUE THREAD

**Issue by dagostinelli** [notepadqq/notepadqq#269]
Is there a way to delete all the preferences and restore to "factory defaults"?

In my case, after a reformat and restore of my personal settings (in my linux profile) and then from downloading latest notepadqq, recompiling, I seem to have conflicting keyboard shortcuts and it's tedious to fix this.  I want to just clear and start over.

**Comment by Teklad** [comment]
If you go into ~/.config/Notepadqq/Notepadqq.ini , you should be able to 
find a section called "Shortcuts",  if you remove that entire section it 
should restore your shortcuts to the defaults (I think).

**Comment by dagostinelli** [comment]
Hmm, now I think there might be a bug.  I did what you said.  Relaunched Notepadqq, went to preferences, changed nothing, clicked OK and it said "Keyboard Shortcut Conflict".  When I press "Restore Defaults" it doesn't work.  I'll file a defect on this now.

**Comment by dagostinelli** [comment]
I logged #270

**Comment by Teklad** [comment]
Thanks. :)

**Comment by danieleds** [comment]
Tracked in #270
