### ISSUE TITLE
Restore Defaults (Shortcuts) does not work

### ISSUE THREAD

**Issue by dagostinelli** [notepadqq/notepadqq#270]
Hello, I think there might be a bug.  

`rm ~/.config/Notepadqq/Notepadqq.ini`

Launch Notepadqq -> Settings -> Preferences -> <change nothing> -> OK

It says "Keyboard Shortcut Conflict" and it shows me the Shortcuts tab.

When I press "Restore Defaults", then press OK, same thing.

**Comment by dagostinelli** [comment]
Also, I don't think deleting the file first makes any difference.

**Comment by danieleds** [comment]
Thank you for the report.
Do you see any highlighted shortcut in the shortcuts tab?

What language are you using? English?

**Comment by dagostinelli** [comment]
English.  Yes, I see highlighted shortcuts (a lot of them). 

I found a symptom.  It looks like there is a duplication of shortcuts happening.  I collapsed all of the sections; below Extensions is one without a name; under it is the tree all over again "File, Edit, Search, View, etc".

**Comment by danieleds** [comment]
Hmm, quite strange.
Are you compiling from the master branch?

@JuBan1 any idea?

**Comment by dagostinelli** [comment]
Yes, master branch.  

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

```

```
git pull
./configure <blah, blah, blah>
make
make install
<launch>
<does it again>

```

**Comment by danieleds** [comment]
Okay, let's try to exclude any issue with Qt itself. Can you verify what version is Notepadqq picking up, from `? -> About Qt...`?

**Comment by JuBan1** [comment]
Turns out I can actually confirm the bug.

I grabbed the newest version and it exhibits the same behavior for me. A quick tests tells me the problem lies with enumerating all menues and adding them to the shortcuts tree. This is the output with some debug messages:

```

Menu name:  "menu_File"
Menu name:  "menu_Edit"
Menu name:  "menu_Search"
Menu name:  "menu_View"
Menu name:  "menuEncoding"
Menu name:  "menuSe_ttings"
Menu name:  "menu"
Menu name:  "menuRun"
Menu name:  "menu_Window"
Menu name:  "menuExtensions"
Menu name:  ""
```

Apart from admiring the inconsistent naming scheme, there's also a rogue menu entry. The last one. It doesn't have an objectName() and apparently counts as the parent for *all* other items. Maybe The menubar itself counts as a menu and all its items are its children? 

What is weird is that this is now suddenly happening.

**Comment by danieleds** [comment]
And even more strange, I'm still not able to reproduce.

(Yeah I'll have to fix those names. Qt Designer created them without knowing what the underscore meant)

**Comment by JuBan1** [comment]
Maybe it's a difference in the desktop environment used. I'm using the same Qt version as before but with this machine I'm using KDE Plasma and with my desktop at home I'm using Gnome. What DE are y'all using?

**Comment by danieleds** [comment]
Gnome here

**Comment by dagostinelli** [comment]
Gnome. Fedora 24

**Comment by Teklad** [comment]
Another small bug that's cropped up... apparently (for me at least).  
The "Recent Files" menu is crammed into my available actions without any 
submenus if the recent files list is empty.

I use Awesome and/or XFCE respectively, here's my QT information.

Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by 
GCC 6.1.1 20160707) on "xcb"
OS: Arch Linux [linux version 4.7.2-1-ARCH]
Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX

Environment:
Features: QT_NO_EXCEPTIONS QT_NO_ZLIB

**Comment by Teklad** [comment]
Oh, and I'm with @danieleds on this.  I can't for the life of me 
reproduce the bug described.  I'm not even sure where to begin on this one.

**Comment by JuBan1** [comment]
Unsurpringly I couldn't find any info about similar bugs such as this on the internet.

The fix, however, is dead simple. I'll put up a PR later.
