### ISSUE TITLE
Development road map

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#278]
We should seriously consider setting up a development road map pretty soon for the "path to 1.0" so we can all get an idea of what needs to be done to get there.  Having an idea of what features/improvements need to be taken care of will give us a better view of what we can contribute to polish up nqq. :)

Making use of the milestones feature of github could get us in the right direction.

Opinions on this?

**Comment by danieleds** [comment]
You're right. I've just created a new milestone.
