### ISSUE TITLE
the translation does not work 

### ISSUE THREAD

**Issue by david-geiger** [notepadqq/notepadqq#281]
Hi,

I have recently pull-requested the French translation and tested notepadqq with the latest git master snapshot, but after installing the package and starting it I see that the language is still on default English.
So I set "French" language in Settings -> Preferences... -> General -> Localization and restart notepadqq but same default English language is still in use, no action done.
So after a quick search I found what is going wrong, here the attached patch:

[fix-translations.patch.txt](https://github.com/notepadqq/notepadqq/files/504365/fix-translations.patch.txt)

Also another question: would it be possible at first run to autodetect the language from users system? so users do not need to select themselves the languages.

Best Regards,
David

**Comment by Teklad** [comment]
I've sent in a pull request #282  to patch up this issue for you as well as include the language auto-detection.  :)

**Comment by Teklad** [comment]
Could you elaborate on how you installed the package?  I'm trying to grasp what is going on with your system which causes this.  

Also, can you verify if the directories /usr/local/share/notepadqq/translations or /usr/share/notepadqq/translations exist for you?

**Comment by david-geiger** [comment]
Yeah! I understand better now, we installed all binaries in "/usr/bin/" as it should be and not in "/usr/lib/project_name/", this is why it can't find translations in "/usr/share/notepadqq/translations/"

$ ls /usr/bin/ |grep notepadqq
notepadqq*
$
$ ls /usr/share/notepadqq/translations/
notepadqq_de.qm  notepadqq_fr.qm  notepadqq_hu.qm  notepadqq_pl.qm  notepadqq_ru.qm
$

So why install the binary in /usr/lib/notepadqq/ ?
And why not include all translations directly compiled in the binary?

**Comment by david-geiger** [comment]
Yes I think so, embed the translations into the binary will be the best solution :)

**Comment by danieleds** [comment]
I'm going to bundle them into the binary.
