### ISSUE TITLE
Layout issues with "new" tabs

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#286]
There's the `&` in the window title and in the suggested filename when saving a file. And with other localizations than English or Russian, the first letter of the tab's title is underlined, and not the number.

![screenshot_20161002_041515](https://cloud.githubusercontent.com/assets/5700937/19018192/e5016d56-8858-11e6-81fb-9bfd64f88ee2.png)
![screenshot_20161002_041833](https://cloud.githubusercontent.com/assets/5700937/19018194/e8b38c86-8858-11e6-9cb4-0a9ad0885832.png)
![screenshot_20161002_041745](https://cloud.githubusercontent.com/assets/5700937/19018195/eba36088-8858-11e6-9ff6-8ad9cd33fc9e.png)
##

**Comment by Teklad** [comment]
Honestly, I'm not sure why we are still using the "new %i" format, but I 
know how to fix the issue easily enough (We're trying to translate %i, 
which will never work).  I'll submit a patch shortly to address the 
issue.  I'd like to hear @danieleds opinion on just changing it to a 
more generic "untitled" and not worry about integer tracking.

**Comment by Teklad** [comment]
If you could test the changes in #287 to verify if it fixes the issue, that would be greatly appreciated. :)

**Comment by JuBan1** [comment]
Imo having new tabs numbered is a good thing. Either that or they should be somehow differently labeled. It helps a lot to be able to distinguish them just by looking at the tab title.

**Comment by danieleds** [comment]
Yes, numbers are a good thing to distinguish tabs at a glance.

Anyway, I don't understand the nature of the problem (and neither the proposed fix).
I mean, we do not handle the underscore in the tab names. Where is it coming from? And why is it sometimes "leaking" in the form of an ampersand instead of being interpreted as a shortcut identifier?

**Comment by Teklad** [comment]
It probably varies a bit between QT versions, but basically... as a 
general rule you aren't supposed to translate dynamic strings (as far as 
I know).  We were translating %1 as-is along with the rest of the "new" 
string.

**Comment by danieleds** [comment]
`%1` is a placeholder for a parameter, that's the correct way to handle composed strings.
For example, in english you say "3-way handshake". In italian, that would become "handshake a 3 vie". You don't know the position of the number in each language, so you need a placeholder.

**Comment by Teklad** [comment]
Hold on, I figured out how to do it... we were translating the string 
wrong, but I went the wrong way about fixing it... one sec and I'll push 
something that should work.  I'll just need someone who experiences the 
issue to test.

**Comment by Teklad** [comment]
I got too excited, lol.  I wasn't very familiar with QT's translation 
when I poked at this.  Unfortunately, I haven't the slightest clue 
what's going on at this point, so my proposed fix is most likely a 
band-aid at best, and breaks translation.
