### ISSUE TITLE
notepadqq $ ./configure --prefix /usr dont work

### ISSUE THREAD

**Issue by BoBBer446** [notepadqq/notepadqq#296]
`rene@LinuxMint-Stick ~ $ cd notepadqq
rene@LinuxMint-Stick ~/notepadqq $ ./configure --prefix /usr
checking for QT5 qmake... not found!
 Try to run configure with `--qmake /path/to/qmake-executable'.
`

eh, sorry.... delete, close ..Ash on my head

**Comment by JuBan1** [comment]
You should be able to close the issue on your own. (Button to the left of the green Comment button)
