### ISSUE TITLE
Notepadqq not available for Ubuntu 16.10

### ISSUE THREAD

**Issue by willydee** [notepadqq/notepadqq#298]
Trying to install the app from the PPA raises error messages:
`E: The repository 'http://ppa.launchpad.net/notepadqq-team/notepadqq/ubuntu yakkety Release' does not have a Release file.`

Please kindly make it available for Ubuntu 16.10 too, Thank you so much!

Best, willydee

**Comment by danieleds** [comment]
Fixed, thank you!
The package should be available in a few hours.
