### ISSUE TITLE
Customizable editor line-height

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#300]
I prefer the line-height to be set a bit higher.
I figured it's set in `/usr/share/notepadqq/editor/styles/app.css` in the `.editor > .CodeMirror` part, so I just edited that file.
But can you make it customizable in the settings, like the text size?

**Comment by Teklad** [comment]
@juban1 , think you could whip up something real quick for this? I don't see any issues with having it.

**Comment by JuBan1** [comment]
I'll add it to the Font setting. Shouldn't be much work, so probably tomorrow.
