### ISSUE TITLE
To remove obsolete strings from notpadqq_"language code".ts file

### ISSUE THREAD

**Issue by SandorPetrovics** [notepadqq/notepadqq#313]
To remove string tagged vanished from notedpadqq_pl.ts file, please execute lupdate with -no-obsolete option e.g lupdate -no-obsolete "path to ui.pro" -ts "path to notepadqq_pl.ts"

**Comment by danieleds** [comment]
We could use a page in the wiki ([Translate Notepadqq](https://github.com/notepadqq/notepadqq/wiki/Translate-Notepadqq)) to explain this too.

**Comment by danieleds** [comment]
Page created. Feel free to send suggestions.
