### ISSUE TITLE
High DPI displays not supported

### ISSUE THREAD

**Issue by ahmetsait** [notepadqq/notepadqq#323]
Currently, Notepadqq toolbox entries are shown too small on my screen (an also text is unreadabily small but I can change font size). It should support GUI & font scaling according to system display settings.
*Edit:* I'm on Ubuntu 16.04

**Comment by JuBan1** [comment]
For curiosity's sake, could you try to follow the instructions [here](http://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt) and see how well Qt's automagic high-DPI support does the job? From what I read setting QT_AUTO_SCREEN_SCALE_FACTOR to "1" should be enough.

**Comment by NightmareX1337** [comment]
Okay... So I tried some combinations trying to get it work and here are the results:
- Executing `QT_AUTO_SCREEN_SCALE_FACTOR=1 notepadqq` makes completely no difference
- Executing `QT_AUTO_SCREEN_SCALE_FACTOR=2 notepadqq` makes no difference either
- Executing `QT_SCALE_FACTOR=1 notepadqq` or `QT_SCALE_FACTOR=2 notepadqq` makes completely no difference
- Executing `QT_DEVICE_PIXEL_RATIO=1 notepadqq` or `QT_DEVICE_PIXEL_RATIO=1.5 notepadqq` changes nothing
- Executing `QT_DEVICE_PIXEL_RATIO=2 notepadqq` makes whole UI to be rendered 2 times bigger and awfully pixelated
- Executing `QT_DEVICE_PIXEL_RATIO=2.5 notepadqq` interestingly renders without any scaling (same as normal run)

I would expect QT_DEVICE_PIXEL_RATIO=1.25 to magically work but to my surprise it just discards floating values.

**Comment by JuBan1** [comment]
That's weird. `QT_SCALE_FACTOR` works well for me and does allow decimals. On Ubuntu you could also try `GDK_SCALE=X` which is supposed to use GTK+3's scaling mechanism.

Other than that I don't know how to help. I was playing with the thought of buying a high DPI monitor for Christmas. If I do I'll work on supporting it for both of our sakes.

**Comment by NightmareX1337** [comment]
So it seems notepadqq is using Qt 5.5.1 (as 'About Qt...' shows). Then I installed Qt 5.7 by hand thinking it might automagically use it over old one but well... I guess I'm not experienced enough to understand how things even work under linux. Are you sure Notepadqq is actually compatible with newer versions? I feel I'm missing out some trivial stuff..

**Comment by JuBan1** [comment]
Quite sure Nqq is compatible with newer versions. I use 5.7.0 myself. What probably happened is that you've installed the two versions side-by-side. Now you've got both on your system but the default one is chosen for all programs.

Unfortunately I have neither Ubuntu nor more than one Qt version installed so guiding you to a solution is a bit tricky. You could upgrade to Ubuntu 16.10 which would bring you Qt 5.6 among other things or you could try what has been suggested here: http://stackoverflow.com/questions/30303277/ubuntu-14-04-qt-version-choosing So go to where you installed 5.7, locate `qmake` and call it, then call notepadqq (from the terminal). That is only a workaround since you'd have to do that every time before opening nqq, although it can be automated with a launcher. It's a lot of fiddling, probably.

Linux is a daunting beast at first- it takes time to learn its ways :)

**Comment by danieleds** [comment]
If you install a version of Qt in `~/Qt/`, Notepadqq will use that.

**Comment by snarum-NIS** [comment]
The auto scale causes the following error dump for me:

```
$ QT_AUTO_SCREEN_SCALE_FACTOR=1 notepadqq
QWidget::setMinimumSize: (advancedSearchDockWidget/QDockWidget) Negative sizes (0,-1) are not possible
QWidget::setMaximumSize: (advancedSearchDockWidget/QDockWidget) Negative sizes (524287,-1) are not possible
QXcbConnection: XCB error: 3 (BadWindow), sequence: 408, resource id: 8388612, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 409, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 410, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 411, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 413, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 414, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 415, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 418, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 422, resource id: 8388612, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 423, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 424, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 425, resource id: 8388612, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 429, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 430, resource id: 8388612, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 433, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 434, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 437, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 438, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 455, resource id: 8388612, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 456, resource id: 8388612, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 457, resource id: 8388612, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 458, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 459, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 460, resource id: 8388612, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 461, resource id: 8388612, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 462, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 463, resource id: 8388612, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 464, resource id: 8388612, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 465, resource id: 8388612, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 466, resource id: 8388612, major code: 8 (MapWindow), minor code: 0

^C
```

The manual scaling works-ish.  That is, it scales the entire window.  However, with no scaling, the top and bottom menus are fine, it is just the toolbar and edit panes that are too small.  It seems that parts of notepadqq are scaling differently than others.

(Note that the text cursor and top window title are the same size (and sane) in all three of these shots.)

(No scaling)
![image](https://user-images.githubusercontent.com/35970935/36391165-93faa0ec-1562-11e8-80df-6ba67dea0a37.png)

(QT_SCALE_FACTOR=2)
![image](https://user-images.githubusercontent.com/35970935/36391235-e80ded56-1562-11e8-864c-d845c6516c66.png)

(QT_SCALE_FACTOR=3)
![image](https://user-images.githubusercontent.com/35970935/36391287-264503c0-1563-11e8-9fb6-f531729cdcd9.png)

**Comment by humaidq** [comment]
My DPI setting is 200% with Ubuntu 18.04. Adding `export QT_DEVICE_PIXEL_RATIO=2` in my `~/.profile` fixed the problem. It looks perfect with that setting, sadly you cannot set the ratio to 1.5 but this isn't an issue on Ubuntu as there is no 150% scaling option yet.

Without environment setting:
![image](https://user-images.githubusercontent.com/10805493/39227005-2faf3aac-4867-11e8-99b2-e0f4e24a6d8f.png)

With setting:
![image](https://user-images.githubusercontent.com/10805493/39226976-ff6a607e-4866-11e8-86ec-601ebeaa9887.png)

**Comment by ahmetsait** [comment]
Is this still a relevant issue? I can confirm that notepadqq renders correctly on my kubuntu environment using Qt 5.12.8 with 125% UI scaling.
Feel free to open it if there are others still having problems.

**Comment by zorzysty** [comment]
It still does not look right on my pc:

![obraz](https://user-images.githubusercontent.com/5398733/145082544-b481b7a4-9728-4677-a9bc-5979ca7d557c.png)
![obraz](https://user-images.githubusercontent.com/5398733/145083312-06aa29d8-1c35-4099-8772-d11d7e8d9ca7.png)



OS: Manjaro 21.2.0 Qonos
Kernel: x86_64 Linux 5.10.79-1-MANJARO
Resolution: 3840x2160
Scale: 200%
DE: KDE 5.88.0 / Plasma 5.23.3
WM: KWin
