### ISSUE TITLE
Crash when trying to save file

### ISSUE THREAD

**Issue by nolanpatrick** [notepadqq/notepadqq#326]
Notepadqq crashes when attempting to save any file whether or not there are edits.

**Comment by JuBan1** [comment]
I think I can speak for all of us if I say that this isn't intended behavior.

Can you add some details? Did you compile it yourself? What distro do you use? What Qt version? Also, does it only crash when trying to save "new" documents or also if you open an existing file in Nqq and attempt to save it?

**Comment by nolanpatrick** [comment]
I compiled it from this GitHub repo on an Arch Linux laptop. Both AUR packages have the same issue as well. I am running Qt 5.7.0. It crashes when I attempt to open files as well as saving.

When I run it from the terminal, the error is a segmentation fault. From what I could tell it is the same error with both 'Open,' 'Save' and 'Save-As' actions, including the 'Open Folder...' option. Here is the output of running Nqq and trying one of the options.
[nolan@archbook notepadqq]$ notepadqq 

(notepadqq-bin:6285): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
Segmentation fault (core dumped)
[nolan@archbook notepadqq]$

**Comment by JuBan1** [comment]
[Are you using Gnome on Wayland?](https://bbs.archlinux.org/viewtopic.php?id=218680)

**Comment by sysrqbr** [comment]
Hi!

Same problem here!

(Fritzing:7927): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
Segmentation fault (core dumped)
 My system is a Fedora 25

Any workaround?

**Comment by nolanpatrick** [comment]
The only workaround so far is to use Xorg rather than Wayland for now until
we have better support for Xorg programs in Wayland.
