### ISSUE TITLE
Including GAMS highlighting

### ISSUE THREAD

**Issue by yordiak** [notepadqq/notepadqq#334]
Is it possible to include GAMS as an option in the "Languages" tab?

**Comment by yordiak** [comment]
[Here ](https://www2.warwick.ac.uk/fac/soc/ier/people/yerushalmi/main/computing/npp/) is gams highlighting in notepad++. However, I am not a programmer, so I don't know how to implement it in notepadqq

**Comment by JuBan1** [comment]
Unfortunately Nqq uses a very different way of implementing language highlighting than N++ does. It can't be directly transferred. I did a quick google if GAMS is available in CodeMirror (which is what Nqq uses) but to no avail.

So I'm afraid you're out of luck unless someone writes it.
