### ISSUE TITLE
Translate notepadqq in Italian

### ISSUE THREAD

**Issue by marcoM32** [notepadqq/notepadqq#335]
First I wanted to thank you for this program, it is really very beautiful and is very useful! 
During use however, I would like to have him in Italian, how can I translate it? Once translated, you can integrate this new resource in the official package?

Thanks and best regards

**Comment by darealshinji** [comment]
Here's some information on translating it:
https://github.com/notepadqq/notepadqq/wiki/Translate-Notepadqq

**Comment by danieleds** [comment]
Thank you! :) If you have further questions which are not explained in the wiki, feel free to ask.

**Comment by urmatej** [comment]
Hello,
just to chip in for other languages ...
So, the translations hosted on https://translations.launchpad.net/notepadqq do not count?
Can I send the translation to someone?

Thanks,
Matej

**Comment by danieleds** [comment]
No, launchpad does not count.

To submit it, you can open a pull request here on GitHub which includes your changes.

Ask if you need more help

**Comment by urmatej** [comment]
OK, thank you for your answer.
Now I need to figure out, how to transcode po2ts.
Thanks

**Comment by urmatej** [comment]
Hello, another question ...
Is it possible to test the translation in the program **without** compiling? I can not find the language files anywhere.
Thanks

**Comment by danieleds** [comment]
No, unfortunately you have to recompile it so that they get embedded in the binary executable.

You will find the files in `src/translations`: https://github.com/notepadqq/notepadqq/tree/master/src/translations

Follow this guide: https://github.com/notepadqq/notepadqq/wiki/Translate-Notepadqq
