### ISSUE TITLE
How to load other language ?

### ISSUE THREAD

**Issue by sonichy** [notepadqq/notepadqq#343]
I want to translate to Chinese language localization.

**Comment by darealshinji** [comment]
This should help: https://github.com/notepadqq/notepadqq/wiki/Translate-Notepadqq

**Comment by JuBan1** [comment]
You can select the language in Nqq under Settings->General->Localization. You don't have to rebuild for that.

But to *add* a new language like Chinese you create a translations file, we put it into the program, and everyone gets it.
