### ISSUE TITLE
Notepadqq crashes when...

### ISSUE THREAD

**Issue by guekho64** [notepadqq/notepadqq#344]
I know the title isn't as self-explanatory as it should, but It seemed difficult for me to describe the way it crashed...

Here's the way to reproduce it:

1. Open nqq
2. Open a file
3. Open a second file NOT indented with your default indentation settings (Just make the "indentation warning" dialog appear)
4. Move file to "Other View"
5. Now, click "Use spaces/tabs" (Whatever option appears to you) and prepare your data to be forgot :(

Luckily, It seems Nqq made a .bck file from my lost data. 
Unluckily, it contains nothing new (A exact copy of my last file before the modifications made with Nqq)

P.S = I haven't tried to click "Close" instead of using recommended indentation...
P.S 2 = Console output just says "Segmentation Fault"

**Comment by JuBan1** [comment]
Thanks, the detailed step-by-step guide helped a lot.
