### ISSUE TITLE
Changes in settings aren't saved

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#345]
When I change something in the settings, the language for example, those settings are reseted to the default on the next start. This happens with my own compiled version as well as with the precompiled version from the release section. Deleting `$HOME/.config/Notepadqq` doesn't help. I'm on Ubuntu 16.04 here.

**Comment by danieleds** [comment]
Just happened to me too. It looks like the settings *are* saved, but notepadqq is always picking up the default settings instead. Can you confirm?

**Comment by danieleds** [comment]
I think I got it. Someone wrote "ensureBacwardsCompatibility" without considering the major version number: https://github.com/notepadqq/notepadqq/blob/master/src/ui/nqqsettings.cpp

Fix in progress
