### ISSUE TITLE
#344 it's still alive!

### ISSUE THREAD

**Issue by guekho64** [notepadqq/notepadqq#358]
Somehow, right now I did the same as with 0.5x version, but now using stable 1.0.1 and the same happend. You can see #344 again for details about this crash...

P.S: Didn't erase old Nqq Config file at the time being
P.S.2: Console output it's the same

**Comment by danieleds** [comment]
@JuBan1

**Comment by JuBan1** [comment]
Can't reproduce. Just to make sure: Going to Help->About Notepadqq says you've got 1.0.1?
