### ISSUE TITLE
Error while trying to save this session

### ISSUE THREAD

**Issue by tsoernes** [notepadqq/notepadqq#361]
**I'm submitting a [x] bug report **  

**Current behavior**

Error while trying to save this session. Please ensure the following directory is accessible:

/home/myname/.config/Notepadqq/tabCache
**Expected behavior**

Close cleanly

**Please tell us about your environment:**

Notepadqq v1.0.1 from repo on Linux Mint 17.2 x64

I think it only happens when launching notepadqq from terminal but I'm unsure

**Comment by JuBan1** [comment]
This error shows up when Nqq can't read or write to the tabCache directory. That could be an issue with the directory's permissions, but honestly it's pretty hard to say without knowledge about your system.

You could try manually deleting that tabCache folder as well as the session.xml file that's in the same directory as tabCache. That will clear all remembered tabs.

**Comment by danieleds** [comment]
Follow JuBan1's advice. That issue might be caused by running notepadqq as root.

**Comment by Teklad** [comment]
There's a one-liner I use to fix permissions for .config... I modified it a bit to target Notepadqq's directories specifically.  

`
if [ ! -v XDG_CONFIG_HOME ];then XDG_CONFIG_HOME="$HOME/.config";fi;sudo find "$XDG_CONFIG_HOME/Notepadqq" -type f -exec chmod -v 644 {} \; -exec chown -v $UID.$GID {} \; -o -type d -exec chmod -v 755 {} \; -exec chown -v $UID.$GID {} \;
`

Of course, as with any suggestions, use at your own discretion. :)

**Comment by tsoernes** [comment]
The issue was not caused by running npp as root. The one-liner worked but I had to replace `$UID.$GID` with my username. Thanks!
