### ISSUE TITLE
Just a congratulatory note!

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#362]
I'd like to congratulate all of the work everyone has put into Notepadqq.  After a couple years of hard work, we're finally starting to get package maintainers for some larger distributions.

As of three days ago, Arch Linux now includes Notepadqq in its repositories. See:
https://www.archlinux.org/packages/community/x86_64/notepadqq/

Installation instructions should probably be updated to include this detail, since building from AUR will no longer be necessary.

Great job to everyone involved with Notepadqq!

**Comment by JuBan1** [comment]
Oooooo, shiny.

**Comment by danieleds** [comment]
Great news! This is surely an important milestone. Nice work guys :)

Someone using Arch which can update the readme to reflect this change? :)
