### ISSUE TITLE
No proper source archives

### ISSUE THREAD

**Issue by hasufell** [notepadqq/notepadqq#369]
Because this project uses submodules, downloading via git tags is broken. Your github releases only offer precompiled stuff, but not actual source archives containing the submodule source code.

**Comment by darealshinji** [comment]
I agree, there should be a full source tarball among the releases. Until that happens however such tarballs could be downloaded from the PPA.

**Comment by Teklad** [comment]
It wouldn't be hard to make this part of the release process via an automated script of some sort... If someone wants to release nightly tarballs I'm not against it.

**Comment by hasufell** [comment]
https://github.com/Kentzo/git-archive-all might be a start which works like `git archive` except that it includes submodules
