### ISSUE TITLE
QtWebEngine: toolbar shows language code instead of language name

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#377]

**Comment by Teklad** [comment]
Okay, so this one should be an easy fix... I probably just pulled the wrong value here.

**Comment by Teklad** [comment]
Fixed in b1cd80d

**Comment by Teklad** [comment]
Quick question... do we even use the values sent in the "currentLanguageChanged" slot?  Judging by what I found in mainwindow.cpp I'm assuming that we don't as of the moment.

**Comment by danieleds** [comment]
I'm not sure if it's useful to keep passing them or not. Let's keep them for now and then we'll see when everything is merged and stable.
