### ISSUE TITLE
Benchmarking eye candy.

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#382]
Due to the structural changes required to get QWebEngine implemented, we've had an interesting side effect.  BEHOLD:

Current Notepadqq Master Branch:
```
Tab opened in 150msec
Tab opened in 7msec
Tab opened in 65msec
Started in 771msec
```

New WebEngine branch:
```
Tab opened in 5msec
Tab opened in 2msec
Tab opened in 2msec
Started in 501msec
```

That's a 35% decrease in the amount of time required to start Notepadqq.... I consider that to be a good win. :)

**Comment by JuBan1** [comment]
It seems a little faster, yes. Numbers for me are ~550ms -> ~250ms so actually more than half! 

Although, to be fair, there's now a bunch of stuff loaded after the start-up timer has ended.

**Comment by danieleds** [comment]
That's awesome! :smiley:

**Comment by Teklad** [comment]
All the tabs are loaded at the same time because of how QWebEngineView is threaded... so its actually faster... once we get done with QWebEngine and get the new Editor interface previously discussed implemented, we should see some very nice performance gains all around.

Unfortunately that's going to mean another very large PR later on as well, lol.
