### ISSUE TITLE
About Notepadqq, Contributors shows 404

### ISSUE THREAD

**Issue by ppfeiler** [notepadqq/notepadqq#386]
Hi,

when opening Notepadqq and open the "About Notepadqq" Window (<kbd>F1</kbd>) and clicking at the link "GitHub Contributors", the default Webbrowser opens and shows a 404 error because the link is incorrect.

What should be the correct link? Maybe https://github.com/notepadqq/notepadqq/network/members ?

**Comment by darealshinji** [comment]
Or https://github.com/notepadqq/notepadqq/graphs/contributors ?
Maybe the Github API can be used to aquire a list at compile time (or before compiling) and hard-code that into the program?

**Comment by danieleds** [comment]
The "contributors" file was removed because it was highly outdated. I don't think the "members" page of github is accurate enough for this (it also shows whoever forked the repo without contributing).

We could use https://github.com/notepadqq/notepadqq/graphs/contributors

Acquiring the list of contributors before compiling would be nice too. I say *before compiling* because I'd avoid making the compilation process dependent on GitHub. A bash script which can be manually executed to update a local list of contributors to hard-code into the program would be great.

**Comment by darealshinji** [comment]
Using curl:
```
$ curl -s https://api.github.com/repos/notepadqq/notepadqq/contributors | grep '"login":' | cut -d '"' -f4
danieleds
darealshinji
JuBan1
OpenNingia
SandorPetrovics
hawkeye116477
Teklad
vpop
aadityakalsi
flavio20002
rprego
david-geiger
xDShot
flamusdiu
pcatalani
Algomorph
maksqwe
urmatej
OhDaeto
Snektron
donced
kprkpr
marcoM32
eson57
```

**Comment by danieleds** [comment]
Nice! We could also link to the profile of each user.

That list is ordered by contributions. A lexicographic order might be more fair, or maybe not. That's your decision :)

**Comment by ppfeiler** [comment]
Okay. I would love to get the chance to do it and contribute to the project. 

> A bash script which can be manually executed to update a local list of contributors to hard-code into the program would be great.

So instead of the link it should open a simple window like the licence window? And the data for the window will be manually generates with a simple bash script?

**Comment by danieleds** [comment]
Ok! I'm going to assign this to you then.

I'm not sure yet about what a good UI would be for that information, however we can start with something like the license window.

I suggest creating a bash script which generates a file `src/ui/include/contributors.h` with the information that we need about the contributors (basically nickname and link). You could represent that information within a QList or whatever you think is better.

**Comment by ppfeiler** [comment]
Hi, can you help me please? How can I debug notepadqq with QTCreator? I can build notepadqq but when I start it for debugging, the following warning pops up...

![screenshot from 2017-03-13 06-57-51](https://cloud.githubusercontent.com/assets/1992680/23843205/65e888d8-07ba-11e7-87b8-74a160c91ace.png)

Should I use a specific paramter for `make` ?
My Build and Run settings:

![screenshot from 2017-03-13 06-59-50](https://cloud.githubusercontent.com/assets/1992680/23843239/b449ce7e-07ba-11e7-8827-285e1d4a392f.png)
![screenshot from 2017-03-13 07-00-03](https://cloud.githubusercontent.com/assets/1992680/23843244/b843e76c-07ba-11e7-9de0-f8d12d4f62d3.png)

I have done the following steps:

1. `$ sudo apt install libqt5webkit5-dev libqt5svg5-dev qttools5-dev-tools` 
2. `$ git clone --recursive https://github.com/notepadqq/notepadqq.git`
3. `./notepadqq/configure`
4. then I opened the project in QT Creator with the build & run settings postet above

**Comment by danieleds** [comment]
Select a debug build from the left panel:

![schermata del 2017-03-13 10-12-25](https://cloud.githubusercontent.com/assets/402652/23848074/b8274696-07d5-11e7-8bb0-30955e7cde51.png)

**Comment by ppfeiler** [comment]
Hmm... I cant select a debug build...

Can you share your Build & Run configs with me please?

**Comment by Teklad** [comment]
It's okay... everyone was new once!  Go ahead and delete your notepadqq.pro.user file if it exists.... and then reopen QtCreator and open notepadqq.pro.

When it firsts asks you to configure the project... your screen should look like this:
![2017-03-13-065906_1253x700_scrot](https://cloud.githubusercontent.com/assets/2869605/23853448/b275ecf4-07ba-11e7-8923-ef63921a203b.png)


Notice that I have Debug checked?  This enables Debug builds to be selected from the left panel as @danieleds described.  I don't personally use QtCreator much, but I've had to poke at qmake enough to know how this evil works. :p

**Comment by ppfeiler** [comment]
Thank you @Teklad 

Now I have the debug options but some Issues:
![screenshot from 2017-03-13 13-08-42](https://cloud.githubusercontent.com/assets/1992680/23853744/4e2b675e-07ee-11e7-9a3a-aa1323ea37b4.png)

**Comment by Teklad** [comment]
You're missing some gst dev packages I believe...  Try installing: libgstreamer-plugins-base1.0-dev

**Comment by ppfeiler** [comment]
Hmm... I have `libgstreamer-plugins-base1.0-dev` installed... At my first attempts to get notepadqq ready for debugging I could build it...

**Comment by Teklad** [comment]
Well the only other reason this would fire off would be your gstreamer libraries aren't new enough (i.e. missing symbols)... What distro do you use?

**Comment by Teklad** [comment]
More specifically... which version of the distro are you running?

**Comment by ppfeiler** [comment]
I deleted everything from notepadqq and done everything from checkout to importing the project. There was a kit error in QTCreator...

Now (I hope the last problem) is that when I start debugging, the following message is in "Application Output":

`Debugging starts
Start-time benchmark started.
WARNING: Notepadqq is running in DEBUG mode.
"Can't open file: /home/ppfeiler/Projects/build-notepadqq-Qt_5_5_1_qt5_temporary-Debug/out/debug/lib/../../share/notepadqq/editor/index.html"
Debugging has finished`

The build is okay but I dont know where thie file should come from? I cant find it on my filesystem...

**Comment by Teklad** [comment]
In your build settings (Under Projects)... disabling "shadow build" and recompiling should fix that.

**Comment by ppfeiler** [comment]
@Teklad thank you so much.

So, the next: break points are ignored... The application ignores my breakpoint, but it writes "Debugging starts"...

**Comment by Teklad** [comment]
For breakpoints you need to use the Debug menu.... or hit F5 to run instead.

**Comment by ppfeiler** [comment]
I know, I start the application with the Debug Menu (the green arrow with the bug). But he ignores my breakpoints...

**Comment by Teklad** [comment]
Where are you setting a breakpoint exactly?

**Comment by ppfeiler** [comment]
For example "frmabout.cpp":47, then the debugger should stop when I press the "licence button". But he ignores my breakpoint and opens the licence message box.

![screenshot from 2017-03-13 14-06-44](https://cloud.githubusercontent.com/assets/1992680/23855540/4e655b32-07f6-11e7-9eee-0de60d98d857.png)

**Comment by Teklad** [comment]
What's your application output look like?

**Comment by ppfeiler** [comment]
"Debugging starts" 

![screenshot from 2017-03-13 14-10-32](https://cloud.githubusercontent.com/assets/1992680/23855659/d49cae76-07f6-11e7-91fa-be506c179653.png)

**Comment by JuBan1** [comment]
Something's probably wrong with your build config. It should look something like this:

![image](http://i.imgur.com/C04nFyb.png)

See if you've got the CONFIG+=debug part in there somewhere. Without it setting breakpoints probably won't work.

**Comment by danieleds** [comment]
Also try opening ui.pro directly instead of notepadqq.pro.

**Comment by ppfeiler** [comment]
Thanks for all that answers but something is wrong... My build config looks like yours... I have another c++ project in qt creator and it works. 

Maybe some one can help me over teamviewer or something? I dont know what the problem could be...

**Comment by JuBan1** [comment]
Was fixed in a different commit a while ago.
