### ISSUE TITLE
QtWebEngine: syntax highlighting doesn't work in Editor preview in preferences dialog

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#389]

**Comment by JuBan1** [comment]
Syntax highlighting works fine for me.

Only issue is that the gutter(?) hides parts of the text with some themes. That was fixed by Teklad for QtWebkit but is broken again for QtWebEngine.

![image](http://i.imgur.com/TB1aI3T.png)

**Comment by danieleds** [comment]
This is the look of that dialog on my machine:

![schermata del 2017-03-12 17-12-49](https://cloud.githubusercontent.com/assets/402652/23833508/2e7f0a8e-0747-11e7-838c-13694c87a113.png)

**Comment by JuBan1** [comment]
Just to be sure: a clean recompile does not change that?

**Comment by danieleds** [comment]
nope...

**Comment by Teklad** [comment]
What version of QT you using?

**Comment by danieleds** [comment]
Qt 5.7. Can't try on 5.8 right now. You're both on 5.8 right?

**Comment by Teklad** [comment]
That would be correct.... @JuBan1 uses Arch Linux just like I do, I believe.

**Comment by JuBan1** [comment]
Yes, arch, the objectively best distro.

@danieleds does the font family change when selecting different themes? If not, I#d guess it's setTheme() that for some reason doesn't do its job. I doubt it's a solely Qt related issue because it works in non-preview views. There's something about the preview view that makes it not work.

**Comment by danieleds** [comment]
Yes the other options work correctly.

As soon as the preview editor is shown, the debug log displays:
```
js: Uncaught TypeError: CodeMirror.defineSimpleMode is not a function
js: Uncaught TypeError: CodeMirror.defineSimpleMode is not a function
js: Uncaught TypeError: CodeMirror.defineSimpleMode is not a function
js: Uncaught TypeError: CodeMirror.defineSimpleMode is not a function
Registered new object after initialization, existing clients won't be notified!
```

**Comment by Teklad** [comment]
Try changing this line for me:
```cpp
     30     m_previewEditor->setLanguageFromFileName("test.js");
```
to this:
```cpp
    m_previewEditor->setLanguageFromFileName("javascript");
```

It looks like an issue with highlighting specifically.  So my money is on one of the setLanguage functions being broken in JS.

**Comment by danieleds** [comment]
Tried. Still not working.

It works if I move the call to `setLanguageFromFileName("test.js")` to *after* the window has been shown. I'll see if I can discover more later.

**Comment by danieleds** [comment]
The issue is caused by this line: https://github.com/notepadqq/notepadqq/blob/1843603658a43f9addaec365733895b60d66ac7a/src/ui/frmpreferences.cpp#L105

Commenting it out "fixes" the problem. For some reason `m_previewEditor->getLanguage()` gives an empty string.

**Comment by danieleds** [comment]
To reproduce the issue, try setting "Override font family / override font size" on and then restart notepadqq.

**Comment by Teklad** [comment]
Hmm... I remember doing something to getLanguage... just trying to remember what it was.... one sec

**Comment by Teklad** [comment]
So what's happening is getLanguage is firing off before the editor has time to initialize the values... this will be fixed as a side effect from the async changes, luckily.

**Comment by Teklad** [comment]
If you change that line to setLanguageFromFileName("test.js")... the issue goes away as well.

**Comment by danieleds** [comment]
Yes but that doesn't fix the underlying problem :P
Let's wait for #400
