### ISSUE TITLE
Begin/End select Menu

### ISSUE THREAD

**Issue by ellicefix** [notepadqq/notepadqq#393]
There is a 'Begin/End select Menu' in the notepad++, it is very useful,Would you consider adding this feature to the new edition?

**Comment by JuBan1** [comment]
I see why this would be useful- our current GoTo Line implementation moves cursor selection as well.

It's something to keep in mind although it likely won't come anytime soon since it's fairly low priority.

**Comment by maravento** [comment]
After a year, I ask the same question as ellicefix. When will they implement 'Begin/End select Menu'... or or it is still "low priority"

**Comment by Teklad** [comment]
We're currently revamping the editor component to (hopefully) be a native widget.  This feature request got buried somewhere in the mounds of work we've managed to make for ourselves hacking together different parts of NQQ.  If all goes well we should be able to implement this feature soon-ish.  I can't give an exact ETA on it but basically whenever the editor component gets a very needed upgrade.

**Comment by JuBan1** [comment]
To add to that, Notepadqq is being worked on by three semi-active devs and we've about 100 outstanding issues of varying importance and difficulty. We have to triage because there's just too much to do.
