### ISSUE TITLE
Curiously...

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#395]
Has anyone put any thought into just writing our own QT-derived editor component rather than relying on things like CodeMirror(current) and icky nasty QScintilla(Many moons ago when I was younger)?

I realize it's quite a bit of work... but it has crossed my mind from time to time when I feel like kicking CodeMirror down into a deep dark valley.  I'm not saying we should (Its a HUGE time sink), but I do think it's very doable with our current knowledge and team. :P

Just some food for thought.  Kind of just wanting to pick everyone's brain today I guess, lol.

**Comment by JuBan1** [comment]
That was pretty much exactly my train of thought too. It's an attractive idea to have an editor suited and optimized specifically for Nqq but the time and effort is just not worth it- at least not until everything else about Nqq is basically done.

**Comment by Teklad** [comment]
Well in the event we were to actually write it... it could be written as 
a separate entity all together as kind of a side project.  There's 
really no time constraints for something like that, considering the 
scope, lol.

**Comment by danieleds** [comment]
I would love to have something like that, but it's a **big** project on its own. And I mean, really big.

A better approach would be to kick CodeMirror down into a deep dark valley (cit.) and switch to something similar which might be better and more active (the great engine of vscode comes to mind).

**Comment by danieleds** [comment]
Look at that!

https://microsoft.github.io/monaco-editor/

**Comment by JuBan1** [comment]
Got to admit, that looks pretty good.

**Comment by Teklad** [comment]
Well I was talking a custom widget as a long term goal.  NOT anytime in the immediate future.  It would take almost a year(maybe longer) probably to write something with enough features to drop into Notepadqq.

Anywho, for the moment its a pipe dream, lol... I've dabbled with it a bit and got some moderate success, but it is very time consuming.

**Comment by Teklad** [comment]
Considering javascript is going to be our limiting factor... a top notch editor component written in javascript is our best solution until we get really sick of stabbing JS with a stick.  CodeMirror is good, but lordy lordy is it a pain in the you know what to work with.

**Comment by danieleds** [comment]
I share all your hate for CodeMirror.
