### ISSUE TITLE
Notepadqq sluggishness in Fedora 25 + Qt 5.7

### ISSUE THREAD

**Issue by aryasenna** [notepadqq/notepadqq#396]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Opening, launching/closing tabs and opening/saving file on notepadqq are sluggish (2-3 seconds delay)
Please see: ![notepad-qq-slow](https://cloud.githubusercontent.com/assets/5351348/23871991/ec511b98-082c-11e7-9820-c53d4c24ba93.gif)

**Expected behavior**
Responsive operation

**Minimal reproduction of the problem with instructions**

1. Compile and Install notepadqq on Fedora 25 with QT 5.7
2. Start notepadqq, sluggishness will persist from startup time to opening file

**Please tell us about your environment:**
Fedora 25 x64, notepadqq 1.0.1 (also tried on old notepadqq 0.5x on sea's devel packages repo, same behaviour)

How do I turn on debugging? tried to run from terminal, no error message or anything.
passing argument to notepadqq (such as -v) will works, but immediately followed by segmentation fault.

Same version works just fine in Ubuntu install.

**Comment by JuBan1** [comment]
We're working on big improvements on the editor that hopefully alleviate performance issues. Either way, the changes are significant enough that investigating slowness right now would be a waste of time. So bear with us for a while and hopefully the next big update will fix that.

But for the record, what CPU do you have?

> passing argument to notepadqq (such as -v) will works, but immediately followed by segmentation fault.

What's the command, specifically? `notepadqq -v` should definitely not segfault.

**Comment by aryasenna** [comment]
That's a good news to hear. I tried a bunch editor and I guess I just got accustomed with Notepad++, and only qq fit the bills. The weird thing is in Ubuntu installation, it runs butter smooth. I don't have that kind of sluggishness on other program (heck even MATLAB is fast), so I suspect this is some incompatibility issues.

CPU is Intel Core i7-4710MQ (Haswell I think)

Regarding the segfault, yes every command except -h, -v included.
![image](https://cloud.githubusercontent.com/assets/5351348/23881913/c197925c-085d-11e7-8d73-a8f319524ca2.png)

Here is the backtrace:

> {   "signal": 11
,   "executable": "/usr/libexec/notepadqq/notepadqq-bin"
,   "only_crash_thread": true
,   "stacktrace":
      [ {   "crash_thread": true
        ,   "frames":
              [ {   "address": 140439971311501
                ,   "build_id": "1bbeb7c5f441d0feab5174db55aa2f976d83a8b8"
                ,   "build_id_offset": 2559885
                ,   "function_name": "QObject::disconnect(QObject const*, char const*, QObject const*, char const*)"
                ,   "file_name": "/usr/lib64/libQt5Core.so.5.7.1"
                }
              , {   "address": 140439600558000
                ,   "build_id": "c2713ad8d4756ecf9c1fcdfad65625deee761482"
                ,   "build_id_offset": 167856
                ,   "function_name": "QDBusConnectionPrivate::closeConnection()"
                ,   "file_name": "/usr/lib64/libQt5DBus.so.5.7.1"
                }
              , {   "address": 140439600478290
                ,   "build_id": "c2713ad8d4756ecf9c1fcdfad65625deee761482"
                ,   "build_id_offset": 88146
                ,   "function_name": "QDBusConnectionManager::run()"
                ,   "file_name": "/usr/lib64/libQt5DBus.so.5.7.1"
                }
              , {   "address": 140439969434058
                ,   "build_id": "1bbeb7c5f441d0feab5174db55aa2f976d83a8b8"
                ,   "build_id_offset": 682442
                ,   "function_name": "QThreadPrivate::start(void*)"
                ,   "file_name": "/usr/lib64/libQt5Core.so.5.7.1"
                }
              , {   "address": 140439963891402
                ,   "build_id": "b1a00278dd68288c9fd6692f7a2050970d62a1ba"
                ,   "build_id_offset": 30410
                ,   "function_name": "start_thread"
                ,   "file_name": "/usr/lib64/libpthread-2.24.so"
                }
              , {   "address": 140439951908735
                ,   "build_id": "1bd952e87fc457d08acfdc6e085c2429fd55deab"
                ,   "build_id_offset": 1081215
                ,   "function_name": "__clone"
                ,   "file_name": "/usr/lib64/libc-2.24.so"
                } ]
        } ]
}

Running on kernel 4.9.13-201.fc25.x86_64

**Comment by devhen** [comment]
FWIW, I'm running notepadqq on Fedora 25 and it is very fast and doesn't have the issues you describe. However, I'm compiling notepadqq from the git sources.

This is what I do:

`git clone https://github.com/notepadqq/notepadqq.git
cd notepadqq
./configure --prefix /opt/notepadqq
make
sudo make install`

**Comment by aryasenna** [comment]
I am also compiling from latest stable git source. 
Looks like this is an isolated case but I need to know what's the cause so I can fix it.

Tried opening the .pro file in QT Creator, run in debug mode, but not helpful error either, just sluggish.

**Comment by aryasenna** [comment]
I run line-by-line breakpoints to see what operation took second to complete.
apparently executing [this line](https://github.com/notepadqq/notepadqq/blob/master/src/ui/EditorNS/editor.cpp#L51)

`m_webView->setUrl(url);`

took almost complete 3 seconds.

Tried to un-comment line 55-56, to replace line 51 since the comment says it supposed to give performance improvement, unfortunately no effect.
Digging further brought me to [this QTWebView namespace declaration](https://github.com/notepadqq/notepadqq/blob/master/src/ui/EditorNS/customqwebview.cpp#L8)

```
...
namespace EditorNS
{

  CustomQWebView::CustomQWebView(QWidget *parent) :
-->       QWebView(parent)
    {
    }
...
```
Line takes 2-3 seconds to complete. I wonder if something is wrong with my QWebView installation?
I have tried to reinstall qt5-qtwebview and qt5-qtwebkit, still no effect.

FWIW I have the Fedora repo Qt5.7

@devhen are you running the default gnome desktop?

**Comment by aryasenna** [comment]
Aha, found the fix, compiling with latest version of Qt 5.8 + this QtWebKit package: https://github.com/annulen/webkit/releases/tag/qtwebkit-tp5 fixes the problem!

You need the latter since QtWebKit is deprecated and is to be replaced by QtWebEngine, it's not there in the default installation.

Also you need to adjust the ./configure to match your Qt path of course.
Issues is fixed, and I'll close it.

**Comment by aryasenna** [comment]
Reopened as I'd like to hear what the devs/others think about this QWebView weirdness.

**Comment by danieleds** [comment]
You might be happy to know that we're switching to QtWebEngine soon :)
See webengine-beta branch.

**Comment by aryasenna** [comment]
@danieleds I can confirm the binary compiled from the `webbengine-beta` branch + QT 5.7 does not exhibit sluggishness, and I got my native skinning back.

Yes, you're right I'm one happy camper here. Closed the issue for good. :)

**Comment by Teklad** [comment]
One last note.... just be wary that this branch is in testing... So some 
features might work, and there may be bugs present that could cause data 
loss.

With that said, as long as you save often, there shouldn't be any REAL 
issues. I hope you enjoy the improvements.

**Comment by aryasenna** [comment]
@teklad thanks for the heads-up. I'm aware it has beta in its name. Saw the discussions about it too so I know this is work in progress.
