### ISSUE TITLE
QtWebEngine:  Asynchronous data retrieval proposals.

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#400]
We're now at a point where we can start doing asynchronous data calls... so I'm going to lay out a few options we have at our disposal as to how we can implement this cleanly.

Option 1 - Template functions:
* Pros:
  * Easiest to implement out of the three.
  * Ability to use the "auto" keyword when defining lambda rather than using a special typedef or convoluted type.
  * Probably less runtime overhead than std::function<TYPE>
* Cons:
  * As everyone is aware, defining template functions outside of the header file is a lot of headache, so we're either going to have to redefine functions that use it in the header file... or do some really icky black magic.
  * Looks quite a bit messier where it's defined.

Option 2 - std::function:
* Pros:
  * Stricter typing... we only have to add the parameters we need, and not much else.
  * Guaranteed to throw an error if we try to cram the wrong type into the Functor parameter field.
* Cons:
  * Will need a typedef or use a very long std::function<void(QVariant)> m = SomeLambda when defining our lambda.
  * There's some runtime overhead involved with std::function, to my understanding.

Option 3 - Good ole void* function pointer:
* Pros:
  * Probably pretty easy to implement.
  * Auto keyword might be available depending on how the compiler handles it.
* Cons:
  * Lambdas CAN NOT capture the scope using this method, which is very limiting.
  

I think that pretty much covers all the bases... these are the three methods we have available for callbacks at the moment... and none of which are going to be "fun" to work with... but asynchronous programming just isn't fun in the first place, lol.

I'm leaning towards option 1 and 2... in that order... though I'm not sure how I feel about having so many functions defined in the header. :\  

Option two looks cleaner where it's defined and isn't insanely difficult to implement, but it makes code elsewhere slightly convoluted.... not too bad though.  However, there is the overhead involved (I'm not sure how much overhead we're talking here).

I'll leave it up to you two @danieleds & @Juban1

**Comment by danieleds** [comment]
I like option 2 hands down. Even without typedefs.

> but it makes code elsewhere slightly convoluted.... not too bad though.

Can you show an example of how you imagine it?

**Comment by JuBan1** [comment]
If we could use `QWebEnginePage::runJavaScript` all the callback stuff would be handled by Qt.

**Comment by Teklad** [comment]
That's the idea but we don't want runJavascript leaking outside of the editor class if we can help it... The callbacks are meant to be used by main window... Preferences, etc.

⁣Sent from BlueMail ​

**Comment by JuBan1** [comment]
Okay, I think I got it. So I'd say go for templates

    template <typename T>
    void getGetValueFunction(T callback) {
        runJavaScript("return getValue()", [&](const QVariant& result){ callback(result.toString(); });
    }

That gives us typesafety by restricing callbacks to anything taking a QString (in this case) and avoids std::function's overhead.

**Comment by Teklad** [comment]
@danieleds, the implementation in std::function looks like this:

In editor.h:
```cpp
typedef std::function<void(const QVariant&)> Callback;
```

In editor.cpp:
```cpp
    QVariant Editor::sendMessageWithResult(const QString &msg, const QVariant &data, const Callback& callback)
    {
        qDebug() << "Handling: " << msg;
        if(!callback) { 
            qDebug() << "Using blocking call.";
            if (m_processLoop.isRunning())
                throw std::runtime_error("m_processLoop must never be running at this point. Did this function get called from another thread?");

            emit m_jsProxy->sendMsg(jsStringEscape(msg), data);
            m_processLoop.exec();
            return m_jsProxy->getResult();
        }
        qDebug() << "Using callback method.";
        QString cleanMsg = jsStringEscape(msg);
        QString cleanData = QString(data.toJsonDocument().toJson());
        if (cleanData.isEmpty())
            cleanData = "''";
        QString msgData = QString("UiDriver.messageReceived('%1',%2)").arg(cleanMsg, cleanData);
        qDebug() << msgData;
        m_webView->page()->runJavaScript(msgData, callback);
        return QVariant();
    }

    QStringList Editor::getSelectedTexts(const Callback& callback)
    {
        return sendMessageWithResult("C_FUN_GET_SELECTIONS_TEXT", 0, callback).toStringList();
    }

```

In mainwindow.cpp:
```cpp
void MainWindow::on_actionSearch_triggered()
{
    if (!m_frmSearchReplace) {
        instantiateFrmSearchReplace();
    }
    EditorNS::Callback cb = [&](const QVariant& v) {
        QStringList sel = v.toStringList();
        if (sel.length() > 0 && sel[0].length() > 0) {
            m_frmSearchReplace->setSearchText(sel[0]);
        }
    };
    currentEditor()->getSelectedTexts(cb);

    m_frmSearchReplace->show(frmSearchReplace::TabSearch);
    m_frmSearchReplace->activateWindow();
}
```

This was what I had partially implemented prior to switching gears and fixing up some of the editor signals.  A few things to note about the previous:
* The auto keyword just won't work (I tried... it just doesn't)... so EditorNS::Callback is a shortcut typedef to save a few keys and some line space.
* Currently, we are forced to return a value regardless whether we use the callback variant or not... it might be better to have a [Callback] version of the get functions... or just try to go full out with the async and replace them entirely... but I'd like to try and avoid that for the time being until we're sure async is going to behave.

This method and the template method will both work pretty much the same on the backend... it really all comes down to runtime overhead(std::function) vs compiler overhead(templates).

There's a few interesting magic tricks you can do with std::function to keep it from having as much overhead(i.e.) passing a reference only to what we're going to interact with in the lambda... as an example:
```cpp
EditorNS::Callback cb = [&m_potato] () {};
```

The goal is to keep the capture under 16 bytes to avoid heap allocation... which isn't very hard when passing by reference... and only passing the absolute necessary:
http://www.boost.org/doc/libs/1_45_0/doc/html/function/faq.html#id1284915
http://www.boost.org/doc/libs/1_45_0/doc/html/function/misc.html#id1285061

These are relevant to std::function.

I just want to make sure we're all on the same page as what we're doing.  I tend to be a little over-zealous when it comes to performance stuff.  I don't think the std::function overhead will be noticeable unless we end up with some call that uses it heavily, though.

**Comment by danieleds** [comment]
Okay... Not so sure anymore... If you could provide an example of the template implementation, it would be nice to compare.

**Comment by Teklad** [comment]
Alright, here we go:

In editor.h:
```cpp
public:
        template<typename T>
        void getSelections(T callback)
        {
            sendMessageWithCallback("C_FUN_GET_SELECTIONS", callback);
        }
private:
        template<typename T>
        void sendMessageWithCallback(const QString& msg, const QVariant &data, T callback) {
            QString jsonData = QJsonDocument::fromVariant(data).toJson();
            QString jsMsg = QString("UiDriver.messageReceived('%1',%2)").arg(msg).arg(jsonData);
            m_webView->page()->runJavaScript(jsMsg, callback);
        }

        template<typename T>
        void sendMessageWithCallback(const QString& msg, T callback) {
            QString jsMsg = QString("UiDriver.messageReceived('%1',%2)").arg(msg).arg(0);
            m_webView->page()->runJavaScript(jsMsg, callback);
        }
```

In Search/frmsearchreplace.cpp (As a sample):
```cpp
void frmSearchReplace::on_searchStringEdited(const QString &/*text*/)
{
    NqqSettings& s = NqqSettings::getInstance();

    if (s.Search.getSearchAsIType()) {
        if (ui->actionFind->isChecked()) {
            currentEditor()->getSelections( [&](QVariant v) {

                Editor *editor = currentEditor();
                // Conversion helper function... just to show template method.
                QList<Editor::Selection> selections = editor->convertToSelections(v);
                if (selections.length() > 0) {
                    qDebug() << "Test" << selections[0].to.line;
                    editor->setCursorPosition(
                        std::min(selections[0].from, selections[0].to));
                }
                findFromUI(true);

            });
        }
    }
}
```

Notice the ability to inline the function directly in the getSelections() call... which is kinda nice.  Both methods of course have pros/cons... but either one will get the job done at any rate.

**Comment by danieleds** [comment]
Okay, let's go with templates.

I don't understand one thing, why whould you use QVariant in getSelections' callback instead of directly providing the converted values, e.g. why this:

```c++
currentEditor()->getSelections( [&](QVariant v) {
  ...
});
```

instead of this:

```c++
currentEditor()->getSelections( [&](QList<EditorSelection> v) {
  ...
});
```

**Comment by Teklad** [comment]
It was just a quick and dirty example... we shouldn't have any problem 
doing the conversion within getSelections itself.  I had to head to bed 
before I could finish it all the way. :P

**Comment by Teklad** [comment]
Didn't realize we had so much dead code lying around... There's a few functions that are never referenced (i.e. the old Run menu actions).  Just kinda cleaning those up as I find them while implementing this, lol.

**Comment by Teklad** [comment]
Closing in favor of PR #402
