### ISSUE TITLE
Feature Request: Multiple selection while searching in files!

### ISSUE THREAD

**Issue by guekho64** [notepadqq/notepadqq#404]
I think the title it's quite self-expressive by its own, but anyways I'll explain my 'Feature Request'

When you search in files (& Directories), you end up with a clickable list of all ocurrencies found, BUT, I'd like that, if possible, you could add some way to select those lines, copy & paste them in the editor itself.

I mean, it should be possible since Nqq actually highlights those characters in yellow:

[![Captura de pantalla de 2017-03-20 16:15:12.png](https://s15.postimg.org/i5uq9bjbv/Captura_de_pantalla_de_2017_03_20_16_15_12.png)](https://postimg.org/image/x1t9gwuqf/)

Wouldn't it be great to had this feature?

P.S: Such a strange number for my issue...(#404) LOL?

Edit: I'm talking about selecting the alredy highlighted text of the find result.

**Comment by JuBan1** [comment]
Not sure I understand.

Do you mean you want to be able to right-click on the items in the clickable list and have a "copy" option; and be able to select more than one item on that list at once?

Or that you can click on several items in the clickable list and the corresponding parts in the editor would be selected?

**Comment by danieleds** [comment]
You mean like, I double-click the result line and the yellow portion gets selected in the editor?

(Ahah yeah nice issue number :P)

**Comment by guekho64** [comment]
Almost, but nope.

I'll try to describe it:

1- Do a File search (Anything)
2- Results appear highlighted in yellow
3- Click the recently added "Copy content" button (That button should copy all yellow-highlighted text into clipboard)
4- Do a Ctrl+V in any editor to paste the content
5- Enjoy!

**Comment by danieleds** [comment]
Got it. That may be interesting to include in #406 as an "advanced" button

**Comment by JuBan1** [comment]
I've added this as a feature to #406. But I can't yet give an ETA as to when it'll be in master for people to use.

![image](http://i.imgur.com/eblrhIo.png) 

You can pick which search results to copy, then use that option.

**Comment by guekho64** [comment]
Can't wait to test It!

It'll be very useful (Like in my case) when searching for Strings in many config files to extract text from them.

**Comment by JohnRenfro2016** [comment]
It worked great! I now use Notepaddqq with Kate.
