### ISSUE TITLE
QWebEngine: Resizing window is sluggish

### ISSUE THREAD

**Issue by JuBan1** [notepadqq/notepadqq#405]
Resizing the Nqq windows under WebKit is buttery smooth for me. But resizing under WebEngine is not smooth at all probably because the WebView's resize operation takes too long.

Here's how it looks like mid-drag:

![image](http://i.imgur.com/UnpRgTA.png)

I looked around a bit and a possible solution is to handle the resize event on our own. During a resizing event, instead of letting the WebView resize, we just rescale it. When the resizing event ends, we resize WebView once.

**Comment by Teklad** [comment]
I disable update contents while resizing so I never noticed this. Lol

**Comment by Teklad** [comment]
Okay, so this issue is due to OpenGL being behind the scenes rendering QWebEngine.  Resizing an OpenGL context is an extremely expensive operation (and verified slow when using the Nvidia drivers).  Also, this behavior seems to be consistent with my experience running Chrome as my web browser, so until it's fixed in upstream we'll just have to deal with it.

**Comment by danieleds** [comment]
https://bugreports.qt.io/browse/QTBUG-58324

**Comment by danieleds** [comment]
On the anniversary of this issue...

> I looked around a bit and a possible solution is to handle the resize event on our own. During a resizing event, instead of letting the WebView resize, we just rescale it. When the resizing event ends, we resize WebView once.

This would be weird but still better than a white empty border.

Or wait, some cool design is coming to my mind.

Imagine that, while resizing, we rescale the WebView but we also make it opaque and show the number of visible text rows/columns over it. Something like this 2-minutes mockup, but better:

![notepadqq2](https://user-images.githubusercontent.com/402652/37715300-f818f5e4-2d1b-11e8-890b-6943e686be9f.png)

This would remove the resize ugliness AND be useful, by giving real-time information on the number of rows and columns.

**Comment by Teklad** [comment]
@danieleds I just looked at the new webengine branch and its coming along nicely... I'll look into getting this done for the branch since I FINALLY have some free time.

**Comment by danieleds** [comment]
Perfect!

The webengine branch still has its problems... but at least it's working without any major modification.
Right now I'm struggling with some crashes, a weird problem on startup and another weirdness with high-frequency messages. Your feedback on these issues would be useful too.

**Comment by Teklad** [comment]
I believe I remember having a similar issue with crashes (especially when exiting notepadqq).  I think it has something to do with messages getting queued up but never processed iirc.  Let me dig through my massive pile of webs and see if I can figure out.

**Comment by Teklad** [comment]
So to update on this... I've looked into it a bit.  Basically its probably "do-able", but due to how QWebEngine is in its current state we'd be relying on some rather undocumented back-end QT things that could break between versions to get it done.  

I'm more than happy to give it a go anyways if you want but this definitely needs to be fixed upstream for any kind of permanent relief.  Unfortunately the issue was reported upstream over a year ago without any fix in sight currently.

**Comment by JuBan1** [comment]
I think backend shenanigans like that ought to be avoided. Especially with QWebEngine since it's a somewhat newer part of Qt so chances are that its internals have changed not too long ago.

We can looks for a nice visual to hide the sluggish resize once the webengine branch is actually working. That should take priority.

**Comment by danieleds** [comment]
I totally agree with JuBan

**Comment by echostorm** [comment]
Just wondering if this ever got solved by now? since im facing same problem with webengine with two of my browser projects any proper solution for this with Qt 5.11...

**Comment by Teklad** [comment]
Just a note, though hopefully unimportant in the coming months... this bug has been fixed in upstream:
https://bugreports.qt.io/browse/QTBUG-58324

**Comment by danieleds** [comment]
Indeed this seems to be fixed when using the most recent version of Qt. Closing.
