### ISSUE TITLE
Advanced Search & Replace design mockup

### ISSUE THREAD

**Issue by JuBan1** [notepadqq/notepadqq#406]
I've wanted to do this for a long time but now I've finally finished the mockup.

The idea is to implement a Search & Replace dialog more akin to Qt Creator's and roughly as powerful. I've not code yet but I've put together a shoddy mockup of the interface.

Here's a full shot:

![full image](http://i.imgur.com/ooPnzwr.png)

With expanded search history:

![search history](http://i.imgur.com/CWghuhV.png)

With expanded scope combobox:

![](http://i.imgur.com/Ov31nc3.png)

When conducting a search (or picking one from the search history), the bottom part is replaced by the search results. I intend to slightly modify them as well. For now they're the same as we have right now:

![](http://i.imgur.com/HMDUz9Y.png)

Clicking the "Replace Options" button in the header bar will toggle a bar for replace actions:

![](http://i.imgur.com/sXzoxnz.png)

The UI is just hacked together at the moment, hence a few visual inconsistencies.

Thoughts and suggestions? Before I start coding I want to get the UI right and make we're all happy with it.

**Comment by JuBan1** [comment]
PS: some more info:

* This is intended to replace the "Find in files..." search option we have right now. The normal search and replace dialog is still useful because it's quicker to use than this one. (Like QtCreator does it too).

* Search history is not meant to be saved across restarts. Will just be wiped at exit.

* The "<" and ">" buttons are "Find Previous" and "Find Next", respectively.

**Comment by JuBan1** [comment]
Obligatory edit for spamming you guys with messages: @Teklad @danieleds

**Comment by danieleds** [comment]
Just one quick comment: it looks awesome.

**Comment by Teklad** [comment]
I thought this email said ham. :(.  Looks very good though!
