### ISSUE TITLE
^F Find ENTER does not search for the currently selected text

### ISSUE THREAD

**Issue by severach** [notepadqq/notepadqq#417]
```
[x] bug report
```

Perform any search so that ^F remembers it.
Highlight a different search word, ^F, ENTER.

**Current behavior**
^F shows the highlighted word but ENTER reverts to the previous search word.

**Expected behavior**
^F ENTER should not revert to the previous search and search for the currently highlighted text.

**Please tell us about your environment:**
% pacman -Q linux
linux 4.10.6-1
% pacman -Q qt5-tools 
qt5-tools 5.8.0-1
% notepadqq --version
[Notepadqq 1.0.1](https://aur.archlinux.org/packages/notepadqq-git/)

**Comment by Scarabol** [comment]
The issue seems only to occur, if the search text was not searched before.
