### ISSUE TITLE
Where are newly created but not saved files stored?

### ISSUE THREAD

**Issue by tsoernes** [notepadqq/notepadqq#418]
Say I open a couple of tabs and paste some text in them, pull the power cord of my computer and boot up. Is it possible to recover my files/tabs? Are they temporarily stored somewhere? The Windows version of the software seems a bit more resilient to that kind of a thing, but with the Linux version the files are not automatically reopened after a hard shutdown. Maybe my memory serves me wrong.

Thank you

**Comment by JuBan1** [comment]
Hi,

Tabs are saved on every exit (if the option is turned on in the settings menu). If you just pulled the power plug you would lose all changes made since Nqq last exited. The save location is usually at ~/.config/Notepadqq/tabCache.

**Comment by tsoernes** [comment]
Can I request that tabs are saved on change or set time intervals?
