### ISSUE TITLE
Not so much an issue as a question. Is the CIA vulnerability an issue in notepadqq?

### ISSUE THREAD

**Issue by UNIcodeX** [notepadqq/notepadqq#419]
It's in the title. I'm assuming this is not an issue, but doing due diligence. Thanks!

**Comment by JuBan1** [comment]
Nope. N++ and Nqq share no code at all. N++'s vulnerability doesn't concern us.

I'd feel flattered if the CIA considered us important enough to hax us.

**Comment by UNIcodeX** [comment]
OK. Lol! Thanks!

**Comment by Teklad** [comment]
@danieleds this one can be closed. :)
