### ISSUE TITLE
Title bar has wrong tab title after launch

### ISSUE THREAD

**Issue by severach** [notepadqq/notepadqq#421]
```
[x] bug report
```

File Close All.
File Exit, close notepadqq
Launch notepadqq. All that should be showing is a single blank tab "new 1".
File Open any text file. We'll call it "foo.txt". Do not make changes.
File New, type some random text in the new tab which should be in the second tab position. Do not save to file. This text will save and reload automatically.
Select the first tab for "foo.txt".
File Exit, close notepadqq
Launch notepadqq
The selected tab at launch is "foo.txt"

**Current behavior**
The title bar shows "new 1 - Notepadqq". The tab of this name is not selected.

**Expected behavior**
The title bar shows "foo.txt (/home/bar/) - Notepadqq".

````
% pacman -Q linux qt5-base notepadqq-git                           :(
linux 4.10.10-1
qt5-base 5.8.0-7
notepadqq-git 1.0.1.r33.g566cec2-1
````

**Comment by qcerasmus** [comment]
Hi,

Just to inform everyone so there is duplicate effort that I'm about to submit a pull request for this.
