### ISSUE TITLE
Extensions downloaded from one repository

### ISSUE THREAD

**Issue by qcerasmus** [notepadqq/notepadqq#423]
I'm submitting a
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
You can select a compiled nqqext file to install an extension. The problem is where do you even start looking for extensions?

**Expected behavior**
When clicking on "Install Extension..." a pop-up should open that lists a bunch of extensions to choose from.
It could display the extension name, extension description and size maybe?
You can then select multiple extensions and install them all at once.

**Comment by JuBan1** [comment]
I've never really taken a look at them but I don't think Extensions are actually functional. At the very least they're very outdated. I don't think anyone did any work on them since before I started contributing in August last year.

But you're right, it'd be great to have a list of available extensions once there actually are any. The whole system probably needs to be overhauled but that only makes sense when we're done reworking the text engine (which is currently in progress).

**Comment by qcerasmus** [comment]
I've written 2 extensions over the weekend so I can confirm there is limited functionality.
I'll see how much I can contribute to reworking the extensions if that'd be ok?

**Comment by JuBan1** [comment]
Sure, contributions are appreciated!

If you want to make bigger changes it might be a good idea to open an issue or PR to explain what you're going to change. That way we're all on the same page.

Just as a heads-up, we're working on changing a decent bit of the internals. So if you're reworking extensions to access things like reading text from documents, it might have to be fixed once we're done with it. Though we don't have any ETA. Could be weeks, could be months.

**Comment by qcerasmus** [comment]
Awesome, I'll create a project soon to keep everyone up to date.

**Comment by jawz101** [comment]
Are there any extensions out there?  An arbitrary "supports node.js extensions" doesn't really point me in a direction on how to get them.

**Comment by JuBan1** [comment]
@jawz101 Barely any. @qcerasmus has some in his Github at https://github.com/qcerasmus/notepadqq-extensions and that's about all I know.
