### ISSUE TITLE
What to do about the editor/tab situation?

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#425]
The way we're doing our tabs now creates a new instance of the editor with every new tab.  While this was fine when we were using QWebKit... QWebEngine is quite a bit heavier in terms of memory usage.

The question is... should we start work on this in the webengine-beta branch.... or do we push that to master and start a new branch for these changes?

**Comment by JuBan1** [comment]
Usability and fast response is more important than memory. So unless switching a WebView's page is as fast as simply switching WebViews I think we should leave it like that.

**Comment by Teklad** [comment]
From what I understand it should be faster... and it will completely eliminate the remaining seizure flashes. :)

**Comment by JuBan1** [comment]
Sounds juicy. In that case I'd say we stick to the beta branch for a little longer. Master is pulled into some repositories and delivered to users. Let's get it into good shape.

**Comment by Teklad** [comment]
I'll write up a rough draft and submit a PR on it soon.  There's a few roadblocks I see in my brain regarding implementation.  It's a fairly large change compared to how we're doing things now... so you'd have a setup more like this:

In each view you'd have:
* QTabBar (NOT QTabWidget)
* QWebEngine/Editor
* "Some container that holds the pages (not sure where this would go yet)"

Clicking each tab will essentially just change to the assigned page... so in all reality, we'd need quite literally one Editor/QWebEngine per view...

Now the real kicker here is... how the (insert naughty word here) do we interface with the current editor model without tearing it down completely.  From what I can tell this isn't really going to be possible... mainly due the Editor would need to be aware of the current page rather than the entire QWebEngine like it is now.  

Essentially it's going to cut our class usage down to almost nothing, but its probably a larger overall project than QWebEngine itself.

**Comment by danieleds** [comment]
We also have to think about how "move to the other view" would be implemented

**Comment by Teklad** [comment]
I think the best way to do that would be to pass the QWebEnginePage to the other view and destroy the old tab... then create a new one in the other view with the same data.  Theoretically speaking it should be pretty clean... but that's just theory. :)

**Comment by JuBan1** [comment]
Hm, why the need for a large change? 

Can't we just have one WebView per SplitView widget, then give each Editor their own WebPage (as a simple member variable). On changing tab we update the corresponding WebView's page. We need something like Editor anyways since there's other data stored as well (tab name, position, whatnot). Why reduce it to just one Editor? What's going to take its place?

**Comment by Teklad** [comment]
I didn't really explain that well... the way you described it is more or less how its gonna be done.  Either way you're looking at a very large shift of how things are done right this minute.  Depending on your hardware performance is gonna be a crap-shoot with a lot of tabs open for some people how it's designed now though. :p

**Comment by Teklad** [comment]
Actually, if we store the pages properly... we could finally support concurrent viewing of the same page in split views I think.... assuming pages work in this manner.

**Comment by JuBan1** [comment]
Sadly not. I've looked into that a while ago and each WebPage can only be shown in a single WebView at a time.

Simultaneous views will probably need to be made by creating two WebPages and synchronizing their input with each other. The bad part: this sounds very prone to bugs. The good part: it can probably be implemented inside Editor with almost no change to our interfaces.

But for now let's focus on the other things.
