### ISSUE TITLE
Submit to distros

### ISSUE THREAD

**Issue by rugk** [notepadqq/notepadqq#435]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

Could you submit this project to big distros for inclusion in their packages? Currently it can only easily be used on Ubuntu. So maybe support it to Debian, Fedora and so on…

**Comment by Teklad** [comment]
Actually, Notepadqq is starting to be included on some popular distros already (Arch Linux, OpenSUSE) without any intervention on our end.  At this point its moreso a matter of when a distribution deems us worthy of inclusion.

We have a lot of big projects underway here reagarding code stability and are working toward making Nqq better all around.

**Comment by danieleds** [comment]
In addition, there already is a pending RFP for Debian :)
