### ISSUE TITLE
Snap & flatpaks

### ISSUE THREAD

**Issue by rugk** [notepadqq/notepadqq#436]
What do you think about providing snaps and flatpak for easy installation on all Linux distro's with support for it?

**Comment by danieleds** [comment]
That would be great!
We need someone to write them though :) Do you have any experience with snap?

**Comment by rugk** [comment]
No, unfortunately not.

**Comment by ajyotirmay** [comment]
@danieleds I can look into it.

**Comment by danieleds** [comment]
@ajyotirmay great! Do you need something to get started?

**Comment by ajyotirmay** [comment]
@danieleds not really. I've been kind of busy lately, so it will take me some time to go through the documentation and start working on it. I'll figure it out :-)

**Comment by BearzRobotics** [comment]
Has there been any progress on this front?

**Comment by cimm** [comment]
I found notepadqq in the [Snapcraft Stor](https://snapcraft.io/notepadqq)e, it's even featured right now (that's how I learned about this project). So I guess there has been progress on this front indeed. 😉

**Comment by cimm** [comment]
One of the problems with snaps IMHO: there is no way to verify if indeed the snap is sanctioned by the official team. They also shouldn't have namesquatted the `notepadqq` namespace. The snap documentation recommends to  use `notepadqq-username` for your snap if it isn't the "official" one. You might wanna get in touch with the packager to see if it can't be contributed back to the project?

**Comment by danieleds** [comment]
I've not been able to find any publisher's contact information yet. I've seen I can submit a name dispute  through the Canonical website. Before doing that, however, I'd like to have a working snap in our hands, possibly from the author of the package which is online right now.

**Comment by danieleds** [comment]
Finally found the repo for that snap! https://github.com/fefeh1/notepadqq

I've filed an issue. Currently waiting for a reply.

**Comment by danieleds** [comment]
We've got the ownership on the name. An official Snap package is finally available!

**Comment by scx** [comment]
Flatpak package: https://github.com/notepadqq/notepadqq/issues/668
