### ISSUE TITLE
QT5.8 

### ISSUE THREAD

**Issue by barnycloud** [notepadqq/notepadqq#442]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

**Comment by danieleds** [comment]
Closing because it is an empty issue.
