### ISSUE TITLE
Jumpy behavior with mouse scrolling

### ISSUE THREAD

**Issue by samikrc** [notepadqq/notepadqq#461]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The editor text seems to jump to the end or to the top when I am trying to scroll down or up respectively with mouse. Sometimes I have also noticed the text scroll back and forth, or repeatedly coming back to the same position even though I am scrolling down or up.

**Expected behavior**
Smooth scrolling of text with mouse.

**Minimal reproduction of the problem with instructions**
This works for me:
- Open a document which can be scrolled through a few pages
- Set the cursor down somewhere in the screen
- Now start scrolling down with mouse
- The page might move forward to the bottom (can't reproduce always)

**Please tell us about your environment:**
Debian Jesse, Qt 5.3.2, npqq 1.0.1

**Comment by samikrc** [comment]
Adding a [screen capture](https://drive.google.com/file/d/0B1EuN_O-nek1aTczMW1Ta2toUGs/view?usp=sharing) of the jumpy behavior described above. I am trying to scroll down first couple of times, followed by trying to scroll up couple of times.

**Comment by JuBan1** [comment]
Just to give you a heads-up: this is probably QWebKit's fault since it pretty much handles all the scrolling. Bad news is it's very hard to fix because of that. Good news is we've plans to move away from WebKit eventually.

**Comment by samikrc** [comment]
Would be looking forward to it. This irks me everytime I try using N++ on my Linux box.

**Comment by samikrc** [comment]
I tried upgrading to Qt 5.10.1 - got it installed at /opt/Qt. I know this is not an npqq-specific issue, but how do I make npqq use it. Even after installing, when I open npqq, it still gives me a warning saying my version of Qt is old (5.3.2). Is there some environment variables that I need to set? Any documentation?

Thanks for any pointers.

**Comment by JuBan1** [comment]
Nqq only looks for Qt libraries in certain paths. For Qt 5.10 the search path looks like this: `/opt/Qt/5.10/gcc_64/lib`. Can you see whether this path exists for you?

You can directly tell Nqq to use a different set of Qt libraries by starting it as

    LD_LIBRARY_PATH="XYZ:${LD_LIBRARY_PATH}" notepadqq

Where XYZ is the path to the Qt libraries of your Qt version. (That's generally the `lib` folder.)

**Comment by samikrc** [comment]
Thanks for your response. Yes, that path exists, and I could run npqq with new Qt. This problem also seem to have been resolved: in limited testing, I did not observe this issue.

Do you by any chance know how I can set this Qt as the default Qt version for the system so that I don't have to use that large command line for starting npqq? I have looked at Qt documentation and searched on the web, but nothing concrete has come up. Thanks much.

**Comment by JuBan1** [comment]
Well, you can modify the .desktop file. It's probably at `/usr/local/share/applications/notepadqq.desktop`. When you open it with a text editor you can change the line `Exec=notepadqq %U` to `Exec=env LD_LIBRARY_PATH="XYZ:${LD_LIBRARY_PATH}" notepadqq %U`. After that -and perhaps a restart- it should always use those libraries.

**Comment by Teklad** [comment]
Depending on your desktop environment you should be able to copy that to ~/.local/share/applications/ and modify it there as to avoid messing with a system file if you like.

**Comment by samikrc** [comment]
Thanks - worked. Closing.
