### ISSUE TITLE
Ubuntu crashes when exit from command line

### ISSUE THREAD

**Issue by jfoclpf** [notepadqq/notepadqq#463]
**I'm submitting a ...**  
```
[X] bug report 

```

**Current behavior**

When open notepadqq through terminal

`notepadqq ./filnename`

and then exiting in terminal with `CTRL+Z`

All Ubuntu crashes. Ubuntu simply crashes, the entire OS. 

**Expected behavior**

I know one should not CTRL+Z when opened from the terminal, but why not another session?

**Minimal reproduction of the problem with instructions**

1. Open terminal
2. Open a file: `notepadqq ./filnename`
3. In that same terminal session press CTRL+Z

**Please tell us about your environment:**

Ubuntu, last notepadqq version

**Comment by JuBan1** [comment]
Can't reproduce with freshly installed Ubuntu 17.04. I can `CTRL+Z` and `fg` and Ubuntu and Notepadqq both work.

**Comment by jfoclpf** [comment]
What the latest version of Notepadqq?
I have v0.53.0

I have Ubuntu 15.10

**Comment by JuBan1** [comment]
1.0.1-3 is latest. But the Ubuntu ppa only contains 0.53.0 for Ubuntu 15.10.

You should think about updating to at least 16.04. Not just for Notepadqq but because 15.10 is out of support since June 2016.

**Comment by jfoclpf** [comment]
OK, I think I have this problem with other editors as well. You may close the issue.
Thank you
