### ISSUE TITLE
First click on any menu item draws it on the top of the screen MAC style

### ISSUE THREAD

**Issue by severach** [notepadqq/notepadqq#470]
````
[x] bug report
````
Run notepadqq, size the top down to expose the desktop above notepadqq, click any menu item (File, Edit, Search)

**Current behavior**
menu draws outside of the notepadqq window as a line across the top of the screen. Dismiss the menu and click again and now the menu is drawn as a box. Each menu item does the same thing independent of the others.

Reload notepadqq and the menu items will do it all over again.

For fun, hit Alt-F and right arrow across all the menu items.

**Expected behavior**
menu draws as a box first time and every time

**Please tell us about your environment:**
````
$ pacman -Q linux qt5-tools notepadqq-git
linux 4.12.6-1
qt5-tools 5.9.1-4
notepadqq-git 1.0.1.r54.g05f50bd-1
$ pacman -Q cinnamon nemo
cinnamon 3.4.4-1
nemo 3.4.6-1
````

**Comment by danieleds** [comment]
Seems to be fixed upstream
