### ISSUE TITLE
Version is missing from Continuous AppImage

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#476]
The git commit info is missing from the uploaded name at https://github.com/notepadqq/notepadqq/releases:

`notepadqq-.glibc2.14-x86_64.AppImage`

**Comment by darealshinji** [comment]
From the build log on Travis:
```
++sed 's|^v||'
++git describe
fatal: No annotated tags can describe 'ec2b6c83b2f19ed9d2395f8ea561b2c54f1ab656'.
However, there were unannotated tags: try --tags.
+VERSION=
```
Maybe that helps.

**Comment by danieleds** [comment]
I think this is the cause:
https://github.com/pypa/setuptools_scm/issues/93
