### ISSUE TITLE
FTP support

### ISSUE THREAD

**Issue by sirajuddin97** [notepadqq/notepadqq#479]
Is it somehow possible to upload files with FTP using Notepadqq? Or is there any plugin I can install? Just like Notepad++ has its own FTP manager.

**Comment by JuBan1** [comment]
We've nothing of the sort unfortunately.

I'm not even sure if the plugin system is powerful enough for a decent ftp plugin.

**Comment by sirajuddin97** [comment]
Hmm. Thanks for your reply.

**Comment by vlasvlasvlas** [comment]
also needing ftp support for working with sftp/ftp ssh connections / remote server
