### ISSUE TITLE
Extensions menu item

### ISSUE THREAD

**Issue by qcerasmus** [notepadqq/notepadqq#491]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When building and running the code from QT creator, I can get the extensions menu to show successfully, but if I open the built version via installing it from the repo I can't get the extensions menu to open at all.

I have checked and I have no changes locally. I also have the same version running (1.0.1).

**Expected behavior**
Extensions menu item should show when you add the 2 paths of nodejs and npm.

**Minimal reproduction of the problem with instructions**
Add the two paths in the compiled notepadqq and save it. Restart notepadqq and the menu item should show.

**Please tell us about your environment:**
Linux Mint.

**Comment by danieleds** [comment]
Thanks.
Could it be that it has been solved after the tagged release?
Does it work if you do a `git checkout v1.0.1` and then build again?

**Comment by qcerasmus** [comment]
Thanks,

It's reproducible now. Looks like I have to be more patient :)

**Comment by danieleds** [comment]
A new release will be out soon, hopefully :)
