### ISSUE TITLE
command line options?

### ISSUE THREAD

**Issue by ineuw** [notepadqq/notepadqq#493]
**I'm submitting a ...**  (check one with "x")
```
[ x ] feature request

Is there command line option to open a specific file? 

Linux Mint 18.2  32/64bit Qt 5.6.1, qq vesion 1.0.1

**Comment by danieleds** [comment]
Hi,
if you are using the PPA, you can open any file by

    notepadqq /path/to/file.txt

or

    nqq /path/to/file.txt

Is this what you need?

**Comment by ineuw** [comment]
Yes, and thank you!!!!
. . . .  and for those who are ignorant, the path and file name should be enclosed in quotes, even if the file name has no spaces. :-)
