### ISSUE TITLE
Ligature font support?

### ISSUE THREAD

**Issue by gamesbook** [notepadqq/notepadqq#497]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behaviour**
The font Fira Code does not display ligatures.

**Expected behavior**
The font Fira Code should display ligatures.

**Minimal reproduction of the problem with instructions**
![fira](https://user-images.githubusercontent.com/354027/31988408-4479a210-b96f-11e7-8dc3-ee5576f0939b.png)

**Please tell us about your environment:**
Ubuntu 14.04; Qt 5.2.1

**Comment by carlhen** [comment]
I just compiled the program and fira code's ligatures works :smile:

**Comment by JuBan1** [comment]
Seems to work now that we're using QtWebEngine.

![img](https://i.imgur.com/0kMmYKt.png)

I'll close this then.

**Comment by jdhalbert** [comment]
Did support for ligatures get dropped? Fira Code ligatures are not appearing for me running Ubuntu 18.04 LTS, notepadqq v.1.4.8, Qt v.5.5.1.

**Comment by dixDel** [comment]
Same here on Notepadqq v1.4.8 (Arch Linux): tried both Fira Code and JetBrains Mono. Ligatures work in other programs.
