### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by inukaze** [notepadqq/notepadqq#507]
Hi there, which file i should modify to make Spanish Localization ?

**Comment by JuBan1** [comment]
Hi, we've got a short write-up of how to translate: https://github.com/notepadqq/notepadqq/wiki/Translate-Notepadqq

**Comment by inukaze** [comment]
@JuBan1 Thanks for the link 

i already finish the first version of my spanish translation for notepadqq , but some text i can't translate : 
[![notepadqq_es_inukaze.png](https://s25.postimg.org/hnas1z0bz/notepadqq_es_inukaze.png)](https://postimg.org/image/4j57pa8a3/)

Here i put the files for the translation : 
[notepadqq_es.zip](https://github.com/notepadqq/notepadqq/files/1484639/notepadqq_es.zip)

**Comment by JuBan1** [comment]
You're right, this should translate properly. I can't look into it at the moment, but this is something we should fix eventually.

In the meantime I pulled your translation into master. Thanks!
