### ISSUE TITLE
Problem in Italian localization

### ISSUE THREAD

**Issue by marcoM32** [notepadqq/notepadqq#509]
**Description**
On my Linux Mint after updating Notepadqq the program is not fully translated, but more than one menu is displayed in English.

![schermata a 2017-11-19 20-28-13](https://user-images.githubusercontent.com/16719549/32994494-69ee26bc-cd68-11e7-806c-37728730b87d.png)

**Current behavior**
Not all labels is in the system language

**Expected behavior**
All labels is in system language because the program resource for this language is complete

```
<message>
        <location filename="../ui/mainwindow.ui" line="883"/>
        <source>Interpret as UTF-8 without BOM</source>
        <translation>Interpreta come UTF-8 sans BOM</translation>
</message>
```

**Minimal reproduction of the problem with instructions**
Systematic

**Please tell us about your environment:**
Program version: 1.2.0

**Comment by danieleds** [comment]
Not sure, but it could be because of the introduction of the keyboard shortcuts (e.g. "Interpret" is now actually "&Interpret").

If that's the case, we just need to update the translation file.
