### ISSUE TITLE
Ukrainian Translation for Notepadqq

### ISSUE THREAD

**Issue by Lan72** [notepadqq/notepadqq#513]
Hello, 

My OS is [Haiku](https://www.haiku-os.org/), the last night build hrev51662.
I've installed Qt5.9.3 and Notepadqq 1.20.

I bring to your attention the Ukrainian translation for Notepadqq.
I attach an archive with localization files - .ts and just in case .qm, as well as two modified source files:
[notepadqq_uk.zip](https://github.com/notepadqq/notepadqq/files/1544921/notepadqq_uk.zip)

**Comment by danieleds** [comment]
Added, thank you.
