### ISSUE TITLE
Notepadqq icon is wrong under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [notepadqq/notepadqq#515]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
notepadqq shows a generic Wayland icon instead its own icon.

**Expected behavior**
notepadqq shows its own icon.

**Minimal reproduction of the problem with instructions**
start kde plasma Wayland session
open notepadqq
![screenshot_20171211_120315](https://user-images.githubusercontent.com/15967631/33834794-64d772f0-de6b-11e7-9ec0-d33d3f734234.png)

**Please tell us about your environment:**
Arch Linux, qt 5.10, notepadqq 1.2

**Comment by JuBan1** [comment]
For now I'm not using Wayland so it's difficult to fix.

But to make fixing it easier in the future here's some relevant info:

> On X11 the applications exported the window icon as pixmap data. This is no longer possible on Wayland. Instead the compositor maps the window icon from the desktop file and the application announces the desktop file for a window. In Qt this is done by using the reverse domain name combined with the binary name. The domain name is set with KAboutData and defaults to “kde.org”. So for example in the case of kate the desktop file should be called “org.kde.kate.desktop”. So please fix the naming of your desktop files. If you want to test please be aware that this requires Qt 5.5 to work properly.


https://blog.martin-graesslin.com/blog/2015/07/porting-qt-applications-to-wayland/

**Comment by glaubersm** [comment]
rename .desktop file to org.kde.notepadqq.desktop did not work.
My qt is 5.10.
