### ISSUE TITLE
complains about old version of Qt with Qt 5.10.0

### ISSUE THREAD

**Issue by Shohou** [notepadqq/notepadqq#516]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```
![screenshot_20171214_103545](https://user-images.githubusercontent.com/1607593/33982998-3a0ed50c-e0bb-11e7-93ad-160d83d1f7f7.png)

**Please tell us about your environment:**

Arch linux with kernel 4.14.5-1-ARCH , Qt 5.10.0, Notepadqq 1.2.0

**Comment by choryuidentify** [comment]
I've make commit for this bug.
I hope my commit can resolve this problem!
