### ISSUE TITLE
New feature: open forder via command line

### ISSUE THREAD

**Issue by alex2534alex** [notepadqq/notepadqq#520]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Folders cannot be opened via command line (error: file to open is a directory)

**Expected behavior**
Folders CAN be opened via command line (no errors :P)

**Minimal reproduction of the problem with instructions**
Just run this command:
`notepadqq "/path/to/folder"` 

**Please tell us about your environment:**

OS: Linux Mint 18.1
Qt version: 5.5.1
Notepadqq version: 1.2.0

**Comment by guekho64** [comment]
I'm not sure about what you're expecting Notepadqq to do.

Are you trying to open the files inside a folder?

If using Linux Mint, it should ship with "bash" as the default shell. Try with:

notepadqq /path/to/folder/*

I haven't tried it yet, but I'm pretty sure It should work (Nqq will open all files inside the folder)

**Comment by JuBan1** [comment]
I agree. Use the glob pattern (`*`) to open multiple files.

**Comment by Baltasarq** [comment]
It is not so difficult to understand.

Currently, when you type from command line:
`$ notepadqq . &`

Notepadqq does not open anything, and complains saying that the folder is... well, a folder.

The expected behaviour would be the same one as when one goes to the option "File >> Open Folder...", and then selects the desired folder.

As a side note if you try:
`$ notepadqq * &`

It will work, but you will have to dismiss one message box for each subfolder in the current folder.

**Comment by guekho64** [comment]
You can always do:

`find "$FolderWithFiles" -maxdepth 1 -type f -exec notepadqq {} +`

_This option tries to invoke only a single command with as many arguments as possible:_

* `notepadqq $File1 $File2 $File3...`

**or**

`find "$FolderWithFiles" -maxdepth 1 -type f -exec notepadqq {} \;`

_This option invokes a new command every time a new file is found:_

* `notepadqq $File1 ; notepadqq $File2 ; notepadqq $File3...`

(One of these should work, although I haven't tested them...)

Also, the `-maxdepth` option disables `find`'s ability to search for files inside a directory recursively. Some common settings for `-maxdepth` are:

* 0 -> Ignore hidden files (Those files whose name start with a period, like `.bashrc` inside home directory)

* 1 -> Search for hidden files too

Any value bigger than two should let `find` discover new files inside \<N\> folders within the initial one. 

Remove the option to search recursively for files inside every single folder within the first folder.

<hr>

If Notepadqq developers would like to actually implement some way to do the same, I'd suggest doing one of these:

A command line option like `--no-folder-warnings` (Or `--ignore-folders`), which would tell Notepadqq to simply avoid displaying an error every time it tries to open a folder.

`notepadqq ~/Documents/*`

If this gets implemented, technically you could create scripts that would make use of this in an useful way...

<hr>

A command line option like `--open-folder`, which would tell Notepadqq to directly start its UI showing the "Open Folder" window, just as if you went to "File -> Open Folder..."

**Comment by Baltasarq** [comment]
> A command line option like --open-folder, which would tell Notepadqq to directly start its UI showing the "Open Folder" window, just as if you went to "File -> Open Folder..."

Yep. Well, you could always avoid the necessity of a command-line switch, since notepadqq already detects it as a folder, but that's the idea.
About scripts, I am not fluent in bash.
