### ISSUE TITLE
Error opening AppImage (Continuous Build)

### ISSUE THREAD

**Issue by drohm** [notepadqq/notepadqq#524]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I wanted to give the new AppImage a test drive, but I'm getting an error when I try to launch the AppImage.  If it's not ready for testing, no problem, just let me know and I'll go back to using the PPA.  I'm getting the following error:
```
drohm@ezy:~$ notepadqq-1.2.0-9-gb14749b.glibc2.14-x86_64.AppImage 
notepadqq.wrapper: error while loading shared libraries: libappimage.so: cannot open shared object file: No such file or directory
```
**Expected behavior**
Expected behavior would be for the application to launch.

**Minimal reproduction of the problem with instructions**

Simply try to launch the AppImage.

**Please tell us about your environment:**

I'm running Ubuntu Budgie 17.10
Notepadqq version: [Continuous Build](https://github.com/notepadqq/notepadqq/releases/tag/continuous) AppImage

Output for `uname -rv`:
```
4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017
```

**Comment by KurtPfeifle** [comment]
Looks like there was a temporary problem with an AppImageKit component which the *`notepadqq`*  build script (* .travis.yml*) was invoking for its continuous build.

Would be nice if @JuBan1 or @danieleds could simply trigger a re-build (which should fix the issue).

Otherwise, this download will be b0rken for everybody until the next commit for other reasons triggers automatic rebuild.

**Comment by drohm** [comment]
Thanks @KurtPfeifle.  Hopefully we'll get a new build soon.

**Comment by JuBan1** [comment]
I pushed a useless commit to force a rebuild (don't know how @danieleds set up this system). Hope that'll fix the issue; I don't know enough about AppImages to debug it otherwise :)

**Comment by drohm** [comment]
@JuBan1 Newest build fixed the issue, thanks.
