### ISSUE TITLE
Wrong Interpretting of Qt 5.3 Dependency (5.10 isn't read as successor)

### ISSUE THREAD

**Issue by Retoolya** [notepadqq/notepadqq#526]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Launching Notepadqq results in an error message stating Qt 5.10 is an old version, and 5.3 or greater is required. "Notepadqq will try to do its best, but some things will not work properly." Should state some things *may* not work correctly in error message.

**Expected behavior**
Notepadqq should read the version of Qt correctly and not have any error messages.

**Minimal reproduction of the problem with instructions**
Reproduced using Qt 5.10 - 5.*

**Please tell us about your environment:**
Linux, Qt 5.10, Notepadqq v1.2.0

**Comment by JuBan1** [comment]
Already fixed inmater.
