### ISSUE TITLE
Support for Search in all open files

### ISSUE THREAD

**Issue by mrkafk** [notepadqq/notepadqq#531]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

Support for "Search in all open files"?

This is literally the only feature I'm missing in notepadqq compared to Notepad++ on Win.

**Comment by JuBan1** [comment]
Can be done with the new search function opened via CTRL+Shift+F and selecting "Search in all opened documents".

It only just got pushed so you'll have to ride the master, so to speak, because it probably won't show up in most distributions' repositories quickly.
