### ISSUE TITLE
AppImage and 'Open with Other Application'

### ISSUE THREAD

**Issue by drohm** [notepadqq/notepadqq#532]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I right-click on a text file in nautilus and choose View All Applications, Notepadqq isn't in the list of available applications.  I'm guessing this is because I'm using the AppImage.  Is that simply the nature of using an AppImage and nothing can be done in regards to this?

**Expected behavior**
I'm expecting to see Notepadqq in the list of available applications to open the file that I right-clicked on.

**Minimal reproduction of the problem with instructions**
Install AppImage for Notepadqq.  Right-click on a text file and choose 'Open with Other Application' and select 'View All Applications'.  Notepadqq isn't there.

**Please tell us about your environment:**
Ubuntu Budgie 17.10
Latest Continuous AppImage Build of Notepadqq

**Comment by danieleds** [comment]
Closing as AppImage support has been discontinued and snap is now the preferred medium.
