### ISSUE TITLE
Whether to consider upgrading to QT5.9？

### ISSUE THREAD

**Issue by omgredfog** [notepadqq/notepadqq#533]
$ ../configure --prefix /usr --qmake /home/i7/Qt5.9.3/5.9.3/gcc_64/bin/qmake --lrelease /home/i7/Qt5.9.3/5.9.3/gcc_64/bin/lrelease
checking for QT5 qmake... /home/i7/Qt5.9.3/5.9.3/gcc_64/bin/qmake
checking for lrelease... /home/i7/Qt5.9.3/5.9.3/gcc_64/bin/lrelease
checking for c++... /usr/bin/c++
checking whether c++ compiler builds test program... ok
checking whether c++ compiler supports -std=c++0x... ok
checking whether compiled test program works... ok
checking for make... /usr/bin/make
checking for pkg-config... /usr/bin/pkg-config
checking for Qt5Core library... -L/home/i7/Qt5.9.3/5.9.3/gcc_64/lib -lQt5Core
checking for Qt5Gui library... -L/home/i7/Qt5.9.3/5.9.3/gcc_64/lib -lQt5Gui -lQt5Core
checking for Qt5Network library... -L/home/i7/Qt5.9.3/5.9.3/gcc_64/lib -lQt5Network -lQt5Core
checking for Qt5WebKit library... not found!
checking for Qt5Widgets library... -L/home/i7/Qt5.9.3/5.9.3/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5WebKitWidgets library... not found!
checking for Qt5PrintSupport library... -L/home/i7/Qt5.9.3/5.9.3/gcc_64/lib -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5Svg library... -L/home/i7/Qt5.9.3/5.9.3/gcc_64/lib -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Core
generate Makefile... Cannot find file: notepadqq.pro.
error!

‘Qt5WebKit library’   &  ‘Qt5WebKitWidgets library’     not found!

i search it on Google, and found that they were have been removed by QT Officail

[Porting from Qt WebKit to Qt WebEngine](http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html
)

**Comment by JuBan1** [comment]
We're aware of WebKit being deprecated but porting Nqq to WebEngine is a ton of work. So for now you'll have to use WebKit.

From the paths it seems you used the Qt online installer to download packages; that one doesn't have WebKit anymore. Most distributions still have WebKit available as a package, or you could build it from source.

**Comment by danieleds** [comment]
FYI I'm trying to build a simple transparent upgrade layer for WebEngine. Still experimenting.
