### ISSUE TITLE
Regex not working properly

### ISSUE THREAD

**Issue by gamer01** [notepadqq/notepadqq#535]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Matching multiline text with regexes is not working

**Expected behavior**
Match the whole string

**Minimal reproduction of the problem with instructions**
having a text
```
a
b
c
```
trying to match it with `a[\s\S]*c`

**Please tell us about your environment:**
Archlinux
Notepadqq 1.2.0

**Comment by JuBan1** [comment]
Neither '\s' or '\S' match a newline character. With `a[\S\n]*c\` you can find a match.

There's a display bug though, the matched text will only be `a` instead of the whole three lines.
