### ISSUE TITLE
Document how regexes are evaluated

### ISSUE THREAD

**Issue by gamer01** [notepadqq/notepadqq#536]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
Regexes have no unified standard, therefore its important to know how the regexes are interpreted. As i found out from the source code [this](https://doc.qt.io/qt-5/qregexp.html#details) should be the applicable documentation. Other users might not want to dig the code, so i would recommend to put this link somewhere in the UI, or at least in your official documentation.

**Comment by JuBan1** [comment]
Putting a link somewhere might not be the worst idea.

`QRegexp` is a good start although it doesn't use exactly the same syntax as `QRegularExpression` which is what we're using. I believe that one implements most of the perl-like regexp language. The Qt docs link to [this](http://perldoc.perl.org/perlre.html) document.
