### ISSUE TITLE
Feature Request: Show/Hide Menu with accelerator "Ctrl+M"

### ISSUE THREAD

**Issue by lorendias** [notepadqq/notepadqq#540]
**Current behavior**
Currently the menu is always-on.

**Expected behavior**
I would like to turn it off and be able to toggle it back on with Ctrl + M, other Qt apps have this feature.

I plan to use Notepadqq more with a a Qt HUD Searchable menu similar to how GTK apps have [Plotinus](https://github.com/p-e-w/plotinus).

Alternatively I would suggest directly implementing that HUD feature so Notepadqq can mimick Sublime (Ctrl + P) and GIMP's (Hotkey "/") searchable menu features.

**Comment by JuBan1** [comment]
I'm a big proponent of being able to remove UI elements. Added with #543.
