### ISSUE TITLE
Cannot add PPA on ubuntu 16.04

### ISSUE THREAD

**Issue by jiwilat** [notepadqq/notepadqq#544]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm trying to add the PPA repository on Ubuntu 16.04 however an error is displayed

sudo add-apt-repository ppa:notepadqq-team/notepadqq
Cannot add PPA: 'ppa:~notepadqq-team/ubuntu/notepadqq'.
ERROR: '~notepadqq-team' user or team does not exist.

**Please tell us about your environment:**
Description:	Ubuntu 16.04.3 LTS

**Comment by JuBan1** [comment]
Can't replicate on 17.10. And looking over our launchpad repo it looks like everything is alright.

Can you add other apt-repositories? Is it an error only showing up with nqq's repo?

**Comment by jiwilat** [comment]
Thanks for your reply.
Certainly I'm able to add other repositories without any problem, anyway I have to reinstall that PC on weekend, will do that and report back when done
Thanks

**Comment by jhult** [comment]
@jiwilat, any update?

**Comment by jiwilat** [comment]
Hi Jonathan

Please forgime me for not responding in time, I reinstalled my PC and the problem was solved, in the end I didn't understood why other repositories worked well but this one

Thanks
