### ISSUE TITLE
Icons not visible on Ubuntu 17.10

### ISSUE THREAD

**Issue by siddrc** [notepadqq/notepadqq#546]
Bug
I had Ubuntu 16, which I then upgraded to 17.04 , I had installed notepadqq previously before the update but after the update it seems all the icons in the menu bar and tool bar have disappeared.
I am attaching the screenshot, please have a look. 
**Expected behavior**
the icons were perfectly visible before the update.
**Please tell us about your environment:**
Ubuntu 17.04, Notepadqq 1.2.0 and Qt is at 5.9.1
![screenshot from 2018-02-09 17-22-10](https://user-images.githubusercontent.com/363164/36026603-eb1cf1ec-0dbd-11e8-9afa-5f3f1031a44d.png)
![screenshot from 2018-02-09 17-22-15](https://user-images.githubusercontent.com/363164/36026605-eb4bd246-0dbd-11e8-9962-272897228935.png)
![screenshot from 2018-02-09 17-22-17](https://user-images.githubusercontent.com/363164/36026606-eb7ab7e6-0dbd-11e8-891c-61e13ee82220.png)
![screenshot from 2018-02-09 17-22-25](https://user-images.githubusercontent.com/363164/36026607-eba8be3e-0dbd-11e8-8b5f-c88f67cabaa7.png)
![screenshot from 2018-02-09 17-22-27](https://user-images.githubusercontent.com/363164/36026608-ebd6bbb8-0dbd-11e8-91d3-d8fbe4363617.png)

**Comment by JuBan1** [comment]
Works for me on 17.04. Have you tried removing and reinstalling Notepadqq? Perhaps something during the upgrade process went wrong.

**Comment by siddrc** [comment]
Yup, did that..but got the same result :(
```
sudo apt-get remove --purge notepadqq
sudo apt-get autoclean
sudo apt-get clean
//removal done
//started installation
sudo add-apt-repository ppa:notepadqq-team/notepadqq
sudo apt-get update
sudo apt-get install notepadqq
```

**Comment by JuBan1** [comment]
What happens if you start Notepadqq from terminal? Do you see a bunch of "Missing Icon" messages?

It looks like you're using a custom icon theme, so it might not have the icons Notepadqq is looking for. Or perhaps Nqq isn't doing the lookup properly.

**Comment by siddrc** [comment]
You were right, I was on GNOME , so i switched to Unity and there was peace in the world, thanks :)
