### ISSUE TITLE
FEATURE REQUEST: Add option to close window/program when last tab is closed

### ISSUE THREAD

**Issue by vertigo220** [notepadqq/notepadqq#548]
**I'm submitting a ...**  (check one with "x")
```
[ x] feature request

```

**Current behavior**

If there's just one file open, if the tab for it is closed, Notepadqq stays open with a blank tab/document.

**Expected behavior**

I would like an option (_not_ a forced change in behavior, as I'm sure there are those that prefer it the way it is) to close Notepadqq if the close button is clicked on a tab when it's the only one open.

**Minimal reproduction of the problem with instructions**

N/A

**Please tell us about your environment:**

Linux Mint 18.3, Qt version and Notepadqq version unknown (on different computer) but irrelevant (will add if requested).

**Comment by JuBan1** [comment]
Good idea! Added as #550.
