### ISSUE TITLE
Missing icon messages when launching from terminal

### ISSUE THREAD

**Issue by vertigo220** [notepadqq/notepadqq#552]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

![notepadqq](https://user-images.githubusercontent.com/12024557/36296180-ec1b167a-12e3-11e8-9fdd-9570d66914cf.jpg)

**Expected behavior**

"Missing icon..." lines shouldn't be present

**Minimal reproduction of the problem with instructions**

See above

**Please tell us about your environment:**

Mint 18.3 Cinnamon, Qt 5.5.1, Nqq 1.2.0, GNOME terminal 3.18.3

**Comment by JuBan1** [comment]
This warning shows up when Nqq can't find an icon in the user's icon theme. That means you probably won't see a few icons in Nqq (such as the ones in the `Search->Next Result` and `Search->Previous Result` menu entries).

I think the error message is useful because it tells users what's wrong. Could you tell my what icon theme you're using?

**Comment by vertigo220** [comment]
How would I tell? I assume it's a Linux-wide theme, not a Nqq theme?

**Comment by JuBan1** [comment]
It should tell you in `System Settings -> Themes -> Icons` which Theme you're using. I quickly installed a fresh version of Mint Cinnamon and it seems to not have this issue with default settings:

![https://i.imgur.com/5WUwWJA.png](https://i.imgur.com/5WUwWJA.png)

**Comment by vertigo220** [comment]
It's set to Mint-X. I also tried Mint-Y, gnome, and Adwaita, restarting Nqq after each change, but the icons are missing for each one.

**Comment by JuBan1** [comment]
Hm, they do work for me. Have you installed it via the ppa (apt-get) or the AppImage?

**Comment by vertigo220** [comment]
PPA

**Comment by danieleds** [comment]
Interestingly, the same issue seems to happen with the (unofficial) Snap package:

https://forum.snapcraft.io/t/call-for-testing-notepadqq/3982

**Comment by vertigo220** [comment]
This is interesting. Not sure what changed, but even though originally, as seen in the screenshot I posted before, this happened when running Nqq as user, now when I run it as user I don't get the error and I have the previous/next icons. But if I run it as sudo I get the error, the icons aren't there, and the other icons (save, save as, cut/copy/paste, etc) are all different. So not only does it seem to be an issue with the theme or an icon pack, but for some reason it uses different ones depending on what account it's run under.

**Comment by JuBan1** [comment]
As far as I understand Qt is loading the theme and icons of the user executing the program. Root probably has a different icon set than your user account. Happens to other programs too.

I don't think this is directly related to the previous/next icons mysteriously not showing. Unfortunately it's hard to debug for me since I don't have that issue and can't repo it  with a fresh Mint Cinnamon install.

**Comment by JuBan1** [comment]
@vertigo220 Can you post the output of `find /usr/share/icons/ -name 'go-next.*'` here? Perhaps the issue is simpler than imagined and the icon simply isn't there.

**Comment by vertigo220** [comment]
Looks like they are:

`/usr/share/icons/breeze/actions/16/go-next.svg
/usr/share/icons/breeze/actions/22/go-next.svg
/usr/share/icons/breeze/actions/24/go-next.svg
/usr/share/icons/Mint-X/actions/48/go-next.png
/usr/share/icons/Mint-X/actions/16/go-next.png
/usr/share/icons/Mint-X/actions/32/go-next.png
/usr/share/icons/Mint-X/actions/22/go-next.png
/usr/share/icons/Mint-X/actions/24/go-next.png
/usr/share/icons/oxygen/32x32/actions/go-next.png
/usr/share/icons/oxygen/16x16/actions/go-next.png
/usr/share/icons/oxygen/22x22/actions/go-next.png
/usr/share/icons/oxygen/48x48/actions/go-next.png
/usr/share/icons/oxygen/64x64/actions/go-next.png
/usr/share/icons/oxygen/128x128/actions/go-next.png
/usr/share/icons/breeze-dark/actions/16/go-next.svg
/usr/share/icons/breeze-dark/actions/22/go-next.svg
/usr/share/icons/breeze-dark/actions/24/go-next.svg
/usr/share/icons/gnome/32x32/actions/go-next.png
/usr/share/icons/gnome/16x16/actions/go-next.png
/usr/share/icons/gnome/22x22/actions/go-next.png
/usr/share/icons/gnome/24x24/actions/go-next.png
/usr/share/icons/gnome/48x48/actions/go-next.png
/usr/share/icons/gnome/256x256/actions/go-next.png
/usr/share/icons/Adwaita/32x32/actions/go-next.png
/usr/share/icons/Adwaita/16x16/actions/go-next.png
/usr/share/icons/Adwaita/22x22/actions/go-next.png
/usr/share/icons/Adwaita/24x24/actions/go-next.png
/usr/share/icons/Adwaita/48x48/actions/go-next.png
/usr/share/icons/Adwaita/256x256/actions/go-next.png
/usr/share/icons/HighContrast/32x32/actions/go-next.png
/usr/share/icons/HighContrast/16x16/actions/go-next.png
/usr/share/icons/HighContrast/scalable/actions/go-next.svg
/usr/share/icons/HighContrast/22x22/actions/go-next.png
/usr/share/icons/HighContrast/24x24/actions/go-next.png
/usr/share/icons/HighContrast/48x48/actions/go-next.png
/usr/share/icons/HighContrast/256x256/actions/go-next.png
`

**Comment by danieleds** [comment]
@vertigo220 could you also post the output of the following command?

    find /usr/share/icons/ -name 'edit-undo.*'

just to compare the previous with something that you have for sure.

**Comment by vertigo220** [comment]
/usr/share/icons/breeze/actions/16/edit-undo.svg
/usr/share/icons/breeze/actions/32/edit-undo.svg
/usr/share/icons/breeze/actions/22/edit-undo.svg
/usr/share/icons/breeze/actions/24/edit-undo.svg
/usr/share/icons/Mint-X/actions/48/edit-undo.png
/usr/share/icons/Mint-X/actions/16/edit-undo.png
/usr/share/icons/Mint-X/actions/32/edit-undo.png
/usr/share/icons/Mint-X/actions/22/edit-undo.png
/usr/share/icons/Mint-X/actions/24/edit-undo.png
/usr/share/icons/oxygen/32x32/actions/edit-undo.png
/usr/share/icons/oxygen/16x16/actions/edit-undo.png
/usr/share/icons/oxygen/22x22/actions/edit-undo.png
/usr/share/icons/oxygen/48x48/actions/edit-undo.png
/usr/share/icons/breeze-dark/actions/16/edit-undo.svg
/usr/share/icons/breeze-dark/actions/32/edit-undo.svg
/usr/share/icons/breeze-dark/actions/22/edit-undo.svg
/usr/share/icons/breeze-dark/actions/24/edit-undo.svg
/usr/share/icons/gnome/32x32/actions/edit-undo.png
/usr/share/icons/gnome/16x16/actions/edit-undo.png
/usr/share/icons/gnome/22x22/actions/edit-undo.png
/usr/share/icons/gnome/24x24/actions/edit-undo.png
/usr/share/icons/gnome/48x48/actions/edit-undo.png
/usr/share/icons/Adwaita/32x32/actions/edit-undo.png
/usr/share/icons/Adwaita/16x16/actions/edit-undo.png
/usr/share/icons/Adwaita/22x22/actions/edit-undo.png
/usr/share/icons/Adwaita/24x24/actions/edit-undo.png
/usr/share/icons/Adwaita/48x48/actions/edit-undo.png
/usr/share/icons/HighContrast/32x32/actions/edit-undo.png
/usr/share/icons/HighContrast/16x16/actions/edit-undo.png
/usr/share/icons/HighContrast/scalable/actions/edit-undo.svg
/usr/share/icons/HighContrast/22x22/actions/edit-undo.png
/usr/share/icons/HighContrast/24x24/actions/edit-undo.png
/usr/share/icons/HighContrast/48x48/actions/edit-undo.png
/usr/share/icons/HighContrast/256x256/actions/edit-undo.png

**Comment by Teklad** [comment]
Pretty sure I managed to dig up the cause of this problem... I'll make a pull request soon which should resolve it.  This doesn't happen when XDG_CURRENT_DESKTOP is set to a valid setting prior to running (i.e. XDG_CURRENT_DESKTOP=X-Cinnamon notepadqq).

**Comment by Teklad** [comment]
Actually I don't believe this is a bug so much as a QT "feature" causing a bit of grief.  To fix this just follow the steps here https://wiki.archlinux.org/index.php/qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma  (they should apply to your distro as well).

From what I understand if XDG_CURRENT_DESKTOP isn't set it defaults to thinking you're using KDE and won't follow any icon theme changes via GTK.

**Comment by Teklad** [comment]
@vertigo220 could you give me the terminal output of `echo $XDG_CURRENT_DESKTOP` just so I can be certain about this issue.  Just wanting to confirm.

**Comment by vertigo220** [comment]
@Teklad Sorry it took so long, started having issues, one of which was that the terminal wouldn't open, and got busy with other stuff. Anyways, here you go:

echo $XDG_CURRENT_DESKTOP   ->   X-Cinnamon

**Comment by Teklad** [comment]
@vertigo220 I'm thinking your version of Cinnamon isn't properly setting the icon theme.  The way QT works is it prefers KDE's icon theme if you're using KDE... otherwise it defaults to GTK.

If Cinnamon is failing to set your GTK icon theme properly this would explain the issue in full.  Would you care to provide the following files from your system for overview:
~/.config/gtk-3.0/settings.ini
~/.gtkrc-2.0

My best guess at this point is your theme isn't being properly set in one of these files when you set it using Cinnamon's interface.

**Comment by vertigo220** [comment]
@Teklad Unfortunately, I just did a reinstall on the computer as I had to make some headway on getting it up and running. Sorry :(
