### ISSUE TITLE
Notepadqq no longer launching after opening large file

### ISSUE THREAD

**Issue by hwsamuel** [notepadqq/notepadqq#554]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I opened a large file and Notepadqq crashed. Now when I launch Notepadqq, it doesn't start at all. I've also deleted the large file but still same behavior from Notepadqq

**Expected behavior**

Since the large file is removed, Notepadqq shouldn't be trying to re-open it. It should launch normally

**Minimal reproduction of the problem with instructions**

- Open a fairly large text file, mine was about 45MB
- Close Notepadqq on hang (force quit)
- Try reopening

**Please tell us about your environment:**

I'm running Ubuntu 16.04

**Comment by JuBan1** [comment]
I assume the tab cache still retains a copy of the file. You can clear the cache by deleting `session.xml` in `~/.config/Notepadqq/; that should get Nqq up and running again.

We do have to handle large files better though.

**Comment by hwsamuel** [comment]
Thanks, that fixed it
