### ISSUE TITLE
execution fails -- snap install notepadqq (linux mint 18.3)

### ISSUE THREAD

**Issue by aplatypus** [notepadqq/notepadqq#556]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

* Install:
  `snap install notepadqq`

* Attempt to run editor, add missing(_??_) directory:
```
    $ notepadqq 
    cannot create user data directory: /home/william/snap/notepadqq/94: Not a directory
    $ mkdir -p /home/william/snap/notepadqq/94
    $ notepadqq 
    cannot create user data directory: /home/william/snap/notepadqq/94: Not a directory
    $ notepadqq --help
     cannot create user data directory: /home/william/snap/notepadqq/94: Not a directory
```
*  Directory actually existed anyway so issue is something not Indicated By the Message.
```
    $  ls -l  /home/william/snap/notepadqq/
    total 8
     drwxr-xr-x 2 william william 4096 Feb 23 00:24 94
     drwxr-xr-x 2 william william 4096 Feb 23 00:24 common
     lrwxrwxrwx 1 william william    2 Feb 23 00:24 current -> 94
```
remove:
* The remove is incomplete.
* After `snap remove notepadqq`
```
    $ notepadqq 
    bash: /snap/bin/notepadqq: No such file or directory
```

**Expected behavior**

* I would like to see the editor start
* Also I'd like some kind of `--help` facility so I can check what may be wrong
* I think a `man` or `info` page is warranted in this day and age.
    * I have added `notepadqq` using `apt-get` -- It has a `man` page
* I also expect a GUI launcher/short-cut == Desktop menu item and perhaps icon to run the program as a GUI.
* I expect `snap remove notepadqq` to clean-up and not leave _dangling_ and _false_ links 
   to the un-installed package.

**Minimal reproduction of the problem with instructions**

* As described above

**Please tell us about your environment:**

* Linux Mint 18.3 (up to date) 64-bit
* Cinnamon (latest)
* Not sure about Qt -- that doesn't appear as a dependency when I used `apt-get` after this.

**Comment by danieleds** [comment]
Hi,

the snap package you installed is created and owned by a non-official entity, so we cannot give support. Sorry.
However, we're currently working on transferring the ownership of the "notepadqq" snap so that we can provide an official package.

Stay tuned

**Comment by danieleds** [comment]
Hi,

could you try again? I've tested on Ubuntu 17.10 and it seems to work.
The man page is still missing but will be available soon.
