### ISSUE TITLE
Snap package issues

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#557]
* Man page is missing
* "nqq" launcher shortcut is missing
* NetworkManager error when starting from terminal
* Qt error when running `notepadqq --help`

see also #556 

@fefeh1 if you can, let me know if you have any idea about these :)

**Comment by JuBan1** [comment]
It appears the Snaps get "built, but failed to release" at the moment.

**Comment by danieleds** [comment]
It apparently got stuck on some old package. Now it should start working again.

**Comment by danieleds** [comment]
The badge however is not very reliable as it seems they forgot to cache-control it

**Comment by JuBan1** [comment]
Confirmed. The problem is that snaps only have limited access to the filesystem. It can read $HOME and removable media but not other locations like /etc with some exceptions. I think we can fix that easily.

**Comment by danieleds** [comment]
Thanks. You should be able to test the classic confinement as soon as the new snap builds
(use the --edge channel)

**Comment by danieleds** [comment]
Reverted. Apparently, that's not the way.

Also Gedit uses strict confinement too: https://bazaar.launchpad.net/~ubuntu-desktop/gedit/snap/view/head:/snapcraft.yaml

**Comment by JuBan1** [comment]
@danieleds That's because Gedit suffers the same issue

![img](https://i.imgur.com/tqXSsyX.png)

**Comment by Teklad** [comment]
Can we really keep snap as "recommended" with issues like this?  It is nice for what it is but seems to have more issues than a standard install....  with the exception of Ubuntu which enjoys crashing... a lot.

**Comment by danieleds** [comment]
Is any of you aware if Flatpaks suffer from the same issues or not?

**Comment by JuBan1** [comment]
Yes

> These directories are blacklisted: /lib, /lib32, /lib64, /bin, /sbin, /usr, /boot, /root, /tmp, /etc, /app, /run, /proc, /sys, /dev, /var

> The reason many of the directories are blacklisted is because they already exist in the sandbox such as /usr or are not usable in the sandbox.

http://docs.flatpak.org/en/latest/sandbox-permissions.html

**Comment by danieleds** [comment]
The optimal solution would be to find real maintainers for the Ubuntu (and Debian) packages. There is a RFP but nobody is working on it since years. Our PPA is just a "release and hope" process... we don't have time to test nqq on every version of every distro, that's what a maintainer should do.

I suspect that shutting down the PPA would easily make new maintainers show up, but... we can't really do that, of course :)

**Comment by JuBan1** [comment]
I guess the best we can do is to elevate the PPA back to the recommended option once the WebEngine branch (hopefully) fixes the crash issues.

**Comment by darealshinji** [comment]
I must say I haven't had any issues with NQQ on Ubuntu 16.04, always building it myself from source, linked against system Qt libraries. However, you could provide your own build of Qt libraries, prefixed and only used by NQQ so it doesn't interfere with the system libraries.

**Comment by danieleds** [comment]
Apparently, any user can already install nqq in classic mode by using the "--classic" flag, without us having to change the type of the package. Do you confirm?

This would be the ideal solution: most users can install it in standard mode, and we can point advanced users to some wiki page explaining "--classic" and the "/snap" manual fix for non-Ubuntu systems.

**Comment by JuBan1** [comment]
Works on my Ubuntu.

**Comment by danieleds** [comment]
> Works on my Ubuntu.

Apparently, that is not "normal" behaviour. They didn't give me any explanation on why it seems to work for some of us ([and not for others](https://plus.google.com/105279761461543762837/posts/GnFGgUomisH)).

Anyway, classic confinement has been granted for our snap. This means that users on Fedora (and many others) won't be able to use it anymore without hacks.

**Comment by danieleds** [comment]
The --edge channel is currently using classic confinement.

I'd like to hear your test results before promoting it to the stable channel, especially because we're not confined anymore (user libraries could creep in if we're not careful...).
I'm going to test it on the most crappy distros with the worst mess I can find.

**Comment by PeterProfessional** [comment]
Installed it with ` --edge --classic` on my Ubuntu 14.04
I can now work on files that I could not open before.

**Comment by gsim** [comment]
--edge --classic also worked on Ubuntu 18

**Comment by rdegraaff** [comment]
--edge --classic indeed works in Ubuntu 18. But in the save dialog of this build the "Retry as Root" prompt is missing. Bug?

**Comment by JuBan1** [comment]
@rdegraaff Do you have gksu (or kdesu) installed? If so it's probably a bug with the snap filesystem architecture.

**Comment by rdegraaff** [comment]
Doesn't look like I have it installed. Fresh install of Ubuntu 18.04 desktop, checked apt list --installed. Any other places I should look?

**Comment by JuBan1** [comment]
If you can run `gksu` in your terminal and a "command not found" you don't have it. It seems `gksu` isn't installed by default on Ubuntu anymore since a few years. 

You can install it via `sudo apt-get install gksu`. After that, your save dialog should have the extra option.

**Comment by rdegraaff** [comment]
gksu has been deprecated, so I can't install it. [This guy did some digging into it](https://itsfoss.com/gksu-replacement-ubuntu/). (his gvfs admin:// solution just gives me a "protocol not supported" error)

If I start the "--edge --classic" build of notepadqq with the --allow-root option, it does at least bring back the "Retry as Root" option. But since there's no gksu/kdesu behind it, it won't work. (clicking it just makes the "Error trying to write to..." prompt loop, without asking for a password)

**Comment by JuBan1** [comment]
Oh, I didn't know it is now deprecated. Perhaps we can support the gvfs admin backend as well, but I'll have to look into it more closely.

You should never get the "Retry as Root" option unless you have either gksu or kdesu installed. Nqq literally checks whether either of them can be run before showing the dialog. If it does show, perhaps the Snap confinement is messing with it. 

The allow-root option on its own doesn't do anything- it only permits Notepadqq to be run using `sudo`. But I don't think that's an option when using Snaps.

**Comment by rdegraaff** [comment]
After doing some more testing: sorry, you were right that allow-root doesn't make a difference. I'm simply always getting the "Retry as Root" option for files I don't own as a user, without having gksu installed. (both edge and stable channel)

**Comment by JuBan1** [comment]
I've added behind-the-scenes support for pkexec as well, meaning "Retry as Root" should work on newer Ubuntus now too.

I also fixed the bug that (likely) caused the "Retry as root" button to be visible when it shouldn't.

But it might take a while until these changes make their way into public repos. We've got some build issues at the moment, especially with snap.

**Comment by darealshinji** [comment]
Can you update the edge snap with the changes from [this commit](https://github.com/notepadqq/notepadqq/commit/efc5536a7d8f015db77281ea76cc658d036b0d84)?

**Comment by danieleds** [comment]
@darealshinji I'll look into it. I hope they fixed the core18 problems.

**Comment by danieleds** [comment]
I need some feedback, can you tell me if this works on your distro?
http://notepadqq.com/tmp/notepadqq_1.4.8+git_amd64.snap

It's a build of the master branch with qtwebengine, using core18. It works for me on Ubuntu 18.04.

Install with `snap install --dangerous --classic`

**Comment by darealshinji** [comment]
Unfortunately not:
```
cp: '/home/djcj/.config/user-dirs.locale' and '/home/djcj/.config/user-dirs.locale' are the same file

(notepadqq-bin:11150): Gtk-WARNING **: 17:07:09.707: GTK+ module /snap/notepadqq/x1/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 17:07:09.707: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(notepadqq-bin:11150): Gtk-WARNING **: 17:07:09.709: GTK+ module /snap/notepadqq/x1/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 17:07:09.709: Failed to load module "canberra-gtk-module"
Missing icon:  "document-open-recent"
Missing icon:  "system-run"
Could not find QtWebEngineProcess
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by darealshinji** [comment]
Ubuntu 18.04

**Comment by danieleds** [comment]
Thanks guys for the feedback, perfect as usual. I've been able to partially reproduce the problem.
We had a missing package and some search paths which were screwed up.

Can you try this new version? (the link is the same)
http://notepadqq.com/tmp/notepadqq_1.4.8+git_amd64.snap

**Comment by darealshinji** [comment]
Yes, it's working. Great!

**Comment by danieleds** [comment]
Finally!
It still has some issues on older versions of Ubuntu (16.04); as soon as I fix those I'll upload the new version to the edge channel.

**Comment by danieleds** [comment]
Okay, it's released on the edge channel. Let me know if anything's wrong.

**Comment by C-Duv** [comment]
> Thanks guys for the feedback, perfect as usual. I've been able to partially reproduce the problem.
> We had a missing package and some search paths which were screwed up.
> 
> Can you try this new version? (the link is the same)
> http://notepadqq.com/tmp/notepadqq_1.4.8+git_amd64.snap

Thanks, it fixed my issue of not being able to open a file in Notepadqq from the console.

**Comment by danieleds** [comment]
I may have found a way to automatically build new core18 packages on launchpad instead of build.snapcraft.io (see https://forum.snapcraft.io/t/core18-base-in-build-snapcraft-io/7715/4)

It's building right now

**Comment by danieleds** [comment]
And it works! The edge channel will be automatically updated with our master branch.
