### ISSUE TITLE
Add compile instructions for OSX in README.md [Instructions included inside]

### ISSUE THREAD

**Issue by Meissa** [notepadqq/notepadqq#558]
I've used Notepadqq for quite some time now on my Linux box, but my primary workstation is a Mac Mini running OSX High Sierra 10.13.3, so I wanted to be able to use Notepadqq on it as well.

It took me quite some time googling and playing with various options for how to get it to work, but I finally managed to get Notepadqq to compile on OSX:

![screen shot 2018-02-26 at 18 41 24](https://user-images.githubusercontent.com/10284121/36705940-d58b86e4-1b24-11e8-84c1-4dab99722959.png)

I imagine other people using OSX probably would be interested in getting Notepadqq working, as well, so I've put together a set of compile instructions that worked for me so that they can be included in the README.md

-----

### Dependencies

Notepadqq requires the newest version of `qt`, along with `qt5-qtwebkit` to compile. The easiest way to download and install the required dependencies is through Homebrew:

1. Install [Homebrew](https://brew.sh/) following the instructions on their website, if you do not already have it.
1. Open a terminal and install qt with the `brew` command:
```
brew install qt@5.5
```
3. Add qt's executables to your `$PATH`:
```
echo 'export PATH="/usr/local/opt/qt@5.5/bin:$PATH"' >> ~/.bashrc
```
4. Open a new terminal session so that the system variable change takes effect.
5. Symlink qt's libraries to the appropriate system location so that qmake will be able to find them when you go to compile Notepadqq:
```
brew link --force qt@5.5
```

### Compiling Notepadqq
1. Grab the newest source code zip from the [releases](https://github.com/notepadqq/notepadqq/releases) page.
1. Unzip the source into its own directory and `cd` into the directory in your favourite terminal app
1. Run the `configure` script:
```
./configure
```
The script should find successfully find all the required qt libraries and generate a makefile. If the script says "Not Found" for any of the required libraries, please make sure that you have linked the qt libraries into your $PATH through the above described `brew` command.

4. Compile it!
```
make
```
5. Notepadqq should successfully compile, and the compiled .app can be found in `notepadqq-x.x.x/out/release/notepadqq.app`. You can copy the `notepadqq.app` file into your Applications directory, and you are all good to go!

**Comment by danieleds** [comment]
Awesome instructions, thanks!

How long have you used it? Did you notice any problem?

**Comment by JuBan1** [comment]
Thanks for the instructions. Since this is a somewhat specific topic I think the Wiki is the best place for it.

I've sketched out a wiki page [here](https://github.com/notepadqq/notepadqq/wiki/Compiling-Notepadqq-on-Mac-OSX) based on your instructions. I made one change to it:

* I changed the `qt@5.5` Homebrew package to `qt` which, according to their [site](http://formulae.brew.sh/search?search=qt) should be the Qt 5.10 package.

Could you look over it again and check if they're fine? I don't have an OSX system to test it; I just think going for the more modern Qt version is a good idea since they usually include fixes and improvements.

**Comment by danieleds** [comment]
@JuBan1 I think webkitwidgets are missing from Qt 5.10

**Comment by JuBan1** [comment]
Gawd you're right. I checked the source given the Brew's package formula to be sure and Webkit isn't in there anymore. I reverted it back to `qt@5.5`.

Looking forward to the day we can get rid of Webkit for good.

**Comment by Meissa** [comment]
> I think webkitwidgets are missing from Qt 5.10

Yeah, I originally tried it using just the standard `qt` package, and it lacked the webkit widgets and wouldn't compile, hence why I switched to using the `qt@5.5` package.

The reason I actually ended up putting together the instructions is because the OSX compile is picky and frankly a bit of a pain in the ass, so I wanted my specific steps documented so that other people (or myself) could figure out how to do it again in the future :)

> How long have you used it? Did you notice any problem?

I've only been using it for a few days on OSX now, but I haven't noticed any issues. That being said, I am probably the most casual of users. I'm not a developer, so I don't really make use of most of the complex features in notepadqq like syntax highlighting or regex often.

I do use the theming feature, though, which is honestly the thing one would be most worried about being messed up on OSX, I would think (considering how picky it was being with the qt installation), and everything in the gui seems to work fine. 

I'm actually surprised; Notepadqq is actually was nicer looking on OSX than on Linux straight out of the box, and the context menus in the menu barare actually automatically organised to meet the OSX standards!

**Comment by danieleds** [comment]
> I'm actually surprised at how clean the compile seems to have went; Notepadqq is actually way nicer looking (in my opinion) on OSX than on Linux straight out of the box, and the context menus in the menu bar are actually automatically organised to meet the OSX standards!

Actually I did some work on it a lot of time ago, that's why it's relatively smooth :) However I ended up throwing everything away because of some upstream bugs. Nice to hear that it works fine now! I'll see if I can produce a dmg and put it on the website.

**Comment by JuBan1** [comment]
Ooo-kay. For the time being I've added a link to the Wiki to README.md.

I'll close this here since that was its purpose.
