### ISSUE TITLE
Provide appstream data for better integration into various Linux Software Centres

### ISSUE THREAD

**Issue by joebonrichie** [notepadqq/notepadqq#565]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

Providing [AppStream](https://www.freedesktop.org/wiki/Distributions/AppStream/) data will allow the various Linux Software Centres to better integrate notepadqq into them. Appstream data can provide metadata such as links to screenshots, icon thumbnails, bug tracker, licences, a summary and description for the software centre to use.

It reduces the reliance on distros to provide appropriate summaries, descriptions and the right licences and makes the software more appealing when stumbled across in a Software Centre.

It's a simple `.xml` file installed to `/usr/share/metainfo` i'll provide a link to kdeconnect's appstream data [here](https://github.com/KDE/kdeconnect-kde/blob/master/org.kde.kdeconnect.kcm.appdata.xml) and chromium's appstream data [here](https://github.com/chromium/chromium/blob/master/chrome/installer/linux/common/chromium-browser/chromium-browser.appdata.xml) as a point of reference.

**Comment by JuBan1** [comment]
Added by #566. Hope that's all that is needed!

**Comment by joebonrichie** [comment]
Thanks, working as expected. [Before](https://ibb.co/c0zVxx) and [after](https://ibb.co/hvyZPc), really does make a difference!
