### ISSUE TITLE
Will you be releasing pre-built binaries for Mac?

### ISSUE THREAD

**Issue by nathancarter** [notepadqq/notepadqq#568]
- [x] feature request

**Current behavior**
One must get developer tools and source code and compile the app from scratch for Mac.  To get updates, one must repeat the process.

**Expected behavior**
Releasing a Mac binary would be much easier for end users.

**Please tell us about your environment:**
Mac OS High Sierra, 10.13.3, Macbook Pro

**Comment by danieleds** [comment]
We will as soon as we manage to fix some giant bugs that are currently present, aka as soon as it exits the experimental stage.

Of course, testing would help a lot!

**Comment by nathancarter** [comment]
Very glad to hear it, and thanks for the speedy response!
