### ISSUE TITLE
Feature request: print function

### ISSUE THREAD

**Issue by vertigo220** [notepadqq/notepadqq#574]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```
Nqq is missing a print option, which frankly surprised me as I would have never expected it to not have one. This is something that should definitely be added.

**Comment by JuBan1** [comment]
Fixed in #586. 

Printing stopped working at some point and was temporarily disabled. Then "temporarily" became "permanently" and here we are.

**Comment by maurizio-omissoni** [comment]
no printing. so... just crap!
