### ISSUE TITLE
PPA is installing old version

### ISSUE THREAD

**Issue by jhult** [notepadqq/notepadqq#596]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The version is 1.2.0.

**Expected behavior**
The version would be 1.3.2-1 (or whatever version the PPA actually has).

The PPA version does not seem to match what gets installed.

**Minimal reproduction of the problem with instructions**

Installed PPA: https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq
`sudo apt install notepadqq`
`sudo apt list notepadqq` = notepadqq/now 1.3.2-1~xenial1 amd64 [installed,local]
`notepadqq --version` = Notepadqq 1.2.0

**Please tell us about your environment:**

OS: 16.04.1-Ubuntu SMP x86_64
Kernel: 4.8.0-53-generic
QT: 5.10.0 in /usr/lib/x86_64-linux-gnu

**Comment by jhult** [comment]
Might be related to #593 and reverting the debs back to 1.2.0.

**Comment by jhult** [comment]
I tried to grab direct versions from these 2 links and it still shows up as 1.2.0.

- https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq-common_1.3.2-1~artful1_all.deb
- https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq_1.3.2-1~artful1_amd64.deb

**Comment by danieleds** [comment]
Exactly, it is related to the deb revert.

I need to verify if v1.3.x works on Ubuntu 16.04, and then I'll reissue a release.
In the meantime, you can give a try to the new snap package (`sudo snap install notepadqq`).
Or, if you prefer, you can manually download the 1.3.1 version and see if it works for you:

https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq-common_1.3.1-0~xenial1_all.deb
https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq_1.3.1-0~xenial1_amd64.deb

version 1.3.1 is totally identical to 1.3.2.

**Comment by jhult** [comment]
Those links worked great!

I was formerly running the snap package but ran into issues with is using an old version of Qt (5.5), not looking pretty (as in the KDE decorator was not kicking in) and being slow to start. I hit none of these issues with the PPA.

Thanks again for all your hard work on this project! I love it.
