### ISSUE TITLE
Searches can't match across lines

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#60]
For a "problem" in search/searchcursor.js, we can't match across lines using regular expressions.

From codemirror docs:

> `query` can be a regular expression or a string (only strings will match across lines—if they contain newlines).

**Comment by aaronfranke** [comment]
This is still an issue in Notepadqq v1.0.1 in the Ubuntu 16.04 repos. \n can't be found in find/replace!

**Comment by JuBan1** [comment]
I'll give it a look with the work-in-progress search rework.

**Comment by estani** [comment]
Still there, neither regular expression or special characters search find linebreaks.
E.g. ^$ does not work to select an empty line

**Comment by JuBan1** [comment]
Fixed in #446
