### ISSUE TITLE
can't save indentation settings for plain-text/literature writing

### ISSUE THREAD

**Issue by dchmelik** [notepadqq/notepadqq#602]
**I'm submitting a
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question

**Current behavior**
If you set indentation setting to spaces and quit, after restarting, they're set to tabs, and can't be saved as spaces for next time.

**Expected behavior**
You should be able to save the indentation settings to be the same after quitting and starting.  When people edit plain-text/literature notes, papers, books, they probably don't want that set to tabs, at least for .TXT files that aren't code.  Notepadqq is now my favourite text editor (since my DE's main one has broken tab bars) but I can't actually set it to work more like an actual text editor that's a notepad, rather than an IDE, but mostly I edit .TXT files of notes, articles/papers, books, so would really like to be able to.  I'm a computer programmer/scientist too, so of course will eventually use tab indentation, but I'd like to set that of my own free will, or have it work for programming files but not .TXT, not just every session (plus getting warnings for two or three of my files I can only use the mouse to ignore.. but I love command-lines & keyboard shortcuts.)

**Minimal reproduction of the problem with instructions**
'Edit -> Indentation -> Custom' should be saveable as permanent configuration between sessions.

**Please tell us about your environment:**
Slackware GNU/Linux 14.2 (64-bit, up-to-date stable) w/KDE4... eventually will probably use with KDE3.5/TDE/Qt3 and/or classic *BSD Unix
Qt4.8.7, Qt5.7.1
notepadqq-1.2.0-x86_64-1_slonly (unofficial repository package compiled from un-/quasi-official build script repository) (first installed earlier version myself last year, then used SlackBuilds.org (SBo) build script, then used installer that SlackOnly.com updated SBo)

**Comment by dchmelik** [comment]
I just meant 'sessions: periods of time in which you edit.'  I don't use 'sessions' that are 'file lists' much yet, because unlike what I'm used to (KDE Advanced Text Editor with inadequate/broken tab bars) it seems saved sessions only open into the current (not necessarily saved) session or 'tab list' instead of as a separate list (I'm used to the current session being replaced when you open a new/saved one) so it hasn't helped much such as if I save & open a bunch of .C or .HTML files for some project (mixing them in with a bunch of .TXT files like my to-do list.)  But, that's a topic possibly for another ticket/question...

**Comment by dchmelik** [comment]
What Teklad describes works for now, but I'd rather exclude .TXT files from being considered indented at all.   My file of a list of things to do and view/read, listen to, and look for (also with a calendar, kind of like a Unix .plan) currently has some subcategories abbreviated from two to five letters, taking up columns two to six, so the first alignment is after one space, but the largest is after four spaces.  The file isn't indented, but Notepaddqq considered it indented by two spaces, so I had to use that setting to not get a warning, even though I use four or eight spaces for text tabs.  I edit other files like an ebook-type .TXT of notes on a subject, and sometimes others' I'm reading/using, that might have other indentation-type quirks but are best considered that indentation is not applicable, in contrast to programming languages.  If I wrote some sort of plain-text file that uses indentation in a formal way like programming, I'd want to temporarily use indentation that's being checked for.

**Comment by JuBan1** [comment]
Ah, I see. With use cases like these we always have to keep user friendliness and simplicity in mind. Unfortunately Nqq can't do what you want and all straight-forward solutions I can think of would mean adding a lot of complexity for, frankly, very little gain. (Even adding .txt as a new "language" would require out-of-mainline patches for CodeMirror.)

This sort of thing sounds perfect for an Extension but our extension system isn't powerful enough to handle it. It's on my to-do list but with no ETA in sight.

So unless someone has an idea for an elegant solution to that issue I vote not to "fix" this and let extensions handle it eventually.
