### ISSUE TITLE
Notepadqq/JS communication issue

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#605]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 
```

**Current behavior**
Notepadqq fails to retrieve info from the editor on exit if using javascript to retrieve the data with an asynchronous function.  An example of this can be seen when trying to use detectIndentationMode while notepadqq is trying to exit.

**Expected behavior**
Notepadqq properly retrieves the requested data via javascript prior to a clean exit.

**Other Notes**
This seems to be a communications issue where javascript isn't returning fast enough before notepadqq terminates.  It became apparent when adding custom indentation settings to the session files.  We either need to capture these types of settings on the C++ side of things for later use or find a way to make QT behave and wait for a return from javascript.

**Comment by danieleds** [comment]
To which branch are you referring?
