### ISSUE TITLE
Better custom language support

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#620]
Though I don't use it myself I'm sure there are others that could find this fairly useful.  As it stands now we read all our supported languages via Languages.js and adding additional languages is not such a straightforward process (Read modifying installation files via root, etc.).

There's a couple of things I'm wanting to do here and I'm just wanting @JuBan1 and @danieleds to give their opinions on this.  First and foremost... I'd like to remove Languages.js entirely and implement the language detection functions on the C++ side of things.  

This was done on the old webengine branch but I made it part of a very much larger commit which made backporting it a somewhat tedious task (lesson learned).

Now... with the Languages.js file removed I'd like to convert the available languages to either JSON or an ini style format.  The downside to using JSON would be the obvious inclusion of QML as a dependency... whereas an ini-like style is supported via QSettings.

Either way this file would be part of the distribution.  This file should be extendable via .config/Notepadqq/languages.ini or something similar for user-defined languages.

There's a lot of finer details to figure out but this *should* allow us to have a GUI for installing any CodeMirror language outside of the normal ones without the user needing to get down and dirty with nqq internals.

To handle new modes on the fly we could inject them into the open tabs on the fly while nqq is running and do the normal preload like we do with the rest of the modes thereafter.

There's been a couple of requests here and there for adding language support for X language... this would give other users of notepadqq with the know-how to upload new languages to github which we could provide links to the various ones at the authors request in our wiki somewhere or host them ourselves in a separate notepadqq-languages repository where we could accept pull requests from various language authors.

We should probably have a defined folder structure for these "language packs" so everyone can follow specific guidelines in regards to distribution.

Any input on this would be appreciated.  If the feature itself doesn't seem that useful we can just skip this as well.

**Comment by JuBan1** [comment]
I think it's not a bad idea. A few thoughts:

* I don't really like the name "Languages" for this feature; partially because I always get it messed up with localization in preferences (:p) and partially because it seems an unusual work to use. Perhaps this would be a nice opportunity to change it if I'm not alone with this? "Mode", or "Language Mode" come to mind. 

* QJson support only needs `core`, not `qml`. I'm using it in OTE as well. And I have/had plans to use Json for #301 too. So I'm in favour of it.

* Perhaps we could move the custom indentation/tabspace data from the Notepadqq.ini to this new file as well? It would also be a good place to store other related data (e.g. perhaps we'll have different indentation styles or limited linting support in the future).

* This might also be a nice way of properly solving issue #602. They could define a new language mode (sounds better, doesn't it?) just for .txt files and disable indentation for it.

**Comment by Teklad** [comment]
To your first point, I definitely agree that "Languages" seems a little too broad.  Mode seems fairly appropriate to me and is also what CodeMirror uses internally for different language definitions.

I must have been thinking of something else when thinking about QJson.  I probably used something that involved QML at one point and changed it in the code later on.

Moving the indentation/tabspace data to the new file does sound very appropriate considering what it would be used for and would allow manual modifications in one place if they want that.

For the last point, I do believe you would be correct... they could easily define a custom mode via the interface and choose not to provide a mode file, which would default to plaintext.  This would allow them to apply the special indentation settings to .txt files only without digging into the core of notepadqq's files at all.

This would probably be a good time to implement the language cache back in... possibly as a static function of Editor so we can get a list of available languages without *needing* an instance of editor active.  This was a simple initial design flaw that just never got fixed due to the fact it never caused any issues.  

That being said, this change will probably be separated into at least two pull requests to keep them separate if its possible at all.  I'm trying to keep pull requests limited to one particular feature so we don't have a mess like the original webengine branch I worked on.

**Comment by JuBan1** [comment]
> I must have been thinking of something else when thinking about QJson.

I had the exact same thought until I looked closer. I'm pretty sure I mixed it up with QJSEngine (which needs `qml`).

I suggest

*  making a new `class LanguageMode` that contains its name, indentation settings, file extensions, etc. Right now a Language is basically a `QMap` which is hard to work with and needs some [iffy hacks](https://github.com/notepadqq/notepadqq/blob/master/src/ui/include/EditorNS/editor.h#L96).

* making a new `class ModeManager` (or something like that) which can `loadFromFile("path/to/json")` to populate itself with all language modes and return them via `std::vector<const LanguageMode&> getAllModes()` and ` const LanguageMode& getModeFromFileExtension(string)` etc.

I think that would separate the Editor and Mode classes and give us a good basis for future enhancements.

**Comment by danieleds** [comment]
What about the actual code of the lexers? It's not clear to me if you suggest moving it out too or not

> I'd like to convert the available languages to either JSON or an ini style format.

What are you referring to, here? Just to the current content of Languages.js?

**Comment by Teklad** [comment]
Yes, just the current content of Languages.js.  The lexers would remain where they are.This basically adds support for overriding default lexers as well as adding new ones at the user level.  As it is now adding a new language or even making a small change requires modifying our own system files. I.e. adding it to languages.js, modifying index.html to load the new language, dropping a new lexer in CodeMirror libs manually, etc.

**Comment by danieleds** [comment]
It's ok for me, however any editing error to that config file could render notepadqq unusable.

I'm more comfortable in splitting it into two, e.g. a core file containing all the current stuff (still handled by c++, but not supposed to be modified by the users) and another one containing overrides and additions for the first one. This would also solve any potential issue with updates overriding user changes.

**Comment by Teklad** [comment]
That's basically what we'll be doing.  The core file will still be distributed which will contain all of our current stuff.  The user just has the option to override default settings if they want to along with adding new modes.

Any overrides provided by the user will be on a mode by mode basis.  The load order should be system definitions first... then user definitions.  This keeps the core integrity intact.

All of our core stuff will be loaded up as a guaranteed fallback in the event of any kind of config error.  This should keep any syntax errors via manual edits in the user config from rendering nqq unusable.  I'll put something in place to alert the user of these kinds of errors so they'll be aware that something is wrong.

There's some finer details to figure out in relation to javascript errors for new custom modes.  This is something we've been needing to handle properly for a while though so it wouldn't be a bad time to look into it.

**Comment by Teklad** [comment]
Yea... I plan to span this across a few "foundation" pull requests which is going to focus on solidifying the code base to be more flexible for future changes.  

I believe all of us are more fluent in programming at this point and updating the older parts of the code to reflect those advancements will be beneficial to us as well as any newcomers who wish to contribute.

I was just looking for some guidance in terms of how to implement this in the next few weeks.  For now I'll be focusing on various different refactoring projects to try and give the code some needed cleanup.

I do look forward to the OTE changeover in the future, however... and I may begin having enough time to contribute to that project very soon as well. (fingers crossed)
