### ISSUE TITLE
github releases page still shows 1.2.0 as the newest release

### ISSUE THREAD

**Issue by Osndok** [notepadqq/notepadqq#621]
...makes the project look stale ~~& probably breaks some automatic-building scripts (most packages are still at 1.2.0~~

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
github 'releases' tab shows '1.2.0' as the most recent release, but the commit history shows 1.3.6.

~~git tags (which github interprets as releases) are not finding there way to github.~~

**Expected behavior**
Release page should be in sync with releases.

~~Release script probably needs to explicitly push the tag, or use the '--tags' flag to push them all.~~

**Minimal reproduction of the problem with instructions**
Shows 1.2.0 "latest release":
* https://github.com/notepadqq/notepadqq/releases

Shows 1.3.6 as latest release:
* https://github.com/notepadqq/notepadqq/commits/master

**Please tell us about your environment:**
Evident using just a web browser.

**Comment by JuBan1** [comment]
Got to remember packaging releases on GH as well. Well, at least latest isn't 1.2.0 anymore.
