### ISSUE TITLE
Don't ask to save changes when closing an empty untitled tab

### ISSUE THREAD

**Issue by skalbers** [notepadqq/notepadqq#632]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

When opening a new tab in NP++ and typing something like 'aaa' and then removing it, one can close the tab without an additional request by the program.
In Nqq one always gets a Request like "Do you want to save changes to «new X» before closing?".

I couldn't find the spot in the code where this behaviour is checked, something like a check of the "fileSize" or length of the content in a new tab (with applying a trim or removing only whitespace-characters before this check) would suffice I think.

**Please tell us about your environment:**
OpenSuse Leap 42.1
Qt 5.5.1
Notepad 1.2.0 (the latest version with a compiled binary "notepadqq-v1.2.0-linux-x64.tar.gz")

**Comment by danieleds** [comment]
I agree it is interesting behaviour, but I'm against being "too smart" in cases like this.

Just as a stupid example, consider if I want to save a small chunk of text (e.g. a random password, a small hash, whatever). I could type or paste it, then close the tab expecting nqq to ask me if I want to save it. When it doesn't, I've lost my text forever.

**Comment by skleinealber** [comment]
Maybe I wasn't clear enough.
I expect this behaviour only, if the content size is zero (at the bottom 0 chars, 1lines) and it's in a new tab.

**Comment by Teklad** [comment]
Should be as simple as marking as clean if content size is 0

**Comment by JuBan1** [comment]
Can't do that because a named document (e.g. an actual file loaded from disk) would still be dirty when its contents are deleted.

This is a special case where the document is an orphan *and* it's empty.
