### ISSUE TITLE
the menu bar and toolbar is missing...

### ISSUE THREAD

**Issue by nm46nm** [notepadqq/notepadqq#633]
I download notepadqq with `sudo apt-get install notepadqq`
I closed the menu bar and toolbar  by accident. Now I can't open it......
And I want to uninstall it and reinstall, hoping it will be initialized. But it seems the new one inherited the data of the old one.
So how can I do to show the menu bar? or to entirely remove it?

**Comment by danieleds** [comment]
Edit `~/.config/Notepadqq/Notepadqq.ini` and delete the "[MainWindow]" section with the 4 lines below it.

**Comment by nm46nm** [comment]
Thank you @danieleds ,I finally solve it by `ctrl+M` in notepadqq. Thanks for your new way.

**Comment by lakshmipriya5-coder** [comment]
Thank you nm46nm , i finally solve it with your command

**Comment by shafiqruet** [comment]
Thank you @nm46nm . It is working .
