### ISSUE TITLE
Math rendering does not work in enumeration lines

### ISSUE THREAD

**Issue by gamer01** [notepadqq/notepadqq#642]
**I'm submitting a ...**
```
[x] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**
does not render the equations in enumeration lines

**Expected behavior**
rendering the equation

**Minimal reproduction of the problem with instructions**
```
- jaccard similarity could be used $\sigma(A,B)= {|A\cap B|\over |A\cup B|}$
```
removing the dash in the beginning of the line will cause the correct rendering

**Please tell us about your environment:**
notepadqq 1.4, archlinux

**Comment by danieleds** [comment]
Hi, I'm assuming you're using Markdown?

**Comment by gamer01** [comment]
oh yes, sorry.
