### ISSUE TITLE
Math rendering is triggered on edition of the line

### ISSUE THREAD

**Issue by gamer01** [notepadqq/notepadqq#643]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
when i create a latex formula and edit the line the formula will be rerendered even though i didnt touch the formula

**Expected behavior**
formula is only rerendered when it is actually modified

**Minimal reproduction of the problem with instructions**
$\sigma$ typing something after the formula

**Please tell us about your environment:**
archlinux, notepadqq 1.4, in markdown mode

**Comment by danieleds** [comment]
Thanks, that's for sure one of the next improvements about math rendering. In the meantime, any other feedback (positive or negative) is welcome.
