### ISSUE TITLE
[WebEngine2] Auto Backups do strange things

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#654]
In the webengine2-promise branch, whenever the autobackup timer triggers, the Open dialog get closed.

It's nearly impossible to select a file, because if one opens the "Open file" dialog, it gets closed as soon as the timer fires.

Still not sure about the reason (didn't investigate much yet).

**Comment by JuBan1** [comment]
That makes absolutely no sense. Are you sure its happening as the timer fires?

**Comment by danieleds** [comment]
I tried disabling auto backups and it stops doing that. Very strange indeed. Didn't have time to investigate further though.

**Comment by danieleds** [comment]
Interestingly, this also happens with the "Save as" dialog, but not with the "File has changed on disk, do you want to save anyway?" dialog.

**Comment by Teklad** [comment]
So... I just want to point out (don't shoot me here)...  This doesn't happen on the latest version of QT under Arch Linux.  Possibly a freak of nature QT issue?
