### ISSUE TITLE
Qt version detection, detecting 5.10 as below 5.3

### ISSUE THREAD

**Issue by smeggysmeg** [notepadqq/notepadqq#656]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I open Notepadqq, I receive the error message:

> You are using an old version of Qt (5.10.1) Notepadqq will do its best but some things will not work properly

**Expected behavior**
Unless I'm mistaken, 5.10 is the latest version of Qt. It says it needs 5.3 or above, which 5.10 would qualify.

**Minimal reproduction of the problem with instructions**
1. Have Qt 5.10 as the only version of Qt available
2. Open Notepadqq and receive the error

**Please tell us about your environment:**
Fedora 28 (x64), qt 5.10.1.

**Comment by JuBan1** [comment]
We've fixed this bug about half a year ago. What version of Nqq do you use? The last affected version is 1.2.0 I believe.

**Comment by smeggysmeg** [comment]
Notepadqq version: 0.46.1 from http://sea.fedorapeople.org/sea-devel.repo (listed on notepadqq-packaging Readme)

Obviously very out of date. I'll see if I can find another repo.

**Comment by JuBan1** [comment]
You should! 0.46 is over three years old.

I'll go ahead and close this issue.
