### ISSUE TITLE
Search and replace regex does not match newline to "\n"

### ISSUE THREAD

**Issue by codemon2002** [notepadqq/notepadqq#657]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Shows no results

**Expected behavior**
Matches "\n" with newlines.

**Minimal reproduction of the problem with instructions**
![notepadqq_newlinenotmatching](https://user-images.githubusercontent.com/7032806/39793656-0930771a-530c-11e8-89a8-56c280b7e4ef.png)
See attached picture**
1.  Open Notepadqq
2.  Press ctrl+h
3.  Check Advanced options
4.  Select Regex bullet
5.  Type "\n" in find text input
6.  Press "Select All" button

**Please tell us about your environment:**
Ubuntu 17.10 on Surface Pro 3, out of the box ubuntu, no special customizations

**Comment by JuBan1** [comment]
I'll mark this as closed. Feel free to re-open if there's still an issue.
