### ISSUE TITLE
Testing formatting style.

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#663]
I'm working on a .clang-format file which I'd like to be the guidelines for our formatting rules.  Currently, it preserves single-line returns and keeps most of our current spacing setup intact.

If nobody is opposed I wouldn't mind turning off namespace indentation.  A lot of the time it seems like a magical waste of column space (to me at least).

The rules I currently have imposed are like so:

- Line length no longer than 120 characters
- Line break after function definition
- Allow single line returns after an if statement
- Force a space before and after an if statement (assuming there's a bracket after)

Have a look at what it looks like here:
https://github.com/notepadqq/notepadqq/compare/master...Teklad:testing-1

**Comment by JuBan1** [comment]
Looks pretty good IMO, although I'm unhappy with

    - void Editor::setLanguage(const QString& language)
    + void Editor::setLanguage(const QString &language)
      {
    -     auto& cache = LanguageService::getInstance();
    +     auto &cache = LanguageService::getInstance();

I think we've mostly been using the upper variant except in old code. I'd prefer to keep it like that although it's no biggie.

I also agree with not indenting namespaces.

**Comment by Teklad** [comment]
Alright, have a look now and see if there's any other nitpicky stuff.  I can make modifications as needed up to a certain extent... My main goal was reserving single-line if() statements and what not while still being able to format our code to some kind of standard.

Right now its a fairly large mixed bag of who knows what.  I'm actually working on some rules for cmake-tidy too to help with modernizing a bit of code... (mostly better use of auto, braced initializers, etc.)

**Comment by JuBan1** [comment]
Well, it's a bit unfortunate that the formatting of `NQQ_SETTING` instances in `nqqsettings.h` gets removed. I assume you couldn't tell clang to leave certain macro invocations alone?

**Comment by Teklad** [comment]
I could just have it skip over that macro-heavy file all together, actually... Files like that require special formatting in the first place.

**Comment by Teklad** [comment]
Actually it appears clang has a built-in thing for these cases... i.e.:
```cpp
int formatted_code;
// clang-format off
    void    unformatted_code  ;
// clang-format on
void formatted_code_again;
```

**Comment by Teklad** [comment]
Appears to work well for that particular case.

**Comment by danieleds** [comment]
about `if {` vs `if \n { `, I wouldn't enforce any of those, as I prefer to choose which one to use based on the content of the if (e.g. short vs long). Same thing with functions and methods.

Similarly, sometimes one might want to define a function in a very compact way, for example in a header, like `inline void doSomething() { ... whatever ...}`. I don't want to forbid that.

Totally happy with all your other points.

I'm not familiar with clang-format; in particular:

 * is it possible, for each commit, to only apply the formatting to the actually changed code? So that we don't need to reformat all of our codebase all at once.
 * do you know of any way to automatically check, from a GitHub PR, if the pushed code is compliant with the formatting? I mean something like Travis. (I guess we could include it in Travis?)

**Comment by Teklad** [comment]
Yeah... this is probably something we should have done ages ago but it somehow got put on the backburner along with everything else that should have had importance, lol.

So I believe the "inline" choice is the proper one... allows single-line functions in header files, but uses the normal format in definition files.

The only thing I can really think of that might be an issue is the if statements now.... everything else appears to be proper.

For the rare case you do need to use special formatting on an if block the special comments you can use are posted above.

I'm just curious how you would like this packaged.... I could place it under a "tools" directory in notepadqq along with a script to run it or something... I dunno.

**Comment by Teklad** [comment]
https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/git-clang-format  we might could use this in order to not have to do it all at once.
