### ISSUE TITLE
I just need to know how to show the menu bar again after accidentally hiding it (using the menu bar)

### ISSUE THREAD

**Issue by swbanks** [notepadqq/notepadqq#673]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I hid the menu bar and have no way to show it again

**Expected behavior**
I can see the menu bar

**Minimal reproduction of the problem with instructions**
I clicked 'hide menu bar'

**Please tell us about your environment:**
Ubuntu Linux

**Comment by swbanks** [comment]
I did originally search google+ and found this post but no responses: https://plus.google.com/114735841289743708407/posts/CwbzCzRdqRe

**Comment by JuBan1** [comment]
CTRL+M will do it.

Perhaps we should add a notification when the user hides the bar- you're not the first one it happened to.

**Comment by swbanks** [comment]
Thanks for the quick response!

**Comment by solonovamax** [comment]
> CTRL+M will do it.
> 
> Perhaps we should add a notification when the user hides the bar- you're not the first one it happened to.

+1 on this. And PLEASE put it somewhere in the docs. I was trying to figure out how to undo that and started looking through the source code files and STILL couldn't figure it out. Finally I found this issue though, and got it working again. I couldn't even use Alt + G to open the settings menu item. It would be nice if there was a tickbox to restore it on the toolbar. (Opening a separate issue for that one.)

Yeah, I know it's a necropost, but whatever.
