### ISSUE TITLE
Regression in latest version of QT.

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#699]
Looks like they changed something about parallel jobs in the latest version of QTWebEngine.  This issue does not come up every time, but if I restart notepadqq a few times I get spammed with javascript errors due to some of our functions running before JS is ready.

Looks like we'll need to modify our code a bit to work properly again.

```bash
^[[A[justin@azure notepadqq]$ ./out/release/bin/notepadqq 
qt5ct: using qt5ct plugin
[0605/113539.149432:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.glOFRFB3 (deleted)
  Error: No such file or directory
[0605/113539.149480:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/justin/#28709815 (deleted)
  Error: No such file or directory
qt5ct: D-Bus global menu: no
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: CodeMirror is not defined
js: Uncaught ReferenceError: UiDriver is not defined
```

**Comment by JuBan1** [comment]
That's Qt 5.11?

[This](http://code.qt.io/cgit/qt/qtwebengine.git/tree/dist/changes-5.11.0/?h=v5.11.0) the QtWebEngine's change log for 5.11, and [here](http://code.qt.io/cgit/qt/qtwebview.git/tree/dist/changes-5.11.0/?h=v5.11.0) is te one for QtWebView. 

Not sure if that's of any use- I couldn't see anything suspicious. Does this issue stop CodeMirror from working, or any issues to crop up (like the first few requests not being answered), or is it just a nuisance?

**Comment by Teklad** [comment]
Occasionally it'll prevent notepadqq from starting.  It seems to be completely random as to how many errors it spits out and whether Notepadqq launches successfully or not.  But yes, Qt 5.11.

**Comment by Teklad** [comment]
I believe the upgrade to the latest chromium backend is the actual issue... something in chromium upstream changed that caused this behavior, not QWebEngine itself.

**Comment by JuBan1** [comment]
And here we thought transitioning to QWebEngine was supposed to *fix* our problems.

**Comment by Teklad** [comment]
Yea this is why I'd prefer a native widget that isn't at the mercy of browser circle jerking.  There's just to many variables involved with those technologies. I'm sure its a simple fix but considering the young age of QWebEngine I'm sure issues like these will pop up very often.

**Comment by JuBan1** [comment]
Yep; I picked up work on OTE again after a hiatus, and integrated the KSyntaxHightlighting component. Now I'm in the process of making it work with nqq-master (which means ripping out all the asynch stuff again...). Once I'm done with that I'd like to get some help bug testing if you're up to.

**Comment by Teklad** [comment]
Definitely. Just give me a mention when you're ready and I'll give it a go and help fix any bugs I find as well.
