### ISSUE TITLE
Ctrl+D now deletes line

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#701]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Ctrl+D now deletes a line, in previous versions it duplicated a line.
However in the menu (Edit->Line Operations) it still says "Duplicate Line (Ctrl+D)"

**Expected behavior**
Should duplicate a line.

**Minimal reproduction of the problem with instructions**
Guess what?

**Please tell us about your environment:**
OS: Ubuntu 18.04
Qt: 5.10.1 (local installation from the Qt online installer)
Nqq: 1.4.8+git20180605 (built from source)

**Comment by danieleds** [comment]
This seems to me to be fixed in the current master branch, @darealshinji can you confirm?

**Comment by darealshinji** [comment]
Yes, it's fixed (using snap version from edge branch).
