### ISSUE TITLE
Huge statusbar on macOS

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#708]
The status bar on macOS has a quite large height:

Before:
<img src="https://camo.githubusercontent.com/58c5af2e7bd00bf00fc2c9f42e754203b5d2e151/68747470733a2f2f6e6f746570616471712e636f6d2f5f7374617469632f73637265656e73686f74732f6d61636f732e706e67">

Now:
<img width="710" alt="screen shot 2018-06-10 at 22 32 14" src="https://user-images.githubusercontent.com/402652/41206047-2f118be8-6cfe-11e8-973f-799b4f01626f.png">

In addition, clicking labels creates some glitches (text disappears on mousedown and no menu appears)

**Comment by danieleds** [comment]
Strange enough, it all seem to be fixed (height and glitches) if I assign

    btn->setStyleSheet("* {background: red;}");

to the QPushButtons.

Still investigating.

**Comment by Teklad** [comment]
Possibly related: https://bugreports.qt.io/browse/QTBUG-60018

There appears to be a work-around provided if you want to give it a go.  The very last comment.

**Comment by Teklad** [comment]
You might also try setting minHeight to a lower number for the push buttons and see if that resolves at least the height issue without messing with the stylesheet.

**Comment by danieleds** [comment]
Thanks.

By the way, is it normal that in MainWindow::configureStatusBar() the `minWidth` parameter in the lambda is always ignored?

**Comment by Teklad** [comment]
Yea I believe I just forgot to remove that as part of the refactoring process... it was used initially until I managed to find a better way to handle it.  It should be able to safely be removed.
