### ISSUE TITLE
Make error: include/EditorNS/editor.h:391:29: error: ‘QPrinter’ was not declared in this scope

### ISSUE THREAD

**Issue by elosantos** [notepadqq/notepadqq#716]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Making the program fails with the following error:

include/EditorNS/editor.h:391:29: error: ‘QPrinter’ was not declared in this scope
  void print(std::shared_ptr<QPrinter> printer);
include/EditorNS/editor.h:391:37: error: template argument 1 is invalid
  void print(std::shared_ptr<QPrinter> printer);

**Expected behavior**

Make without error

**Minimal reproduction of the problem with instructions**

This is the output of make:

root@HP-Debian:/home/emilio/notepadqq# make
cd src/ui/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/emilio/notepadqq/src/ui/ui.pro PREFIX=/usr QMAKE_CXX=c++ 'QMAKE_CXXFLAGS= ' QMAKE_LFLAGS= 'LRELEASE=/usr/bin/qtchooser -run-tool=lrelease -qt=5' CONFIG+= -o Makefile ) && make -f Makefile 
make[1]: se entra en el directorio '/home/emilio/notepadqq/src/ui'
(cd "/home/emilio/notepadqq/src/ui" && rm -rf "../../out/release/lib/../appdata/editor" && cd "../editor" && make DESTDIR="../../out/release/lib/../appdata/editor")
make[2]: se entra en el directorio '/home/emilio/notepadqq/src/editor'
mkdir -p "../../out/release/lib/../appdata/editor"
cp -r classes styles features app.js index.html init.js Languages.json "../../out/release/lib/../appdata/editor"/
mkdir -p "../../out/release/lib/../appdata/editor"/libs
cp -r libs/jquery "../../out/release/lib/../appdata/editor"/libs/jquery/
cp -r libs/MathJax "../../out/release/lib/../appdata/editor"/libs/MathJax/
cp -r libs/require.js "../../out/release/lib/../appdata/editor"/libs/require.js/
# Call CodeMirror makefile passing DESTDIR as absolute path, so we have no problems with cd-ing to libs
make -C libs -f Makefile-codemirror DESTDIR="/home/emilio/notepadqq/out/release/appdata/$(basename "../../out/release/lib/../appdata/editor")"/libs/codemirror
make[3]: se entra en el directorio '/home/emilio/notepadqq/src/editor/libs'
mkdir -p "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"
cd codemirror && cp -r addon keymap lib mode theme LICENSE "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"/
# Clean unnecessary files within "mode"
find "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/ -type f -name '*.html' -exec rm -f {} +
find "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/ -type f -name 'test.js' -exec rm -f {} +
cd "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/m4/ && rm -f *.txt *.sh *.in
make[3]: se sale del directorio '/home/emilio/notepadqq/src/editor/libs'
make[2]: se sale del directorio '/home/emilio/notepadqq/src/editor'
(cd "/home/emilio/notepadqq/src/ui" && rm -rf "../../out/release/lib/../appdata/extension_tools" && cd "../extension_tools" && make DESTDIR="../../out/release/lib/../appdata/extension_tools")
make[2]: se entra en el directorio '/home/emilio/notepadqq/src/extension_tools'
mkdir -p "../../out/release/lib/../appdata/extension_tools"
cp -r node_modules install.js pack.js package.json readmanifest.js "../../out/release/lib/../appdata/extension_tools"/
make[2]: se sale del directorio '/home/emilio/notepadqq/src/extension_tools'
(/usr/bin/qtchooser -run-tool=lrelease -qt=5 "/home/emilio/notepadqq/src/ui/ui.pro")
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_de.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_es.qm'...
    Generated 365 translation(s) (365 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_fr.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_hu.qm'...
    Generated 448 translation(s) (448 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_it.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_ja.qm'...
    Generated 344 translation(s) (344 finished and 0 unfinished)
    Ignored 1 untranslated source text(s)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_pl.qm'...
    Generated 348 translation(s) (348 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_pt.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_ru.qm'...
    Generated 328 translation(s) (326 finished and 2 unfinished)
    Ignored 17 untranslated source text(s)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_sl.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_sv.qm'...
    Generated 359 translation(s) (359 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_uk.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_zh.qm'...
    Generated 448 translation(s) (448 finished and 0 unfinished)
(cd "/home/emilio/notepadqq/src/ui" && mkdir -p "../../out/release/lib/../bin/" && cp -f "../../support_files/launch/notepadqq" "../../out/release/lib/../bin/" && chmod 755 "../../out/release/lib/../bin/notepadqq")
c++ -c -O2 -std=gnu++1y -Wall -W -Wold-style-cast -D_REENTRANT -fPIC -DQT_NO_URL_CAST_FROM_STRING -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ilibs/qtpromise/include -Ilibs/qtpromise/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebChannel -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I../../out/build_data -I../../out/build_data -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o ../../out/build_data/main.o main.cpp
In file included from main.cpp:1:0:
include/EditorNS/editor.h:391:29: error: ‘QPrinter’ was not declared in this scope
  void print(std::shared_ptr<QPrinter> printer);
                             ^~~~~~~~
include/EditorNS/editor.h:391:37: error: template argument 1 is invalid
  void print(std::shared_ptr<QPrinter> printer);
                                     ^
Makefile:1114: fallo en las instrucciones para el objetivo '../../out/build_data/main.o'
make[1]: *** [../../out/build_data/main.o] Error 1
make[1]: se sale del directorio '/home/emilio/notepadqq/src/ui'
Makefile:43: fallo en las instrucciones para el objetivo 'sub-src-ui-make_first'
make: *** [sub-src-ui-make_first] Error 2

**Please tell us about your environment:**

Operating Systema: Linux version 4.9.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)

The output of the configure command is:

_root@HP-Debian:/home/emilio/notepadqq# ./configure --prefix=/usr
checking for QT5 qmake... /usr/bin/qtchooser -run-tool=qmake -qt=5
checking for lrelease... /usr/bin/qtchooser -run-tool=lrelease -qt=5
checking for c++... /usr/bin/c++
checking whether c++ compiler builds test program... ok
checking whether c++ compiler supports -std=c++0x... ok
checking whether compiled test program works... ok
checking for make... /usr/bin/make
checking for pkg-config... /usr/bin/pkg-config
checking for Qt5Core library... -lQt5Core
checking for Qt5Gui library... -lQt5Gui -lQt5Core
checking for Qt5Network library... -lQt5Network -lQt5Core
checking for Qt5WebEngine library... -lQt5WebEngine -lQt5WebEngineCore -lQt5Quick -lQt5Gui -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Core
checking for Qt5Widgets library... -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5WebEngineWidgets library... -lQt5WebEngineWidgets -lQt5WebEngineCore -lQt5WebChannel -lQt5Widgets -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core
checking for Qt5PrintSupport library... -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5Svg library... -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5WebSockets library... -lQt5WebSockets -lQt5Network -lQt5Core
checking for Qt5WebChannel library... -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Core
generate Makefile... Info: creating stash file /home/emilio/notepadqq/.qmake.stash
done
_

**Comment by JuBan1** [comment]
Seems like it's just a missing include. This sometimes pops up due to different libstd/qt library versions.

I pushed a patch that should fix this. You can either fetch the current master again or [apply the one-liner yourself](https://github.com/notepadqq/notepadqq/commit/09ad7c0719e8ccd1e39a51c4f9c5dd1dbb9f200f).

I'll leave the dir paths and unneeded files in mode/ alone for now since we'll probably make some larger changes to those things soon-ish anyways.

**Comment by elosantos** [comment]
The patch resolves this issue although the make give another error later. I close this issue an open another one with the new error.
Thanks a lot.
