### ISSUE TITLE
Qt 5.10.1 <= Qt 5.3 warning

### ISSUE THREAD

**Issue by michaelolson01** [notepadqq/notepadqq#721]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Having Qt 5.10.1 installed, and starting notepadqq, it says I need to upgrade my version of Qt to at least 5.3.0

**Expected behavior**
Not telling me I need a newer version of Qt, when I already have a newer version.

**Minimal reproduction of the problem with instructions**
To reproduce, install Qt 5.10.1 or above, start notepadqq.

**Please tell us about your environment:**
Debian 10, Qt v5.10.1, Notepadqq v1.2.0

**Comment by danieleds** [comment]
Thank you for the report, this is a known bug which has been fixed in one of the following releases: if you upgrade nqq it should be fine.

Closing but feel free to comment if you have any question.
