### ISSUE TITLE
Better encoding auto detection

### ISSUE THREAD

**Issue by boogiefromzk** [notepadqq/notepadqq#730]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Unable to quickly switch language of the file.

**Expected behavior**

The best solution: add language auto detection after reload from disk and reload with another encoding. And add encoding auto detection.
The other solution: add a button to menu that auto detects the language. Add a way to add buttons for switching directly to a language to the toolbar.

**Minimal reproduction of the problem with instructions**

The use case: I have a project where files are windows-1251 encoded, so when I open a file it has syntax highlight, but wrong encoding. I reload the file with that encoding and I loose the syntax highlight. Now I have to go to languages/P/PHP for example. Too many things to do to start working with a file.

**Please tell us about your environment:**

OpenSuse 15.0, Qt 5.9.4, Notepadqq 1.4.0

**Comment by boogiefromzk** [comment]
After fixing issue #729 there is only one thing left: encoding auto detection.
Thanks in advance!

**Comment by boogiefromzk** [comment]
I made a short research, this tool https://github.com/chardet/chardet works great on my tests, while "file -b --mime-encoding ./sql.php" failed to guess windows-1251 encoding.

**Comment by Teklad** [comment]
I looked at chardet a while back as a viable way to detect encoding for NQQ.  It's very accurate and can detect character encoding a lot better than the way we're doing it now.  At some point I forgot about it though.

I wouldn't be against replacing our clunky detection with a well made library like this.

**Comment by danieleds** [comment]
@Teklad yep, I was thinking the same. Requiring python for notepadqq seems overkill, but if we can find something in c++ I'm totally for it.

**Comment by Teklad** [comment]
Just for reference... this was originally something developed by Mozilla.  The original library is C/C++:
https://github.com/Joungkyun/libchardet

I didn't feel like looking for the original repository.  I can implement this next weekend if nobody else wants to.

**Comment by Teklad** [comment]
Nope... I found it:
https://www.freedesktop.org/wiki/Software/uchardet/

**Comment by Teklad** [comment]
Okay, this is the last comment.  It looks like the library is written in C.  I'll need to create a C++ interface for it to make it easier to work with.  Outside of that it's overall a very good library.

**Comment by JuBan1** [comment]
Not sure if we're currently doing anything at all to detect codecs, but Qt has some built-in facilities for that via [QTextCodec::codecForUtfText](https://doc.qt.io/qt-5/qtextcodec.html#codecForUtfText). 

Aside from that, this part ` I reload the file with that encoding and I loose the syntax highlight. ` is a separate bug to fix.

**Comment by Teklad** [comment]
I'm almost certain we're already checking encoding using that method in docengine, if I recall correctly.  It just appears to not work for this particular file for some unknown reason.

I double checked this file using uchardet and it does indeed return Windows-1251 as it should.  I'm not sure how QT's built-in encoding detecting works but this seems to work just a bit better.  That's assuming we're using codecForUtfText properly, of course. :p

**Comment by danieleds** [comment]
The file reloading bug is fixed in 4457fc93e

**Comment by danieleds** [comment]
I'm changing the title of this issue to make clear that we're now talking about the encoding.

**Comment by JuBan1** [comment]
Yea, we're already doing [codepage detection](https://github.com/notepadqq/notepadqq/blob/master/src/ui/docengine.cpp#L816). But looking at Qt's source it seems it's [limited to UTF8 through 32](https://code.woboq.org/qt5/qtbase/src/corelib/codecs/qtextcodec.cpp.html#_ZN10QTextCodec15codecForUtfTextERK10QByteArrayPS_) based on their BOM. Failing that, it returns Latin1, which is what probably happens in our case I think. 

I guess that chardetect library uses heuristics to guess codepages since there's no surefire way of finding that out.

**Comment by Teklad** [comment]
So uchardet uses CMake for building.  The question is how should we go about including it?  I'd prefer to add it as a build dependency to ensure its always available on a system, but the options are either to hack the build step into qmake, or switch to using cmake.

Alternatively we can simply require the user install that library on their system, but the compile-time dependency list is already quite high as it is.

I'm fine with whatever method, just need to clarify prior to pulling this off.

**Comment by JuBan1** [comment]
I don't think we should pull in the sources. Referencing the package as a compile-time dependency sounds just fine.

I took a peak at some official repos:

* [Ubuntu](https://packages.ubuntu.com/trusty/libuchardet-dev) :+1: 
* [Debian](https://packages.debian.org/stretch/libuchardet-dev) :+1: 
* [OpenSUSE](http://rpm.pbone.net/index.php3/stat/4/idpl/29874185/dir/opensuse_13.x/com/libuchardet-devel-0.0.1-2.1.i586.rpm.html) :+1: 
* [RHEL](http://rpmfind.net/linux/RPM/epel/7/x86_64/Packages/u/uchardet-devel-0.0.6-1.el7.x86_64.html) - in extas :+1: 
* [Arch](https://www.archlinux.org/packages/extra/x86_64/uchardet/) :+1: 
* [Mint](https://community.linuxmint.com/software/view/libuchardet-dev), only in Community but that should be okay :+1: 
* [Fedora](http://rpmfind.net/linux/RPM/fedora/27/x86_64/u/uchardet-devel-0.0.6-4.fc27.x86_64.html) :+1: 
* [CentOS](https://centos.pkgs.org/7/epel-x86_64/uchardet-devel-0.0.6-1.el7.x86_64.rpm.html) :+1:

**Comment by danieleds** [comment]
It is also available on [macOS](http://brewformulas.org/Uchardet) 👍 via brew, so that's great.
