### ISSUE TITLE
missing packages Debian 9.x

### ISSUE THREAD

**Issue by blub4747** [notepadqq/notepadqq#739]
Hello,
Iam trying to build notepadqq under Debian 9.x
When I am trying to run ./configure
I do get a message telling me that the follwing packages are misssing.

checking for QT5 qmake... /usr/bin/qtchooser -run-tool=qmake -qt=5
checking for lrelease... /usr/bin/qtchooser -run-tool=lrelease -qt=5
checking for c++... not found!
Can you please help me locate them ?

Thank you, blub4747

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

**Comment by JuBan1** [comment]
You might be missing the gcc package. If that's not the case, the package might not provide you with the needed `c++` binary. Try running `CXX=gcc` before `./configure`. It should explicitly tell the script to use `gcc` for compilation.

**Comment by blub4747** [comment]
I just tried the following commands

> user@debian:~/notepadqq$ CXX=gcc 
user@debian:~/notepadqq$ ./configure
checking for QT5 qmake... /usr/bin/qtchooser -run-tool=qmake -qt=5
checking for lrelease... /usr/bin/qtchooser -run-tool=lrelease -qt=5
checking for c++... not found!
and once again no luck.

**Comment by Teklad** [comment]
It should actually be:
```bash
CXX=g++ ./configure
```

You can also use:
```bash
which g++
```

This should locate the binary if it exists on your system.  If it does not, you're missing some stuff to properly build notepadqq.  I recommend installing "build-essential" through apt to get a working base for compiling software.

**Comment by danieleds** [comment]
Closing as this doesn't seem like a bug.
