### ISSUE TITLE
Notepadqq non-stop shows a bar telling the user 'This file is indented with spaces ...'

### ISSUE THREAD

**Issue by quantuumsnot** [notepadqq/notepadqq#755]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```

**Current behavior**
Notepadqq non-stop show a bar telling the user 'This file is indented with spaces, but your current settings specify to use tabs'. Hitting on 'Use spaces' or 'Ignore' doesn't solve the problem. In fact I setup first the indentation to be 'Tab size: 2' and checked 'Use spaces instead of tabs' before going to edit any files.

**Expected behavior**
App to stop telling me that I'm using tabs ...

**Minimal reproduction of the problem with instructions**
Just installed it, set the tab size and using spaces instead of tabs, hit Apply button then OK then closed and started the app again

**Please tell us about your environment:**
Ubuntu 18.04.1 LTS x64, GNOME 3.28.2, Qt version 5.5.1, Notepadqq v1.4.8

**Comment by TinyJune** [comment]
A fix that I did was I went into the config files and changed the values manually. Find the Notepadqq.ini file and change the following:
Replace all
UseDefaultSettings=true -> UseDefaultSettings=false
IndentWithSpaces=false -> IndentWithSpaces=true

I think there is something wrong with applying and saving the settings but this is what I came up with for now.

**Comment by quantuumsnot** [comment]
Good idea, thought the same and did it. Not working :(

**Comment by danieleds** [comment]
If you are using the snap package as I assume, the fix is now out. Sorry for the inconvenience.

**Comment by kas-cor** [comment]
A fix that. Find the Notepadqq.ini file and change the following:
WarnForDifferentIndentation=true -> WarnForDifferentIndentation=false
