### ISSUE TITLE
Feature request: disable line numbers

### ISSUE THREAD

**Issue by lonix1** [notepadqq/notepadqq#756]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

Shows line numbers.

**Expected behavior**
Has an option for disabling line numbers.

**Please tell us about your environment:**
Ubuntu 18, notepadqq 1.4.2

**Comment by lonix1** [comment]
@JuBan1 Thanks. When do you think this will be released?

**Comment by JuBan1** [comment]
That I don't know. We haven't had a new release in a while and the project's very inactive at the moment. It'll probably be quite a while, unless you build-from-source.
