### ISSUE TITLE
cannot open the file using the context menu when soft link (ln -s) is set to file location

### ISSUE THREAD

**Issue by linuxiaobai** [notepadqq/notepadqq#770]
**Describe the bug**
cannot open the file using the right click context menu when soft link (ln -s) is set to file location 
**To Reproduce**
1. Suppose the file aa.txt is under "home/user/doc/", and I added soft link using "ln -s home/user/ /my"
2. Go to '/my/doc/' folder
3. Right Click on the file aa.txt and choose open by notepadqq

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu [16.04.5]
 - Installation type [snap]
 - Qt version [5.5.1]
 - Notepadqq version [1.4.8]

**Additional context**

**Comment by JuBan1** [comment]
I tested it under the same environment and it works fine for me

![screenshot_20180923_110314](https://user-images.githubusercontent.com/4319621/45926188-59211880-bf20-11e8-9f9f-b62eea1f1bb0.png)

What error do you get?

**Comment by JuBan1** [comment]
Nevermind. It does fail using the version that `snap` downloads. I've had a locally compiled version with some patches inside.

For the record: the text file is opened in a dirty state, with no contents shown, and no option to "Reload from Disk".

The good bit: it's probably already fixed somewhere along the road of implementing #704 because that doesn't cause the issue.

**Comment by JuBan1** [comment]
@danieleds I did. Still failed (see previous comment).

**Comment by danieleds** [comment]
@JuBan1 weird... was it an absolute symlink or a relative one?

**Comment by JuBan1** [comment]
Absolute. You can see the commands I used in the screenshot.

**Comment by linuxiaobai** [comment]
> Nevermind. It does fail using the version that `snap` downloads. I've had a locally compiled version with some patches inside.
> 
> For the record: the text file is opened in a dirty state, with no contents shown, and no option to "Reload from Disk".
> 
> The good bit: it's probably already fixed somewhere along the road of implementing #704 because that doesn't cause the issue.

Thanks for your quick turnaround. Yes, exactly this is the issue I encountered. For now we just navigate to the absolute path (~/doc) in the Nautilus to open my file instead of the relative path (/my/doc).

**Comment by danieleds** [comment]
This appears to be already fixed in the current development version.

You can install it with `sudo snap install --classic --edge notepadqq`, but it is BETA and thus may be unstable. The fix will be available in the upcoming release.
