### ISSUE TITLE
crazy scrolling

### ISSUE THREAD

**Issue by schumischumi** [notepadqq/notepadqq#781]
**Describe the bug**
When I scroll down (with mouse wheel or arrow down key) a file that does not fit in one page, the scrolling gets fuzzy and often jumps or decides to scroll up instead of down.
Maybe similar to the issue https://github.com/notepadqq/notepadqq/issues/461#issue-238393898

**To Reproduce**
Open a "big" file (more than 2-300 lines in my case) and scroll down with the arrow down key or the mouse wheel.

**Expected behavior**
Normal scrolling behavior.

**Screenshots**
[MP4 screencapture](https://drive.google.com/file/d/1glEMoIUMVcZ0dMDUdAQr4HYj4Z7YvLYs/view?usp=sharing)

**Environment (please complete the following information):**
 - OS: Antergos Deepin
 - Installation type: distro packages
 - Qt version: 5.11.2
 - Notepadqq version: 1.4.8

**Additional context**
Two Monitors: 4k Monitor (3840x2160) and FullHD (1920x1200) extended. Both have the problem.
When starting notepadqq via terminal I get these messages:

> QApplication: invalid style override passed, ignoring it.
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile

**Comment by schumischumi** [comment]
Thanks for your response. Compiling the current master fixed the error.

**Comment by Telonko** [comment]
v2.0.0 beta still has the problem with scrolling
Qt installed 5.14.0
