### ISSUE TITLE
Notepadqq can't show the first number in the first column

### ISSUE THREAD

**Issue by zhmh163** [notepadqq/notepadqq#782]
**I generate a txt file from c++ with many columns. But the first column can't show properly in notepadqq. Other python and data files can be show very well. Anyone can help me to solve it?**
![qq 20181009160519](https://user-images.githubusercontent.com/18723361/46674872-82f36400-cbdd-11e8-8228-a4f6a6ea2792.png)

**Environment :**
 - OS: Ubuntu 18.04
 - Installation type :snap 
 - Qt version: 5.5.1
 - Notepadqq version: v1.4.8

**Comment by danieleds** [comment]
Fixed on master

**Comment by roelofz** [comment]
It looks like it has returned...

Lab31 laptopstandaard

Opvouwbaar
229

![afbeelding](https://github.com/notepadqq/notepadqq/assets/11368363/5d81f0c7-7892-475d-923b-edf7b8dad709)
