### ISSUE TITLE
Wrap document Tabs

### ISSUE THREAD

**Issue by samuraibrian** [notepadqq/notepadqq#783]
[X ] feature request

I typically have 20, or more documents on the go. It's quite tedious to have to use the left/right Tabs arrow to move around. Would be great to have option to display tabs in multiple rows and/or have a Document Selector pane. (Or even list documents under the Window menu.)

Cheers, Jon
Ubuntu 18.04, Notepadqq v1.4.8

**Comment by JuBan1** [comment]
I'll close this as it's a dupe of #683.

The normal Qt tab widget doesn't support this unfortunately. We'd have to provide our own. I might give it a try since it's been requested a few times but it's a bit more involved than just setting an option.

**Comment by jhaberly** [comment]
I would LOVE to see this feature as well. This thread is a couple years old. Any updates?
