### ISSUE TITLE
On mac os 10.14 , cannot start.

### ISSUE THREAD

**Issue by 9527KGG** [notepadqq/notepadqq#790]
**Describe the bug**
On mac os, cannot start. Hung

**To Reproduce**
Download img file. Drop&drop to /Applications.
Double click to start 

**Expected behavior**
notepad can start

**Screenshots**
Hung

**Environment (please complete the following information):**
Mac 10.14
Notepadqq 1.4.8

**Additional context**
When I start the app from command line, I see
_Missing icon:  "edit-clear"
Missing icon:  "go-previous"
Missing icon:  "go-next"
Missing icon:  "go-bottom"
Missing icon:  "view-refresh"
Missing icon:  "document-open-recent"
Missing icon:  "application-exit"
Missing icon:  "edit-delete"
Missing icon:  "edit-select-all"
Missing icon:  "go-next"
Missing icon:  "go-previous"
Missing icon:  "go-jump"
Missing icon:  "view-fullscreen"
Missing icon:  "system-run"
Missing icon:  "window-new"
Missing icon:  "help-about"
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
[9701:83459:1022/093207.102715:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[9701:83459:1022/093207.103266:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[9701:83459:1022/093207.103505:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[9701:83459:1022/093207.106808:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[9701:83459:1022/093207.107129:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[9701:83459:1022/093207.107260:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/notepadqq.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found_

**Comment by JuBan1** [comment]
Did it work for you before upgrading to 10.14, or did you only try on 10.14?

**Comment by 9527KGG** [comment]
For that machine, I only tried 10.14. 
Today, I grabbed another machine, which is 10.12. However, nqq still hung during startup. Any suggestion? Do I need run any special cmd before run the app?

**Comment by JuBan1** [comment]
I can't really tell you, I don't own a Mac. @danieleds does, and he's done most of the work to make Nqq compatible with macOS. Though he's rather busy the last weeks.

It sounds like the image doesn't include the QtWebEngine module which would be a problem on our part. If you want to try to compile Nqq from source we have [build instructions](https://github.com/notepadqq/notepadqq/wiki/Compiling-Notepadqq-on-macOS) for macOS.

**Comment by 9527KGG** [comment]
Thanks. Seems mac version is not usable at all. I would like prefer to wait and glad to verify once the issue has been fixed.

**Comment by danieleds** [comment]
Hmm, it seems that some of the links are pointing outside of the package.

You should be able to solve this by simply running `brew install qt`. It's a workaround, but should work.

That's something that we need to fix though. Keep in mind that is still experimental (but I happily use it regularly on macOS too).

Let us know

**Comment by danieleds** [comment]
Or maybe not, since now Qt is at version 5.11.2 and your log suggests that nqq is looking for 5.11.1 specifically. It's still worth a try though.

**Comment by 9527KGG** [comment]
On 10.14, I ran brew install qt. And /usr/sbin/system_profiler SPFrameworksDataType shows:

    QTKit:

      Version: 7.7.3
      Obtained from: Apple
      Last Modified: 10/18/18, 8:29 PM
      Kind: Intel
      64-Bit (Intel): Yes

Yes, I understand it's experimental. But I wish it's usable first :)

Thanks

**Comment by 9527KGG** [comment]
Finally, I gave up NQQ and switch to gneay ^_^.

I've unsubscribed the thread. Free free to close the issue if it no longer repro.
