### ISSUE TITLE
Feature request: please add "Advanced Replace"

### ISSUE THREAD

**Issue by 9527KGG** [notepadqq/notepadqq#791]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```
Please add "Advanced Replace". Basically allow user to do replacement in all opened files or on the file system.

**Please tell us about your environment:**

Ubuntu 18 LTs
Notepadqq: 1.4.8

**Comment by JuBan1** [comment]
That's possible using the Advanced Search Dialog. You can open it from the Menu (`Search -> Advanced Search` or something like that) or, I think, using Shift+CTRL+F. 

In that panel you can search in all open documents, or all files on the file system. 

![img](https://camo.githubusercontent.com/ea9479850babc6183377fbdc24fb3d56b8d2691a/687474703a2f2f692e696d6775722e636f6d2f466474467442392e706e67)

Once you searched, you get a list of search results and an option to replace (in the panel's header bar):

![img2](https://camo.githubusercontent.com/163e02d9901053312a9e82836e4c77b1eea98e2e/687474703a2f2f692e696d6775722e636f6d2f484d44557a39592e706e67)

**Comment by 9527KGG** [comment]
Oh~. Thanks for pointing out. Really appreciate.
