### ISSUE TITLE
failed to create symbolic link

### ISSUE THREAD

**Issue by Sorky** [notepadqq/notepadqq#797]
**Describe the bug**
Messages output on starting...
ln: failed to create symbolic link '.../snap/notepadqq/855/snap/notepadqq/855/Desktop': No such file or directory
ln: failed to create symbolic link '.../snap/notepadqq/855/snap/notepadqq/855/Downloads': No such file or directory
ln: failed to create symbolic link '.../snap/notepadqq/855/snap/notepadqq/855/Music': No such file or directory
ln: failed to create symbolic link '.../snap/notepadqq/855/snap/notepadqq/855/Pictures': No such file or directory
ln: failed to create symbolic link '.../snap/notepadqq/855/snap/notepadqq/855/Videos': No such file or directory
ln: failed to create symbolic link '.../snap/notepadqq/855/snap/notepadqq/855/Templates': No such file or directory

**To Reproduce**
Clean install: sudo snap install --classic notepadqq

**Expected behavior**
No logs

**Environment (please complete the following information):**
 - OS: = Ubuntu 18.04
 - Installation type = snap
 - Qt version = 5.5.1
 - Notepadqq version = 1.4.8

- WM = awesome

**Additional context**

Q: What's with the 855?

**Comment by Sorky** [comment]
Seems to be a stupid nesting issue

Workaround...

Create symlink `/home/<user>/snap/notepadqq/855/snap -> /home/<user>/snap`

**Comment by Sorky** [comment]
Seems to have been a not -"-classic" issue

**Comment by snarum-NIS** [comment]
I'm not sure what you mean by "a not -'-classic' issue" but this is not resolved for me

**Comment by awaisdeveloper** [comment]
> I'm not sure what you mean by "a not -'-classic' issue" but this is not resolved for me

How you can resolve this issue?

**Comment by SylwesterBogusiak** [comment]
Similar issue with notepadqq and ln to create a symlinks.

https://github.com/notepadqq/notepadqq/issues/806

`sudo notepadqq`

gives these errors in terminal.

mkdir: cannot create directory '/run/user/0': Permission denied ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Documents': No such file or directory ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Desktop': No such file or directory ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Downloads': No such file or directory ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Music': No such file or directory ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Pictures': No such file or directory ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Videos': No such file or directory ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Templates': No such file or directory Authorization required, but no authorization protocol specified QXcbConnection: Could not connect to display :0 Aborted 

Can anybody help?
