### ISSUE TITLE
Crash at maximize

### ISSUE THREAD

**Issue by kraamis** [notepadqq/notepadqq#801]
When I trying to maximize window to full screen occur crash. And I can't correct close program's window.

Console log

kraamis@debian [~]$ notepadqq
nouveau: kernel rejected pushbuf: Нет такого файла или каталога
nouveau: ch5: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch5: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch5: buf 00000001 00000006 00000004 00000000 00000004
Received signal 11 SEGV_MAPERR 000000000080
#0 0x7fe46c50336e <unknown>
#1 0x7fe46c503480 <unknown>
#2 0x7fe46c503ab7 <unknown>
#3 0x7fe4691c58e0 <unknown>
#4 0x7fe4478b2089 <unknown>
#5 0x7fe4478c092c <unknown>
#6 0x7fe4478c2ef0 <unknown>
#7 0x7fe44750f44f <unknown>
#8 0x7fe46a4e56a2 QSGBatchRenderer::Renderer::renderBatches()
#9 0x7fe46a4eaf02 QSGBatchRenderer::Renderer::render()
#10 0x7fe46a4db52c QSGRenderer::renderScene()
#11 0x7fe46a4db9bf QSGRenderer::renderScene()
#12 0x7fe46a515380 QSGDefaultRenderContext::renderNextFrame()
#13 0x7fe46a577370 QQuickWindowPrivate::renderSceneGraph()
#14 0x7fe46a634028 QQuickRenderControl::render()
#15 0x7fe468a9a0d2 <unknown>
#16 0x7fe468a9a2a6 <unknown>
#17 0x7fe4694fcafb QObject::event()
#18 0x7fe470d23c5b QWidget::event()
#19 0x7fe468a9de2d QQuickWidget::event()
#20 0x7fe471285b50 <unknown>
#21 0x7fe470ce5491 QApplicationPrivate::notify_helper()
#22 0x7fe470cecad0 QApplication::notify()
#23 0x7fe4694d3039 QCoreApplication::notifyInternal2()
#24 0x7fe469524128 QTimerInfoList::activateTimers()
#25 0x7fe469524984 <unknown>
#26 0x7fe4689afc3e g_main_context_dispatch
#27 0x7fe4689afed8 <unknown>
#28 0x7fe4689aff6c g_main_context_iteration
#29 0x7fe469524d13 QEventDispatcherGlib::processEvents()
#30 0x7fe458234851 <unknown>
#31 0x7fe4694d1d0b QEventLoop::exec()
#32 0x7fe4694d9e82 QCoreApplication::exec()
#33 0x562efb7b72d1 main
#34 0x7fe468ce5b17 __libc_start_main
#35 0x562efb7b7a1a _start
  r8: 000000000000005d  r9: 0000000000000078 r10: 0000562efdbe6a20 r11: 0000562efdbbdd90
 r12: 0000562efde3be18 r13: 00007fe42418d1a0 r14: 0000000000000000 r15: 0000562efdbbc200
  di: 00007fe42418d1a0  si: 0000000000000001  bp: 0000562efde3be08  bx: 0000000000000038
  dx: 0000562efde3be18  ax: 0000000000000100  cx: 0000000000000002  sp: 00007ffe71f83c30
  ip: 00007fe4478b2089 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000080
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by Teklad** [comment]
It looks like your graphics driver faulted out over something.  Is there any way you can build from source for us and run the program through gdb so we can get a proper backtrace?  Also, care to share which version of Debian you're using?

Another thing you might try is to use the Nvidia proprietary drivers and see if that helps with the issue.  If it does that's a definite indicator of a possible regression in the graphics driver and/or QT.  If this is the stable build of notepadqq it's got a glaring amount of random stability issues due to QWebKit no longer being supported.

**Comment by kraamis** [comment]
I install Nvidia proprietary drivers  and problem was solved
