### ISSUE TITLE
[Feature Request] AppImage

### ISSUE THREAD

**Issue by zero77** [notepadqq/notepadqq#825]
Can you please provide an AppImage, this is basically just a standalone portable executable for linux, that doesn't require installation.
Thanks

There are different ways to create AppImages:

    Use Open Build Service (OBS)
    Convert existing binary packages (.deb, .rpm, …)
    Bundling your Travis CI builds as AppImages
    Run linuxdeployqt on your Qt application
    Using electron-builder for Electron-based apps
    Create an AppDir manually

Documentation:
https://docs.appimage.org/packaging-guide/ways.html
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by danieleds** [comment]
Thanks, we're discussing about it here: https://github.com/notepadqq/notepadqq/issues/817

Right now I don't have the resources to work on it. It's ok if you want to jump in, just let me know.
