### ISSUE TITLE
cannot open a file in the root directory that starts with _ or . or even symlinks to anything in root

### ISSUE THREAD

**Issue by Sorky** [notepadqq/notepadqq#827]
**Describe the bug**
cannot open a file in a root directory that starts with _ (eg: /_a/file.txt)
cannot even select the dir
also applies to a root directory that starts with .  (eg: /.a/file.txt)

**To Reproduce**
Make a dir in root that starts with _ or .

**Expected behavior**
Browse dir and open, edit, save file

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - Installation type snap [classic]
 - Qt version 5.5.1
 - Notepadqq version 1.4.8

**Additional context**
also fails with "notepadqq /_a/file.xyz" (opens an empty file in an unknown location)

**Comment by JuBan1** [comment]
Works for me on 18.04 and Snap:

![img](https://i.imgur.com/InvbyOU.png)

Have you installed Notepadqq with the classic flag? `snap install --classic notepadqq`.

Snaps sandbox the program and prohibit it from seeing much of the filesystem. By default only `~/` and a few other places can be accessed. Using `--classic` you get access to more-or-less the entire filesystem. Maybe that's what you've been seeing?

**Comment by Sorky** [comment]
> Works for me on 18.04 and Snap:

Sorry my report wasn't as clear as it should have been [now updated]

Can you try /_a/file.txt?

Thanks in advance

PS: My dialog is different so I wonder if that's a factor?

**Comment by Sorky** [comment]
@JuBan1  -  Any further feedback?

**Comment by JuBan1** [comment]
Sorry, I forgot about this one. I tested it with a file with path `/_test/file` and that worked fine too.

I have no idea why we have different file dialogs. I have tried it on Ubuntu with no extra bells or whistles.

So a file in `/a/file.txt` works for you?

**Comment by Sorky** [comment]
Basically yes, however I did some extra tests and it seems weirder than that...

webmin-setup.out opens in root with xfwrite (see bottom right) but opens empty in notepadqq

Made a directory with /abc/xyz.txt and I can't edit that one either [opens blank]

Clue? File open dialog is not in /abc but is in /var/lib/snapd/void


![hpiurm 9](https://user-images.githubusercontent.com/43520033/51888764-7e9cc200-23eb-11e9-9ad9-6b8bf1529a36.PNG)

**Comment by Sorky** [comment]
Trying a refresh...

lsb_release -a
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

uname -a
```
Linux XXX 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
sudo snap remove notepadqq
sudo apt-get remove snapd
sudo apt autoremove --purge snapd
sudo apt-get install snapd
sudo snap install --classic notepadqq
```
2019-01-29T18:11:31+11:00 INFO Waiting for restart...
error: cannot perform the following tasks:
- Mount snap "notepadqq" (855) (snap "notepadqq" is not a classic confined snap)
```
Had to install without --classsic

Still bad

snap info notepadqq
```
name:      notepadqq
summary:   A Notepad++-like editor for Linux.
publisher: Daniele Di Sarli (danieleds)
license:   unset
description: |
  It helps developers by providing all you can expect from a general purpose text editor, such as
  syntax highlighting for more than 100 different languages, code folding, color schemes, file
  monitoring, multiple selection and much more.
  You can search text using the power of regular expressions. You can organize documents side by
  side. You can use real-time highlighting to find near identifiers in no time.
commands:
  - notepadqq
snap-id:      6iueWFAtx9P2OQz4SIW64Kry9hT8aUCL
tracking:     stable
refresh-date: today at 19:19 AEDT
channels:
  stable:    1.4.8     2018-09-14 (855) 151MB -
  candidate: ↑                                
  beta:      ↑                                
  edge:      1.4.8+git 2019-01-28 (874) 205MB classic
installed:   1.4.8                (855) 151MB -
```
sudo snap refresh notepadqq --edge --classic
update = Fixed!!!
