### ISSUE TITLE
Enforce Single Instance

### ISSUE THREAD

**Issue by dfwdraco76** [notepadqq/notepadqq#828]
**Is your feature request related to a problem? Please describe.**
I'm a fairly new Linux user, just moved over from using Notepad++ for as long as I can remember on Windows.  NPP has a setting which forces the app to only one instance, so if you have it open and double click another file, it opens the file in the existing instance as a new tab, rather than launching another copy of the program.

**Describe the solution you'd like**
I would love if Notepadqq could enforce only one instance of the program, so double-clicking a file opens in the already open instance, rather than launching a second (third,etc.) instance.

**Describe alternatives you've considered**
I've been searching off and on for a couple days for a solution to this problem to no avail.

**Additional context**
Notepadqq v1.4.8 on Linux Mint 19.1

**Comment by JuBan1** [comment]
> it opens the file in the existing instance as a new tab, rather than launching another copy of the program.

This is the default behavior of Notepadqq. The only time you get a new window for every new tab is when it is specifically requested (by calling Nqq with the `--new-window` flag). I guess your operating system mistakenly does that. 

Since you're using Mint your desktop environment is probably Cinnamon or MATE, both of which I don't know. But I'd look into how to change the DE's file association.

**Comment by JuBan1** [comment]
If you find a solution please do post it. If this is "standard" behavior of Mint/Cinnamon it may be worth for us to look into it and try to fix it from our end.

Oh- and one more thing: how did you install Nqq? Via some software center, the Snap, manually, or some user-made package?

**Comment by dfwdraco76** [comment]
Will do.  No solution yet, but I've only had 10 minutes combined over the past several hours to dig around. :/

I installed using the Software Manager within Mint.

**Comment by dfwdraco76** [comment]
I'm not sure if this is useful or not -- I feel like I'm on the right track...
~/.config/mimeapps.list:

```
[Default Applications]
text/plain=com.notepadqq.Notepadqq.desktop
application/javascript=com.notepadqq.Notepadqq.desktop
application/x-httpd-php3=com.notepadqq.Notepadqq.desktop
application/x-httpd-php4=com.notepadqq.Notepadqq.desktop
application/x-httpd-php5=com.notepadqq.Notepadqq.desktop
application/x-m4=com.notepadqq.Notepadqq.desktop
application/x-php=com.notepadqq.Notepadqq.desktop
application/x-ruby=com.notepadqq.Notepadqq.desktop
application/x-shellscript=com.notepadqq.Notepadqq.desktop
application/xml=com.notepadqq.Notepadqq.desktop
text/css=com.notepadqq.Notepadqq.desktop
text/turtle=com.notepadqq.Notepadqq.desktop
text/x-c++hdr=com.notepadqq.Notepadqq.desktop
text/x-c++src=com.notepadqq.Notepadqq.desktop
text/x-chdr=com.notepadqq.Notepadqq.desktop
text/x-csharp=com.notepadqq.Notepadqq.desktop
text/x-csrc=com.notepadqq.Notepadqq.desktop
text/x-diff=com.notepadqq.Notepadqq.desktop
text/x-dsrc=com.notepadqq.Notepadqq.desktop
text/x-fortran=com.notepadqq.Notepadqq.desktop
text/x-java=com.notepadqq.Notepadqq.desktop
text/x-makefile=com.notepadqq.Notepadqq.desktop
text/x-pascal=com.notepadqq.Notepadqq.desktop
text/x-perl=com.notepadqq.Notepadqq.desktop
text/x-python=com.notepadqq.Notepadqq.desktop
text/x-sql=com.notepadqq.Notepadqq.desktop
text/x-vb=com.notepadqq.Notepadqq.desktop
text/yaml=com.notepadqq.Notepadqq.desktop

[Added Associations]
text/x-python=com.notepadqq.Notepadqq.desktop;xed.desktop;
application/javascript=xed.desktop;com.notepadqq.Notepadqq.desktop;
application/x-httpd-php3=xed.desktop;com.notepadqq.Notepadqq.desktop;
application/x-httpd-php4=xed.desktop;com.notepadqq.Notepadqq.desktop;
application/x-httpd-php5=xed.desktop;com.notepadqq.Notepadqq.desktop;
application/x-m4=xed.desktop;com.notepadqq.Notepadqq.desktop;
application/x-php=xed.desktop;com.notepadqq.Notepadqq.desktop;
application/x-ruby=xed.desktop;com.notepadqq.Notepadqq.desktop;
application/x-shellscript=xed.desktop;com.notepadqq.Notepadqq.desktop;
application/xml=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/css=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/turtle=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-c++hdr=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-c++src=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-chdr=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-csharp=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-csrc=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-diff=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-dsrc=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-fortran=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-java=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-makefile=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-pascal=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-perl=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-sql=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/x-vb=xed.desktop;com.notepadqq.Notepadqq.desktop;
text/yaml=xed.desktop;com.notepadqq.Notepadqq.desktop;

```

No command line though yet...

**Comment by dfwdraco76** [comment]
Beyond the above config, all I'm able to find is the gui for file associations.  Nothing here is showing me actual command lines and/or flags being used to launch the apps.  I'm kind of at a loss, not sure where to look.

![image](https://user-images.githubusercontent.com/30734939/51091575-d1bb1780-1751-11e9-9bc8-bc677fa5d5e4.png)

**Comment by JuBan1** [comment]
Since this is the flatpak version, perhaps @scx knows more? Is that an issue with this flatpak in general?

**Comment by scx** [comment]
@JuBan1 

> Since this is the flatpak version, perhaps @scx knows more? Is that an issue with this flatpak in general?

Actually, it could be a flatpak-specific problem.
https://github.com/wxMaxima-developers/wxmaxima/pull/1076#issuecomment-451767487
https://github.com/flathub/org.nextcloud.Nextcloud/issues/10#issue-288554244

@alexlarsson @nedrichards @jurf @TingPing
Do you know something about that?

**Comment by alexlarsson** [comment]
Single-instance support has to be coded in the app by finding the existing running copy of the app and talking to it. This can be done in various ways, some which are naturally blocked by a sandbox like the flatpak one (depending on permissions, etc).

The recommended, always working way to do it is to use dbus. Any flatpak app can always own and talk to its app id (com.notepadqq.Notepadqq in this case) on the session bus, and this can easily be used to find a pre-existing running copy of the app and ask it to open a window. If you're using e.g. glib this is easily done with the GApplication API, and it would surprise me if Qt QApplication didn't have similar support.

**Comment by JuBan1** [comment]
@scx @alexlarsson Thanks, that was very helpful.

@scx I've pushed a patch to master that adds DBus as an alternative to what we currently use. It works well on my system but I haven't tested it as a Flatpak since I don't have anything set up for them. Worst-case scenario it works as well (badly) as it currently does.

To enable that option the `USE_DBUS` flag needs to be set during compile time, so you'd have to add that to your Flatpak install script. If you can pass arguments to QMake then calling it via `qmake "DEFINES+=USE_DBUS"` will do the trick. Otherwise you could add `DEFINES+=USE_DBUS` into `src/ui.pro` via your patch file.

The DBus alternative is a lot nicer than our old, crufty sockets approach. I think we'll eventually make it the default but until then `USE_DBUS` will be needed.

**Comment by JuBan1** [comment]
@dfwdraco76 The patch might not arrive at your doorstep for a long time since the version you get via the software center is the "stable" 1.4.8 version which is fairly old by now. That's pretty much our fault here; we've got some organisational issues that make releasing a new version a bit iffy at the moment.

But you can build Notepadqq yourself to get the latest version (without this bug) if you follow our [installation instructions](https://github.com/notepadqq/notepadqq#build-it-yourself). Since you're using Mint, you'd be following the Ubuntu instruction. You should uninstall the version from the software center before though.

It's not quite as convenient as through the software center but it does get you a better Nqq for the time being.

**Comment by dfwdraco76** [comment]
This is great, thanks @JuBan1 !

However, I've run into an issue already.  I successfully cloned and installed dependencies, ran the configure script...

```
dfwdraco76@ncc-1701:~/git/notepadqq$ ./configure --prefix /usr
checking for QT5 qmake... /usr/bin/qtchooser -run-tool=qmake -qt=5
checking for lrelease... /usr/bin/qtchooser -run-tool=lrelease -qt=5
checking for c++... not found!

```

but I don't get a make file:

```
dfwdraco76@ncc-1701:~/git/notepadqq$ make
make: *** No targets specified and no makefile found.  Stop.

```

Is the missing C++ the problem?

**Comment by dfwdraco76** [comment]
Ok, fixed the missing c++
`sudo apt-get install g++`

Now the configure command shows a lot more
```
dfwdraco76@ncc-1701:~/git/notepadqq$ ./configure --prefix /usr
checking for QT5 qmake... /usr/bin/qtchooser -run-tool=qmake -qt=5
checking for lrelease... /usr/bin/qtchooser -run-tool=lrelease -qt=5
checking for c++... /usr/bin/c++
checking whether c++ compiler builds test program... ok
checking whether c++ compiler supports -std=c++0x... ok
checking whether compiled test program works... ok
checking for make... /usr/bin/make
checking for pkg-config... /usr/bin/pkg-config
checking for Qt5Core library... -lQt5Core
checking for Qt5Gui library... -lQt5Gui -lQt5Core
checking for Qt5Network library... -lQt5Network -lQt5Core
checking for Qt5WebEngine library... -lQt5WebEngine -lQt5WebEngineCore -lQt5Quick -lQt5Gui -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Positioning -lQt5Core
checking for Qt5Widgets library... -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5WebEngineWidgets library... -lQt5WebEngineWidgets -lQt5WebEngineCore -lQt5WebChannel -lQt5Positioning -lQt5Quick -lQt5Qml -lQt5Network -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5PrintSupport library... -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5Svg library... -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5WebSockets library... -lQt5WebSockets -lQt5Network -lQt5Core
checking for Qt5WebChannel library... -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Core
checking for uchardet library... -luchardet
generate Makefile... Info: creating stash file /home/dfwdraco76/git/notepadqq/.qmake.stash
done
```

and make is executing

**Comment by dfwdraco76** [comment]
Beautiful - now when I double click a text file it opens in the current instance.

Thank you for all your help!!

**Comment by dfwdraco76** [comment]
Man I hate to be a pain...  but after compiling this myself, I no longer have an icon on the panel:
![image](https://user-images.githubusercontent.com/30734939/51114716-c0aeec80-17cb-11e9-884f-b9e7c49052a7.png)

It's just a blank space between Calc and Slack

**Comment by JuBan1** [comment]
No worries. The installation process ought to be as easy as possible, and if you encounter these issues then others will too. Best to find them quickly :)

The icon issue is because the icon cache isn't updated yet. Perhaps rebooting would fix that, but you can do it manually via `sudo update-icon-caches /usr/share/icons/*`

**Comment by dfwdraco76** [comment]
Voila -- there's an icon.  You are awesome - thank you so much!!

**Comment by danieleds** [comment]
@scx sorry for the late reply. It wasn't stable enough yet anyway.

**Comment by scx** [comment]
I just backported this feature to the stable branch.
https://github.com/flathub/com.notepadqq.Notepadqq/pull/7
This update should be available in the Flathub repo within 24 hours.
