### ISSUE TITLE
Focus the Advanced Search after opened

### ISSUE THREAD

**Issue by nikolayhg** [notepadqq/notepadqq#831]
**Describe the bug**
After "Advanced Search" is opened, the user enters the search string, but instead of the search string being written in the search view, it is entered in the editor. The search view was not focused.

**To Reproduce**
1. Go to 'Search->Advanced Search' or Press Ctrl+Shift+F
2. Enter search string
4. The search string is written in the editor.

**Expected behavior**
Immediately after opening the advanced search, the focus goes to the search field, the user enters the search string, press enter and sees the search results.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation type: snap
 - Qt version: 5.5.1
 - Notepadqq version: 1.4.8

**Comment by JuBan1** [comment]
Fixed by https://github.com/notepadqq/notepadqq/commit/db7f87b500050ea8fb5efd2ad5ed4be8fad624e0. Thanks

**Comment by nikolayhg** [comment]
thanks!
