### ISSUE TITLE
Perf issue: the cold startup speed is too slow and eats lots of memory, comparing to other editor.

### ISSUE THREAD

**Issue by 9527KGG** [notepadqq/notepadqq#836]
**Describe the bug**
The cold startup speed is too slow, comparing to other editor.

**To Reproduce**
1. Reboot machine.
2. Start notepadqq.
3. Start VS code.

**Observed behavior**
Notepadqq cold startup takes about 10 seconds.
VS code cold startup takes about 5 seconds.

**Expected behavior**
Because NQQ is mostly written in C++, while VS code is implemented by Javascript. The cold startup of NQQ should be much faster than VS Code.

What I observed: when NQQ started from terminal, it prompts some warning message: 

_/home/XXX/Templates was removed, reassigning TEMPLATES to homedir
/home/XXX/Public was removed, reassigning PUBLICSHARE to homedir
/home/XXX/Documents was removed, reassigning DOCUMENTS to homedir
/home/XXX/Music was removed, reassigning MUSIC to homedir
/home/XXX/Videos was removed, reassigning VIDEOS to homedir
Missing icon:  "edit-clear"
Missing icon:  "go-previous"
Missing icon:  "go-next"
Missing icon:  "go-bottom"
Missing icon:  "view-refresh"
Missing icon:  "document-open-recent"
Missing icon:  "application-exit"
Missing icon:  "edit-delete"
Missing icon:  "edit-select-all"
Missing icon:  "go-next"
Missing icon:  "go-previous"
Missing icon:  "go-jump"
Missing icon:  "view-fullscreen"
Missing icon:  "system-run"
Missing icon:  "window-new"
Missing icon:  "help-about"_

Seems NQQ startup does lots of checking, which failed and  slow down the code startup.

**Environment (please complete the following information):**
OS: Ubuntu 18.04
Installation type: snap
Qt version: 5.5.1
Notepadqq version: 1.4.8

**Comment by 9527KGG** [comment]
I notice:

A blank VS code consumes about 500MB memory. A blank NQQ take about 450MB (200MB+for NQQ process and 200MB+ for QtWebEngineProcess)

Considering VS code is more powerful than NQQ, on Linux, I don't see a reason to preference NQQ over VS code.

As a comparison, on Windows, reason to prefer Notepad++ over VS code: NPP starts faster than VS code. NPP consumes much less memory than VS code.

I understand that comparing NQQ to VScode or NPP does not make much sense. 

So just my cents, for your reference.

**Comment by 9527KGG** [comment]
I will keep NQQ on hold, till one day you merge your fork back to the main line. Thanks.

**Comment by 9527KGG** [comment]
I once thought NQQ is an alternative for NPP on Linux/Mac. But seems NQQ is far behind NPP.

**Comment by Sorky** [comment]
I'm also now experiencing slow startup speed and occasional lock-ups

**Comment by 9527KGG** [comment]
Finally, I gave up NQQ and switch to gneay ^_^.

I've unsubscribed the thread. Free free to close the issue if it no longer repro.

**Comment by danieleds** [comment]
Fixed in master (#890, c0efb1b275d2a260d18d172a1a739821ce134f80)
