### ISSUE TITLE
Snap run can not input Chinese

### ISSUE THREAD

**Issue by sonichy** [notepadqq/notepadqq#837]
Environment:
Deepin Linux
Sougou Chinese input methord.
Snap notepadqq

**Comment by dqwyy** [comment]
I installed notepadqq via snap but can not input Chinese by using the Chinese IME *[Rime](https://github.com/rime/home)*. My OS is Ubuntu 18.04.

**Comment by JuBan1** [comment]
Is Rime using fcitx? [Snap added support for it only in Ubuntu 18.10](https://trello.com/c/KSLXgc5E/7-add-fcitx-support-to-desktop-snaps). Does it work with other Snap apps?

**Comment by dqwyy** [comment]
Thanks for your comment.

> Is Rime using fcitx?

I'm using the [ibus version](https://github.com/rime/home/wiki/RimeWithIBus).

> Does it work with other Snap apps?

Yes, it is. It works well in Sublime Text.

**Comment by zhengzepeng** [comment]
Can anyone solve this problem?I use sougou in ubuntu18.04 and can't input chinese.

**Comment by dqwyy** [comment]
> Can anyone solve this problem?I use sougou in ubuntu18.04 and can't input chinese.

As for me, I switched to another text editor, Kwrite/Kate for example, which has the similar functions, features and user interface. 😂
