### ISSUE TITLE
Advanced Search: Autocompletion handles uppercase/lowercase incorrectly

### ISSUE THREAD

**Issue by patrickroocks** [notepadqq/notepadqq#842]
**Describe the bug**
When using the advanced search of Notepadqq together with "match case" it is not possible to search for the same word with a lower case. 

**Related**
This bug is quite similar to the description in: https://github.com/notepadqq/notepadqq/issues/834
But the described bug is not reproducible for me, as the standard search works fine. The bug is only within the advanced search.

**To Reproduce**
1. Open any file
2. Type Crtl+Shift+F or go to "Search | Advanced Search"
3. Type (within the advanced search dock) in the "Search:" field "a"
4. Press the "Search" button
5. Press the "Clear Search History" Button (with the small green "+" symbol)
6. Type "A"
7. Click on "Match case" checkbox (as we want to search for the search for capital "A" only)
8. **Bug:** Large "A" turns into a small "a"
9. Type "A" again (now "match case" is really active!)
10. Click on the "Match Whole Words Only" checkbox
11.  **Bug:** Again, large "A" turns into a small "a".

**Expected behavior**
The large A should not turn into a small a again. At least not in those cases, where "Match Case" is activated in the next step or was already activated.

**Workaround**
Click directly on search and do not click on any of the checkboxes, i.e., the search textbox may not loose focus before the advanced search is started.

**Screenshots**
None.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation type snap
 - Qt version 5.5.1
 - Notepadqq version 1.4.8

**Comment by JuBan1** [comment]
That one I can reproduce. As of patch https://github.com/notepadqq/notepadqq/commit/d5be1a2d6a0057ab451145aa151194c2b0ffc75d the auto-completer will respect case sensitivty.

But this isn't the same sort of bug that caused #834 because those search fields already had the correct settings applied but it gave me an idea of why it may happen. Much appreciated.
