### ISSUE TITLE
Impossible to stop auto-complete with advanced search find/replace

### ISSUE THREAD

**Issue by aaronfranke** [notepadqq/notepadqq#846]
**Describe the bug**

It's currently impossible to perform a replace if you've previously replaced with a different casing because there's no way to disable the advanced search auto-complete.

**To Reproduce**

1. Press Ctrl+F and click Advanced Search
2. Have a text file with "apple" and "APPLE" in it
3. Case-sensitive find/replace "apple" with "orange"
4. Try to perform another case-sensitive replace for "APPLE" with "ORANGE"
5. Auto-complete keeps changing "ORANGE" to "orange" when you click outside of the box

**Expected behavior**

Notepadqq should accept my text as-is, without auto-complete, unless I specifically click the suggestion.

**Environment:**
 - OS: Ubuntu 18.04
 - Installation type: Repo
 - Qt version: 5.9.5
 - Notepadqq version: 1.4.2

**Additional context**

Work-around: Delete `~/.config/Notepadqq` after every search operation to clear auto-complete history.

**Comment by JuBan1** [comment]
Thanks, I think we fixed this issue in #842 just recently. I don't know when these fixes will arrive in the repository (things are very sluggish at the moment). If it's a big bother you can compile Nqq from source to get the most up-to-date version that includes this fix.
