### ISSUE TITLE
Where is the configure file of notepadqq?

### ISSUE THREAD

**Issue by Zhao-Michael** [notepadqq/notepadqq#848]
![image](https://user-images.githubusercontent.com/15730936/52533752-67f35500-2d73-11e9-8a89-16355b42c7ff.png)
somehow, I can't display the toolbar, i think this is a bug, user can't find a entry to change setting in this way.

**Comment by Zhao-Michael** [comment]
The layout of notepadqq has been restored after i delete /home/<username>/.config/Notepadqq
![image](https://user-images.githubusercontent.com/15730936/52533953-16989500-2d76-11e9-8bc9-2159487ddea5.png)

**Comment by JuBan1** [comment]
Yes, the config file is in `~/.config/Notepadqq/Notepadqq.ini`.

But hiding the toolbar is a feature. You can hide/unhide it with CTRL+M. You probably pressed it accidentally.

**Comment by hosseinkhojany** [comment]
The only way I found to restore the settings was to delete it
