### ISSUE TITLE
standard JS compliant

### ISSUE THREAD

**Issue by jfoclpf** [notepadqq/notepadqq#849]
**Is your feature request related to a problem? Please describe.**
I'm a great fun of this text editor, but I was wondering if you have any ideas of allowing a plugin or any kind of integrated built-in feature or option to allow certain JS code to be standardjs compliant.

https://standardjs.com/#are-there-text-editor-plugins

**Describe the solution you'd like**
Plugin, feature, or merely an option such that the code before saving, or in real-time could be matched with standardjs rules. I know you have an option for node.js path extensions, but can I run a command line automatically before saving the file? It may be the trick, outputting the results within the active window, like you do for `search` option

**Describe alternatives you've considered**
The alternatives are a burden, because I have to save, run the command-line, and then amend again. standardjs has an option `--fix` but I like to be in control of what part of the code is changed before sending it to production

Thanks for the great tool

**Comment by JuBan1** [comment]
Our extension "system" is lacklustre to say the least. I don't think you can do this comfortably yet. 

You can create a Run Command (under the Run menu field) to execute `standard` via hotkey and write the output into another text file that you can open in Nqq too. It's still cumbersome but the best you could do for now.

A decent extension system is on my want-to-do-before-I-die list.

**Comment by jfoclpf** [comment]
Thank you for the reply

**Comment by danieleds** [comment]
Closing for now. This would be nice to implement as soon as the plugin system is renewed.

Thank you
