### ISSUE TITLE
A way to turn off line numbering

### ISSUE THREAD

**Issue by eluuk** [notepadqq/notepadqq#852]
**Is your feature request related to a problem? Please describe.**
I'd like to use Notepadqq also for writing plain text or markdown but prefer an editor w/out line numbers for them

**Describe the solution you'd like**
AFAIK there's no way to turn line numbering off/on, which would be a useful (and simple) feature. Two check boxes under Settings > Preferences > General: `Turn off line numbering for: plain text [tick] markdown [tick]`

**Describe alternatives you've considered**
Hacking `app.js`?

**Comment by danieleds** [comment]
Implemented in 45f90b6705801f368c435897ca23404735ab2d8d
