### ISSUE TITLE
Use my build of v1.4.8 for the experimental mac version offered

### ISSUE THREAD

**Issue by james-yeoman** [notepadqq/notepadqq#861]
**Is your feature request related to a problem? Please describe.**
The current experimental release for Mac has the issue of a hardcoded link to QT.

**Describe the solution you'd like**
I have built v1.4.8 from source and attached it as a zip to this issue. Would it be possible to review the build and assess whether it's built correctly from your perspective and therefore be able to use it as the mac release?

**Describe alternatives you've considered**
I have tested the build on QT version 5.12.1 and 5.12.2 so I can confirm that it doesn't depend on a specific installation of QT.

[notepadqq.zip](https://github.com/notepadqq/notepadqq/files/3007771/notepadqq.zip)

**Comment by danieleds** [comment]
This will be fixed soon in the repo. Thank you
