### ISSUE TITLE
Advance search result...

### ISSUE THREAD

**Issue by erikdemarco** [notepadqq/notepadqq#872]
Advance search result must be expanded by default.
Let me ask you what is the purpose user when doing a search?
They want to see the result! why you collapse the result by default?
What it feels when google do collapse their search results? its really annoying to click 2 times just to get the result right?

**Comment by JuBan1** [comment]
This sounds like a good idea. I quickly implemented it in #874.

However, it's only when searching through one document. 
I think with "Search all documents" the collapsed view gives you a better overview of how many files were searched.
I think that's a good compromise.
