### ISSUE TITLE
cannot open any file on external drives

### ISSUE THREAD

**Issue by A13XIS** [notepadqq/notepadqq#878]
**I'm submitting a bug report**

**Current behavior**
Fails to open files on root directories of secondary drives (internal or external)
with error "Permission denied".

**Expected behavior**
Open file

**Suspected Cause**
default mount directory (/media/*username*/*drivename*) belongs to root. Bug still occurs after changing the owner of *drivename* to *username*.  

**Minimal reproduction of the problem with instructions**
Create file in root directory of a secondary drive and try to open it.

**Please tell us about your environment:**
    Ubuntu 18.04
    Installation type snap [classic]
    Qt version 5.5.1
    Notepadqq version 1.4.8

**Comment by A13XIS** [comment]
I experimented a little further and found out that the error also shows up in any directory on an external drive. Not just the root folder.

**Comment by WalJT** [comment]
Could be due to the sandboxing done by snaps, since notepadqq is no longer packaged using classic confinement. Try running "snap connect notepadqq:removable-media". It should work after that.

**Comment by A13XIS** [comment]
Gotcha!
That solves the problem. Didn't really think of it as "removable media" since (in my case) it's an internal drive, but it has to be mounted and unmounted, so it totally is.
