### ISSUE TITLE
Slack opens login page using Notepadqq, can't remove association

### ISSUE THREAD

**Issue by elpreto** [notepadqq/notepadqq#883]
Hi.

I am using Kubuntu 19.04 and notepadqq from the repository.
I had to uninstall Notepadqq, because I use Slack to work and when Slack tries to authenticate, Notepadqq takes the authentication call and Slack fails to authenticate.

After removing Notepadqq, Chromium takes the authentication request and I can use slack normally.

I have read here that Notepadqq can take network addresses to open files and that kind of things, but I checked in all the possible options of Notepadqq, and I can not see anywhere the options to handle the protocols that Notepadqq tries to open to try to remove it.

**Comment by danieleds** [comment]
To me this seems a problem with Slack or with Kubuntu.

Anyway, as a workaround you can edit your [notepadqq.desktop](notepadqq.desktop) and remove any reference to "text/html".
