### ISSUE TITLE
Show Symbol

### ISSUE THREAD

**Issue by vejobuj** [notepadqq/notepadqq#89]
Hi, I use the up to date notepadqq-git from AUR
Just to report the view "Show Symbol" doesn't seems to work and it doesn't seems to save the settings of the view.

http://i.imgur.com/aCO6jGx.png

**Comment by aoloe** [comment]
this stackoverflow answer:
http://stackoverflow.com/questions/19246539/is-it-possible-to-show-hidden-characters-in-codemirror
shows how to show the hidden characters and points to an existing codemirror addon that also does the same:
https://github.com/coderaiser/cm-show-invisibles

**Comment by Teklad** [comment]
@danieleds , I think this issue as well as #166 can be closed now.

**Comment by danieleds** [comment]
Fixed with #244
