### ISSUE TITLE
Non-ascii text in unsaved tabs gets converted to question marks

### ISSUE THREAD

**Issue by david-cortes** [notepadqq/notepadqq#904]
**Steps to reproduce:**
* Write some non-ascii characters in an unsaved tab (e.g. `фывфывфвы`) along with some ascii characters.
* Close notepadqq.
* Launch notepadqq again.

**Expected behavior:** should preserve the non-ascii text just like it preserves the ascii text.

**Actual behavior:** when relaunched, all non-ascii characters are replaced with question marks.

**Comment by danieleds** [comment]
Hi, could you please fill the issue template so that we know which version or setup is affected?

Thank you

**Comment by david-cortes** [comment]
Extra info:

**Environment (please complete the following information):**
 - OS: debian testing
 - Installation type: compiled from source
 - Qt version: 5.11.3
 - Notepadqq version: 1.4.8

Another update: the bug only happens in unsaved tabs that were restored from previous session and had ascii-only text on them written before.


![txt_nonascii_before](https://user-images.githubusercontent.com/11860098/65910499-7f02b800-e3d3-11e9-8baf-432bab3fac64.png)
![txt_nonascii_after](https://user-images.githubusercontent.com/11860098/65910498-7f02b800-e3d3-11e9-992d-e6772399751f.png)

**Comment by danieleds** [comment]
It appears to be a non-compatible change in the latest version of an upstream library, uchardet.
The good news is that I have a straightforward fix.

**Comment by danieleds** [comment]
@david-cortes it should be fixed in master. Can you confirm?

**Comment by david-cortes** [comment]
Working fine now, thanks.
