### ISSUE TITLE
Future of the project?

### ISSUE THREAD

**Issue by chclxds** [notepadqq/notepadqq#955]
Has this program been **stopped/abandoned** from its development?

**Comment by sagitter** [comment]
Looks like it's so; no commits, no replies, ...

**Comment by chclxds** [comment]
SAD

**Comment by jugrajsingh** [comment]
Any active maintainer of this repo?

**Comment by krulkrul** [comment]
It would be sad if this project dies, it looks very promissing

**Comment by dorsany** [comment]
this is awesome project! please maintain it, the community can help

**Comment by jcs090218** [comment]
😭
