### ISSUE TITLE
Sort and blocksort operations

### ISSUE THREAD

**Issue by ineuw** [notepadqq/notepadqq#960]
**Is your feature request related to a problem? Please describe.**
Are there plugins for 
line sort?
unique line sort?
block sort?
block search?
block copy?
block cut?
block paste?
block delete?

**Describe the solution you'd like**
Make these available

*Describe alternatives you've considered**
None found in Linux apps.

**Comment by ericjs** [comment]
Having used this in other text editors, I agree that having line sort and unique line sort is handy. But I'm pretty sure you can create that yourself pretty easily with Run commands (see Run menu), by piping through the sort command.

**Comment by absolutelynothinghere** [comment]
Really missing this feature!

> But I'm pretty sure you can create that yourself pretty easily with Run commands (see Run menu), by piping through the sort command.

Care to elaborate? I tried `sort -o %selection% %selection%` for a basic sort of selected lines but it didn't work.

**Comment by ahoffer** [comment]
`sort -o %selection% %selection%` still does not work to sort lines in the current file.

**Comment by ahoffer** [comment]
I tried a lot of combinations, but I could not get the Run commands to sort the lines of a file.

**Comment by durban77** [comment]
Save the file to be able to use the placeholders in the Run menu, then `sort -o %path% %path%` and reload the file.

**Comment by michas79de** [comment]
> Save the file to be able to use the placeholders in the Run menu, then `sort -o %path% %path%` and reload the file.

`sort "%path%" -o "%path%"
`
works for me, if the file was saved. (And save before and reload after the sorting is mandatory.)
