### ISSUE TITLE
No Macros

### ISSUE THREAD

**Issue by rubmz** [notepadqq/notepadqq#968]
**Describe the bug**
You had macros and YOU REMOVED THEM.

**To Reproduce**
1. create a good app.
2. destroy it!

**Expected behavior**
BE SANE!

**Environment (please complete the following information):**
LINUX

**Additional context**
THE PEOPLE DEMAND MACROS NOW :-)

**Comment by he3als** [comment]
why were they removed in the first place?

**Comment by danieleds** [comment]
they've never been there :) We only had a non-working prototype.

Closing this issue, but feel free to open new ones
