### ISSUE TITLE
Search in files

### ISSUE THREAD

**Issue by withthelemons** [notepadqq/notepadqq#98]
This is one of key features of Notepad++ and it's missing in Notepadqq

**Comment by danieleds** [comment]
Planned!
These days I'm trying to figure out how to switch to qwebengine without performance degradations, so if someone wants to help with this feature he's welcome! Otherwise, I'll work on it asap.

**Comment by danieleds** [comment]
see #aba5a7de3a451568bf8c7d05eb87e2fed9677d5f, work in progress

**Comment by Shopingjs** [comment]
On my machine, Notepadqq stops responding when searching

**Comment by danieleds** [comment]
At the moment, it searches in every subdirectory of the specified path. It is very likely the cause.
There will be an option to exclude subdirectories.

**Comment by danieleds** [comment]
See 32de7efd6cfe86a620482222e5cd408fdeeeb3e2 for the option to exclude subdirs.

**Comment by danieleds** [comment]
The big part is done (d9cae82b671c3012b7bd9233fa66a08bb58a01f0).
The only missing part is user-interaction with the search results.

**Comment by withthelemons** [comment]
Nice! Maybe after it's done I'll switch from Sublime Text to Notepadqq

**Comment by danieleds** [comment]
Implemented (31490970c060a4fc2b3d8b5d34f645b6d2a67338)
